Dual Display Billboard: DisplayClockManager Class Reference
DisplayClockManager Class Reference
Advanced clock display system with multiple face styles.
#include <display_clock_manager.h>
Public Member Functions
DisplayClockManager (DisplayManager *dm, TimeManager *tm)
Constructs the clock manager.
bool begin ()
Initializes the clock manager system.
void begin (int firstCS, int secondCS)
Initialize clock manager with specific display pin configuration.
void displayClockOnBothDisplays ()
Displays clock on both configured displays.
void setClockLabel (const String &label)
Sets custom label for clock display.
String getClockLabel ()
Gets current clock label.
void setSecondDisplayEnabled (bool enabled)
Enables or disables second display.
void setDisplayPins (int firstCS, int secondCS)
Configures display chip select pins.
void setClockFace (ClockFaceType faceType)
Set active clock face style.
ClockFaceType getClockFace () const
Get current active clock face type.
String getClockFaceName (ClockFaceType faceType) const
Get human-readable name for clock face type.
Private Member Functions
void displayAnalogClock (TFT_eSPI &tft)
Renders classic analog clock face with circular design.
void displayDigitalClock (TFT_eSPI &tft)
Renders modern digital clock with large cyan text.
void displayMinimalistClock (TFT_eSPI &tft)
Renders minimalist clock with clean, simple design.
void displayModernSquareClock (TFT_eSPI &tft)
Renders modern square analog clock with adaptive display size support.
void displayClockOnDisplay (TFT_eSPI &tft, int csPin)
Renders clock display on specified hardware display.
Private Attributes
DisplayManager * displayManager
TimeManager * timeManager
int firstScreenCS
int secondScreenCS
bool enableSecondDisplay
ClockFaceType currentClockFace
Detailed Description
Advanced clock display system with multiple face styles.
Manages clock rendering across dual displays with support for:
Multiple clock face styles (analog, digital, minimalist, modern square)
Dual display synchronization
Dynamic sizing for different display types
Professional typography
Definition at line 68 of file display_clock_manager.h.
Constructor & Destructor Documentation
DisplayClockManager()
DisplayClockManager::DisplayClockManager (DisplayManager * dm, TimeManager * tm)
Constructs the clock manager.
Constructor - initializes display clock manager with required dependencies.
Parameters
dm Pointer to the display manager instance
tm Pointer to the time manager instance
dm DisplayManager instance for TFT control
tm TimeManager instance for time synchronization
Definition at line 33 of file display_clock_manager.cpp.
References CLOCK_MODERN_SQUARE, currentClockFace, DISPLAY_SPLASH_DURATION_MS, displayManager, enableSecondDisplay, firstScreenCS, secondScreenCS, and timeManager.
Member Function Documentation
begin() [1/2]
bool DisplayClockManager::begin ()
Initializes the clock manager system.
Initialize clock manager (basic initialization)
Returns
true if initialization successful, false otherwise
true if initialization successful, false if dependencies missing
Definition at line 50 of file display_clock_manager.cpp.
References displayManager, and timeManager.
begin() [2/2]
void DisplayClockManager::begin (int firstCS, int secondCS)
Initialize clock manager with specific display pin configuration.
Parameters
firstCS Chip select pin for primary display
secondCS Chip select pin for secondary display
Definition at line 62 of file display_clock_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, firstScreenCS, and secondScreenCS.
displayAnalogClock()
void DisplayClockManager::displayAnalogClock (TFT_eSPI & tft) private
Renders classic analog clock face with circular design.
Parameters
tft TFT_eSPI instance for rendering
Features:
Circular clock face with sky blue border
White hour markers at all 12 positions
Red hour and minute hands with smooth movement
White center dot
Optimized for 80x160 displays
Definition at line 141 of file display_clock_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS.
Referenced by displayClockOnDisplay().
displayClockOnBothDisplays()
void DisplayClockManager::displayClockOnBothDisplays ()
Displays clock on both configured displays.
Display clock on both screens simultaneously.
Coordinates rendering on primary and secondary displays with proper display manager integration for consistent timing and synchronization.
Definition at line 409 of file display_clock_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, displayClockOnDisplay(), displayManager, enableSecondDisplay, DisplayManager::getTFT(), DisplayManager::selectDisplayForImage(), and timeManager.
Referenced by SlideshowManager::showClock().
displayClockOnDisplay()
void DisplayClockManager::displayClockOnDisplay (TFT_eSPI & tft, int csPin) private
Renders clock display on specified hardware display.
Parameters
tft TFT_eSPI instance for rendering
csPin Chip select pin for target display
Complete clock rendering pipeline:
Display selection via CS pin control
Screen preparation and clearing
Adaptive label positioning based on display size
Clock face rendering based on current style
Display deselection
Label positioning adapts to display size:
Small displays (≤80px width): Center at X=40
Large displays (>80px width): Center at X=120
Definition at line 85 of file display_clock_manager.cpp.
References CLOCK_CLASSIC_ANALOG, CLOCK_DIGITAL_MODERN, CLOCK_MINIMALIST, CLOCK_MODERN_SQUARE, currentClockFace, DISPLAY_SPLASH_DURATION_MS, displayAnalogClock(), displayDigitalClock(), displayMinimalistClock(), displayModernSquareClock(), TextUtils::drawUnicodeText(), TimeManager::getClockLabel(), TextUtils::getUnicodeTextWidth(), timeManager, and TextUtils::toDisplayText().
Referenced by displayClockOnBothDisplays().
displayDigitalClock()
void DisplayClockManager::displayDigitalClock (TFT_eSPI & tft) private
Renders modern digital clock with large cyan text.
Parameters
tft TFT_eSPI instance for rendering
Features:
Large font size for excellent readability
Cyan color for modern appearance
HH:MM format (24-hour time)
Centered positioning
Definition at line 190 of file display_clock_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS.
Referenced by displayClockOnDisplay().
displayMinimalistClock()
void DisplayClockManager::displayMinimalistClock (TFT_eSPI & tft) private
Renders minimalist clock with clean, simple design.
Parameters
tft TFT_eSPI instance for rendering
Features:
Minimal visual elements for clean appearance
White text on black background
Single decorative line under time
Centered time display
Definition at line 220 of file display_clock_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS.
Referenced by displayClockOnDisplay().
displayModernSquareClock()
void DisplayClockManager::displayModernSquareClock (TFT_eSPI & tft) private
Renders modern square analog clock with adaptive display size support.
Parameters
tft TFT_eSPI instance for rendering
Features:
Rounded square border design for modern aesthetic
Adaptive sizing for both 80x160 and 240x240 displays
Blue analog hands with red center dot
Quarter-hour markers (12, 3, 6, 9) are longer than others
Time synchronization validation with fallback display
Graceful error handling for coordinate and math errors
Definition at line 254 of file display_clock_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, and getClockLabel().
Referenced by displayClockOnDisplay().
getClockFace()
ClockFaceType DisplayClockManager::getClockFace () const
Get current active clock face type.
Returns
Current ClockFaceType enumeration value
Definition at line 448 of file display_clock_manager.cpp.
References currentClockFace.
getClockFaceName()
String DisplayClockManager::getClockFaceName (ClockFaceType faceType) const
Get human-readable name for clock face type.
Parameters
faceType Clock face type to get name for
Returns
User-friendly name string
Definition at line 457 of file display_clock_manager.cpp.
References CLOCK_CLASSIC_ANALOG, CLOCK_DIGITAL_MODERN, CLOCK_MINIMALIST, CLOCK_MODERN_SQUARE, and DISPLAY_SPLASH_DURATION_MS.
Referenced by setClockFace().
getClockLabel()
String DisplayClockManager::getClockLabel ()
Gets current clock label.
Get current clock label text.
Returns
Current clock label string
Current clock label or "Clock" if not set
Definition at line 379 of file display_clock_manager.cpp.
References TimeManager::getClockLabel(), and timeManager.
Referenced by displayModernSquareClock().
setClockFace()
void DisplayClockManager::setClockFace (ClockFaceType faceType)
Set active clock face style.
Parameters
faceType Clock face type from ClockFaceType enumeration
Definition at line 439 of file display_clock_manager.cpp.
References currentClockFace, DISPLAY_SPLASH_DURATION_MS, and getClockFaceName().
Referenced by SlideshowManager::showClock().
setClockLabel()
void DisplayClockManager::setClockLabel (const String & label)
Sets custom label for clock display.
Set custom clock label text.
Parameters
label Custom text label to display
label Custom label text to display above clock
Definition at line 368 of file display_clock_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, TimeManager::setClockLabel(), and timeManager.
setDisplayPins()
void DisplayClockManager::setDisplayPins (int firstCS, int secondCS)
Configures display chip select pins.
Configure display pin assignments.
Parameters
firstCS First display CS pin
secondCS Second display CS pin
firstCS Chip select pin for primary display
secondCS Chip select pin for secondary display
Definition at line 397 of file display_clock_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, firstScreenCS, and secondScreenCS.
setSecondDisplayEnabled()
void DisplayClockManager::setSecondDisplayEnabled (bool enabled)
Enables or disables second display.
Enable or disable second display.
Parameters
enabled true to enable second display, false to disable
Definition at line 387 of file display_clock_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, and enableSecondDisplay.
Field Documentation
currentClockFace
ClockFaceType DisplayClockManager::currentClockFace private
Definition at line 77 of file display_clock_manager.h.
Referenced by DisplayClockManager(), displayClockOnDisplay(), getClockFace(), and setClockFace().
displayManager
DisplayManager* DisplayClockManager::displayManager private
Definition at line 70 of file display_clock_manager.h.
Referenced by begin(), DisplayClockManager(), and displayClockOnBothDisplays().
enableSecondDisplay
bool DisplayClockManager::enableSecondDisplay private
Definition at line 75 of file display_clock_manager.h.
Referenced by DisplayClockManager(), displayClockOnBothDisplays(), and setSecondDisplayEnabled().
firstScreenCS
int DisplayClockManager::firstScreenCS private
Definition at line 73 of file display_clock_manager.h.
Referenced by begin(), DisplayClockManager(), and setDisplayPins().
secondScreenCS
int DisplayClockManager::secondScreenCS private
Definition at line 74 of file display_clock_manager.h.
Referenced by begin(), DisplayClockManager(), and setDisplayPins().
timeManager
TimeManager* DisplayClockManager::timeManager private
Definition at line 71 of file display_clock_manager.h.
Referenced by begin(), DisplayClockManager(), displayClockOnBothDisplays(), displayClockOnDisplay(), getClockLabel(), and setClockLabel().
The documentation for this class was generated from the following files:
include/display_clock_manager.h
src/display_clock_manager.cpp