Dual Display Billboard: Logger Class Reference
Logger Class Reference
Hierarchical logging system with build-time optimization.
#include <logger.h>
Public Types
enum Level {
ERROR = 1 , WARN = 2 , INFO = 3 , DEBUG = 4 ,
VERBOSE = 5
}
Logging priority levels in ascending order of verbosity.
Static Public Member Functions
static void init (unsigned long baudRate=115200)
Explicit logger initialization with custom baud rate.
static void setLevel (Level level)
Sets runtime log level threshold.
static Level getLevel ()
Gets current runtime log level threshold.
static bool enableFileLogging (const String &filePath="/logs/system.log")
Enables file logging to specified file path.
static void disableFileLogging ()
Disables file logging.
static bool isFileLoggingEnabled ()
Checks if file logging is currently enabled.
static void log (Level level, const String &tag, const String &message)
Core logging function with explicit level specification.
static void logf (Level level, const String &tag, const char *format,...)
Printf-style formatted logging with explicit level.
static void error (const String &tag, const String &message)
Log error-level message (highest priority)
static void warn (const String &tag, const String &message)
Log warning-level message
static void info (const String &tag, const String &message)
Log informational message (production default)
static void debug (const String &tag, const String &message)
Log debug-level message (development use)
static void verbose (const String &tag, const String &message)
Log verbose-level message (maximum detail)
static void errorf (const String &tag, const char *format,...)
Printf-style error logging.
static void warnf (const String &tag, const char *format,...)
Printf-style warning logging.
static void infof (const String &tag, const char *format,...)
Printf-style informational logging.
static void debugf (const String &tag, const char *format,...)
Printf-style debug logging.
static void verbosef (const String &tag, const char *format,...)
Printf-style verbose logging.
static void printSystemInfo ()
Output comprehensive ESP32 system information.
static void printWiFiStatus ()
Output detailed WiFi connection status.
static void printMemoryInfo ()
Output memory usage analysis including PSRAM.
Static Private Member Functions
static void ensureInitialized ()
Ensures logger is initialized before use.
static void writeToFile (const String &message)
Writes message to log file if file logging is enabled.
Static Private Attributes
static bool initialized = false
Lazy initialization state tracking.
static bool fileLogging = false
File logging enabled state.
static String currentLogFile = ""
Current log file path.
Detailed Description
Hierarchical logging system with build-time optimization.
Singleton logger class providing comprehensive logging infrastructure for embedded ESP32 systems. Features five priority levels with build-time filtering to eliminate runtime overhead in production environments.
The logger automatically initializes on first use and provides both simple string logging and printf-style formatted output. All logging calls are subject to compile-time filtering based on build flags, ensuring zero performance impact for disabled log levels.
Thread Safety: Not required for single-threaded ESP32 Arduino environment Memory Usage: Minimal static allocation with 512-byte formatting buffers Performance: Zero overhead for disabled levels via preprocessor elimination
Definition at line 61 of file logger.h.
Member Enumeration Documentation
Level
enum Logger::Level
Logging priority levels in ascending order of verbosity.
Five-level hierarchy designed for embedded systems with clear separation between production-suitable levels (ERROR/WARN/INFO) and development levels (DEBUG/VERBOSE).
Enumerator
ERROR
Critical errors requiring immediate attention.
WARN
Non-critical issues and recoverable errors.
INFO
General operational information (production default)
DEBUG
Development debugging and detailed state information.
VERBOSE
Maximum detail for intensive debugging scenarios.
Definition at line 94 of file logger.h.
Member Function Documentation
debug()
void Logger::debug (const String & tag, const String & message) static
Log debug-level message (development use)
Logs debug-level message with simplified interface.
Parameters
tag Component identifier
message Debug information
Convenience wrapper for debug-level logging suitable for development troubleshooting, state tracking, and detailed operational insight. Typically filtered out in production builds for performance optimization.
Parameters
tag Component or module identifier for message categorization
message Debug message content with detailed system information
Note
Equivalent to calling log(DEBUG, tag, message)
Subject to build-time DEBUG level filtering via LOGGER_LEVEL_DEBUG
Intended primarily for development and debugging scenarios
Higher verbosity than INFO level with more detailed output
See also
log() for general-purpose logging with explicit level specification
debugf() for printf-style formatted debug logging
Level::DEBUG for debug level threshold definition
Since
v0.9
Definition at line 387 of file logger.cpp.
References DEBUG, DISPLAY_SPLASH_DURATION_MS, and log().
Referenced by debugf().
debugf()
void Logger::debugf (const String & tag, const char * format, ...) static
Printf-style debug logging.
Printf-style formatted debug logging convenience function.
Parameters
tag Component identifier
format Printf format string
... Variable arguments
Combines printf-style formatting with debug-level logging for flexible development troubleshooting message composition. Optimized for detailed system state reporting and development diagnostic output.
Parameters
tag Component or module identifier for message categorization
format Printf-style format string with embedded format specifiers
... Variable arguments matching format specifiers in format string
Note
Uses 512-byte internal buffer for formatted message assembly
Subject to build-time DEBUG level filtering via LOGGER_LEVEL_DEBUG
Calls debug() internally after formatting variable arguments
Buffer overflow protection via vsnprintf size limiting
Typically filtered out in production builds for performance
See also
debug() for simple string-based debug logging
logf() for general-purpose formatted logging with explicit level
Level::DEBUG for debug level threshold definition
Since
v0.9
Definition at line 542 of file logger.cpp.
References debug(), and DISPLAY_SPLASH_DURATION_MS.
disableFileLogging()
void Logger::disableFileLogging () static
Disables file logging.
Stops writing log messages to file while continuing to output to Serial. Clears the current log file path and disables the file logging flag.
Note
Serial logging continues unaffected
Can be re-enabled later with enableFileLogging()
See also
enableFileLogging() to start file logging
isFileLoggingEnabled() to check current state
Since
v0.9
Definition at line 669 of file logger.cpp.
References currentLogFile, DISPLAY_SPLASH_DURATION_MS, fileLogging, and writeToFile().
enableFileLogging()
bool Logger::enableFileLogging (const String & filePath = "/logs/system.log") static
Enables file logging to specified file path.
Parameters
filePath Path to log file (will be created if doesn't exist)
Returns
true if file logging was successfully enabled
Initializes LittleFS filesystem and enables logging output to be written to a file in addition to Serial output. Creates the logs directory if it doesn't exist and sets up the log file for writing.
Parameters
filePath Path to log file (default: "/logs/system.log")
Returns
true if file logging was successfully enabled, false otherwise
Note
Requires LittleFS to be available and functioning
Creates parent directory if it doesn't exist
Existing log files will be appended to, not overwritten
File logging continues until explicitly disabled
See also
disableFileLogging() to stop file logging
isFileLoggingEnabled() to check current state
Since
v0.9
Definition at line 610 of file logger.cpp.
References currentLogFile, DISPLAY_SPLASH_DURATION_MS, ensureInitialized(), fileLogging, and writeToFile().
ensureInitialized()
void Logger::ensureInitialized () static private
Ensures logger is initialized before use.
Ensures logger system is properly initialized before use.
Lazy initialization function called automatically by all public logging methods. Initializes Serial communication and system state on first invocation only.
Note
Thread-safe not required in single-threaded Arduino environment
Called automatically - no need for manual invocation
See also
init() for explicit initialization with custom baud rate
Internal initialization check that automatically initializes the logging system if not already done. Provides lazy initialization to ensure Serial communication is available before any logging operations.
Called automatically by all logging functions to guarantee proper initialization state without requiring explicit initialization calls.
Note
This is an internal method called automatically by logging functions
Only performs initialization once regardless of call frequency
Thread-safe and suitable for use from any context
See also
init() for manual logger initialization
initialized static member for initialization state tracking
Since
v0.9
Definition at line 51 of file logger.cpp.
References init(), and initialized.
Referenced by enableFileLogging(), and log().
error()
void Logger::error (const String & tag, const String & message) static
Log error-level message (highest priority)
Logs error-level message with simplified interface.
Parameters
tag Component identifier
message Error message content
Convenience wrapper for error-level logging that eliminates need to specify logging level explicitly. Designed for critical error conditions that require immediate attention and should always be visible in production logs.
Parameters
tag Component or module identifier for message categorization
message Error message content describing the critical condition
Note
Equivalent to calling log(ERROR, tag, message)
Subject to build-time ERROR level filtering via LOGGER_LEVEL_ERROR
Highest priority logging level for critical system issues
See also
log() for general-purpose logging with explicit level specification
errorf() for printf-style formatted error logging
Level::ERROR for error level threshold definition
Since
v0.9
Definition at line 313 of file logger.cpp.
References DISPLAY_SPLASH_DURATION_MS, ERROR, and log().
Referenced by errorf().
errorf()
void Logger::errorf (const String & tag, const char * format, ...) static
Printf-style error logging.
Printf-style formatted error logging convenience function.
Parameters
tag Component identifier
format Printf format string
... Variable arguments
Combines printf-style formatting with error-level logging for flexible critical error message composition. Automatically handles variable argument processing and buffer management for formatted output generation.
Parameters
tag Component or module identifier for message categorization
format Printf-style format string with embedded format specifiers
... Variable arguments matching format specifiers in format string
Note
Uses 512-byte internal buffer for formatted message assembly
Subject to build-time ERROR level filtering via LOGGER_LEVEL_ERROR
Calls error() internally after formatting variable arguments
Buffer overflow protection via vsnprintf size limiting
Format specifiers follow standard printf conventions (s, d, x, etc.)
See also
error() for simple string-based error logging
logf() for general-purpose formatted logging with explicit level
Level::ERROR for error level threshold definition
Since
v0.9
Definition at line 440 of file logger.cpp.
References DISPLAY_SPLASH_DURATION_MS, and error().
getLevel()
Logger::Level Logger::getLevel () static
Gets current runtime log level threshold.
Retrieves the current runtime logging level threshold.
Returns
Current minimum log level
Returns the currently configured logging level that determines which messages are displayed. Useful for conditional logging decisions and dynamic log level management in applications.
Returns
Level Current logging level threshold Messages at this level or lower will be displayed
Note
Reflects runtime level setting, not build-time flag configuration
Default return value is INFO level
Can be used for conditional logic around expensive log operations
See also
setLevel() for configuring logging level threshold
Level enumeration for available logging levels
log() for how level threshold is applied during filtering
Since
v0.9
Definition at line 151 of file logger.cpp.
References currentLevel.
info()
void Logger::info (const String & tag, const String & message) static
Log informational message (production default)
Logs informational message with simplified interface.
Parameters
tag Component identifier
message Information content
Convenience wrapper for informational logging suitable for general system status updates, operational milestones, and user-relevant information. Default logging level providing balanced output for normal operation.
Parameters
tag Component or module identifier for message categorization
message Informational message content for general status updates
Note
Equivalent to calling log(INFO, tag, message)
Subject to build-time INFO level filtering via LOGGER_LEVEL_INFO
Default logging level suitable for production environments
Provides good balance between verbosity and useful information
See also
log() for general-purpose logging with explicit level specification
infof() for printf-style formatted informational logging
Level::INFO for info level threshold definition
Since
v0.9
Definition at line 362 of file logger.cpp.
References DISPLAY_SPLASH_DURATION_MS, INFO, and log().
Referenced by infof(), printMemoryInfo(), printSystemInfo(), and printWiFiStatus().
infof()
void Logger::infof (const String & tag, const char * format, ...) static
Printf-style informational logging.
Printf-style formatted informational logging convenience function.
Parameters
tag Component identifier
format Printf format string
... Variable arguments
Combines printf-style formatting with informational-level logging for flexible general status message composition. Default formatting function providing balanced output suitable for production environments.
Parameters
tag Component or module identifier for message categorization
format Printf-style format string with embedded format specifiers
... Variable arguments matching format specifiers in format string
Note
Uses 512-byte internal buffer for formatted message assembly
Subject to build-time INFO level filtering via LOGGER_LEVEL_INFO
Calls info() internally after formatting variable arguments
Buffer overflow protection via vsnprintf size limiting
Default formatting level for operational status reporting
See also
info() for simple string-based informational logging
logf() for general-purpose formatted logging with explicit level
Level::INFO for info level threshold definition
Since
v0.9
Definition at line 508 of file logger.cpp.
References DISPLAY_SPLASH_DURATION_MS, and info().
Referenced by printMemoryInfo(), printSystemInfo(), and printWiFiStatus().
init()
void Logger::init (unsigned long baudRate = 115200) static
Explicit logger initialization with custom baud rate.
Initializes the logging system with configurable serial communication.
Parameters
baudRate Serial communication speed (default: 115200)
See also
ensureInitialized() for automatic initialization
Sets up Serial communication for logging output with timeout protection and system identification. Displays startup banner and version information to clearly identify system boot and logging initialization.
Initialization process:
Configures Serial communication at specified baud rate
Implements 3-second timeout to prevent indefinite blocking
Uses non-blocking yield() calls to maintain system responsiveness
Displays system identification banner with emoji indicators
Sets initialization state to prevent repeated initialization
Parameters
baudRate Serial communication baud rate (default: 115200) Common values: 9600, 38400, 57600, 115200, 230400
Note
Only active when LOGGER_ENABLED build flag is true
Includes timeout protection to prevent blocking during boot
Can be called multiple times safely (initialization occurs only once)
Displays system banner for easy log identification
See also
ensureInitialized() for automatic initialization
setLevel() for runtime log level configuration
LOGGER_ENABLED build flag for compile-time control
Since
v0.9
Definition at line 85 of file logger.cpp.
References DISPLAY_SPLASH_DURATION_MS, and initialized.
Referenced by ensureInitialized(), and setup().
isFileLoggingEnabled()
bool Logger::isFileLoggingEnabled () static
Checks if file logging is currently enabled.
Returns
true if file logging is active
true if file logging is active, false otherwise
See also
enableFileLogging() to start file logging
disableFileLogging() to stop file logging
Since
v0.9
Definition at line 694 of file logger.cpp.
References fileLogging.
log()
void Logger::log (Level level, const String & tag, const String & message) static
Core logging function with explicit level specification.
Core logging function with level filtering and formatted output.
Parameters
level Log level for this message
tag Component identifier for message categorization
message Log message content
Note
Subject to both build-time and runtime level filtering
Primary logging implementation that handles level filtering, build-time optimization, and formatted message output. Provides timestamp, visual indicators, and structured formatting for all log messages.
Message processing:
Build-time level filtering using LOGGER_LEVEL_* flags
Runtime level filtering using currentLevel threshold
Automatic logger initialization if not already initialized
Timestamp generation using millis() for relative timing
Visual emoji prefixes for quick level identification
Structured format: [timestamp] [LEVEL] [TAG] Message
Professional level indicators:
ERROR: [ERROR] (critical issues)
WARN: [WARN] (warning conditions)
INFO: [INFO] (general information)
DEBUG: [DEBUG] (debug information)
VERBOSE: [VERBOSE] (detailed trace)
Parameters
level Logging level for this message (Level enumeration)
tag Component or module identifier for message categorization
message Log message content to be displayed
Note
Only active when LOGGER_ENABLED build flag is true
Respects both build-time and runtime level filtering
Timestamp shows milliseconds since system boot
Message output goes to Serial interface
See also
logf() for printf-style formatted logging
Level enumeration for available logging levels
ensureInitialized() for automatic initialization
Since
v0.9
Definition at line 192 of file logger.cpp.
References currentLevel, DEBUG, DISPLAY_SPLASH_DURATION_MS, ensureInitialized(), ERROR, fileLogging, INFO, VERBOSE, WARN, and writeToFile().
Referenced by debug(), error(), info(), logf(), verbose(), and warn().
logf()
void Logger::logf (Level level, const String & tag, const char * format, ...) static
Printf-style formatted logging with explicit level.
Printf-style formatted logging with variadic arguments.
Parameters
level Log level for this message
tag Component identifier for message categorization
format Printf-style format string
... Variable arguments for format specifiers
Note
Uses 512-byte internal buffer for message formatting
Provides printf-style formatting capabilities for complex log messages requiring variable substitution, numeric formatting, or structured output. Uses internal buffer for format string processing before delegation to log().
Format processing:
Supports full printf format specifier syntax
Uses 512-byte internal buffer for formatted output
Automatic buffer management with safe overflow handling
Delegates to log() for level filtering and output formatting
Supported format specifiers include:
s (strings), d (integers), f (floats)
x (hexadecimal), c (characters)
Width and precision specifiers (e.g., %04d, %.2f)
Parameters
level Logging level for this message (Level enumeration)
tag Component or module identifier for message categorization
format Printf-style format string with placeholders
... Variable arguments corresponding to format placeholders
Note
Buffer size is 512 bytes; longer formatted strings will be truncated
All level filtering and build-time flags apply as with log()
Format string processing occurs even if message will be filtered
Consider performance impact for verbose logging with complex formatting
See also
log() for basic string logging without formatting
Level enumeration for available logging levels
Standard printf documentation for format specifier syntax
Since
v0.9
Definition at line 279 of file logger.cpp.
References DISPLAY_SPLASH_DURATION_MS, and log().
printMemoryInfo()
void Logger::printMemoryInfo () static
Output memory usage analysis including PSRAM.
Outputs detailed ESP32 memory usage analysis via logging.
Note
Requires DEBUG level logging for visibility
Advanced diagnostic function that collects and logs comprehensive memory statistics for both internal heap and external PSRAM when available. Essential for memory leak detection, heap fragmentation analysis, and optimal memory allocation strategy development.
Internal Heap Information:
Current free heap space
Total heap size configuration
Minimum free heap reached (watermark)
Maximum single allocation possible
PSRAM Information (when available):
Total PSRAM capacity
Available PSRAM space
PSRAM detection and availability status
Note
Requires DEBUG level logging to be enabled for output visibility
Uses formatted logging (infof) for structured data presentation
Output is tagged with "MEMORY" identifier for easy filtering
Subject to build-time DEBUG level filtering via LOGGER_LEVEL_DEBUG
Automatically detects PSRAM availability via compile-time flags
Issues warnings when PSRAM is expected but not found
Ideal for memory optimization and leak detection scenarios
See also
printSystemInfo() for general hardware diagnostic information
printWiFiStatus() for network connectivity analysis
infof() for underlying formatted logging mechanism
warn() for PSRAM unavailability reporting
Since
v0.9
Definition at line 862 of file logger.cpp.
References DISPLAY_SPLASH_DURATION_MS, info(), infof(), and warn().
printSystemInfo()
void Logger::printSystemInfo () static
Output comprehensive ESP32 system information.
Outputs comprehensive ESP32 system information via logging.
Note
Displays chip model, CPU freq, memory, SDK version
Diagnostic function that collects and logs essential ESP32 hardware and firmware information for system analysis and troubleshooting. Provides formatted output of chip specifications, performance metrics, and firmware details through the established logging infrastructure.
Information displayed includes:
Chip model and revision identification
CPU frequency configuration
Flash memory size and specifications
Available heap memory status
SDK version and build information
Note
Requires INFO level logging to be enabled for output visibility
Uses formatted logging (infof) for structured data presentation
Output is tagged with "SYSTEM" identifier for easy filtering
Subject to build-time INFO level filtering via LOGGER_LEVEL_INFO
Ideal for startup diagnostics and system health verification
See also
printWiFiStatus() for network-specific diagnostic information
printMemoryInfo() for detailed memory analysis
infof() for underlying formatted logging mechanism
Since
v0.9
Definition at line 758 of file logger.cpp.
References DISPLAY_SPLASH_DURATION_MS, info(), and infof().
printWiFiStatus()
void Logger::printWiFiStatus () static
Output detailed WiFi connection status.
Outputs comprehensive WiFi network status via logging.
Note
Shows AP/STA modes, connection status, signal strength
Diagnostic function that collects and logs current WiFi configuration, connection status, and network parameters for connectivity troubleshooting. Supports both Access Point (AP) and Station (STA) modes with detailed status reporting for each operational mode.
Access Point Mode Information:
AP SSID configuration
AP IP address assignment
Connected client count
Station Mode Information:
Connected network SSID
Assigned IP address
Signal strength (RSSI) measurement
Connection status verification
Note
Requires INFO level logging to be enabled for output visibility
Uses formatted logging (infof) for structured data presentation
Output is tagged with "WIFI" identifier for easy filtering
Subject to build-time INFO level filtering via LOGGER_LEVEL_INFO
Automatically detects and reports current WiFi mode configuration
Issues warnings for disconnected station mode scenarios
See also
printSystemInfo() for hardware-specific diagnostic information
printMemoryInfo() for memory usage analysis
infof() for underlying formatted logging mechanism
warn() for disconnection status reporting
Since
v0.9
Definition at line 803 of file logger.cpp.
References DISPLAY_SPLASH_DURATION_MS, info(), infof(), and warn().
setLevel()
void Logger::setLevel (Level level) static
Sets runtime log level threshold.
Sets the runtime logging level threshold.
Parameters
level Minimum level for log output
Note
Build-time filtering takes precedence over runtime level
Configures the minimum logging level that will be output to Serial. Messages at or below the specified level will be displayed, while higher level messages will be filtered out for cleaner output.
Logging level hierarchy (ascending verbosity):
ERROR (1): Critical errors only
WARN (2): Warnings and errors
INFO (3): Informational messages, warnings, and errors
DEBUG (4): Debug information plus all lower levels
VERBOSE (5): All logging output including trace information
Parameters
level Maximum logging level to display (Level enumeration)
Note
Runtime level filtering works in conjunction with build-time flags
Does not affect build-time compilation filtering via LOGGER_LEVEL_* flags
Default level is INFO providing balanced output
Can be changed at runtime to adjust verbosity dynamically
See also
getLevel() for retrieving current logging level
Level enumeration for available logging levels
log() for level-based message filtering implementation
Since
v0.9
Definition at line 127 of file logger.cpp.
References currentLevel, and DISPLAY_SPLASH_DURATION_MS.
verbose()
void Logger::verbose (const String & tag, const String & message) static
Log verbose-level message (maximum detail)
Logs verbose-level message with simplified interface.
Parameters
tag Component identifier
message Verbose debugging content
Convenience wrapper for the most detailed logging level suitable for comprehensive troubleshooting, step-by-step execution tracking, and in-depth system analysis. Typically filtered out in all but development builds.
Parameters
tag Component or module identifier for message categorization
message Verbose message content with comprehensive detail
Note
Equivalent to calling log(VERBOSE, tag, message)
Subject to build-time VERBOSE level filtering via LOGGER_LEVEL_VERBOSE
Highest verbosity level producing most detailed output
Intended for intensive debugging and system analysis scenarios
May significantly impact performance if enabled in production
See also
log() for general-purpose logging with explicit level specification
verbosef() for printf-style formatted verbose logging
Level::VERBOSE for verbose level threshold definition
Since
v0.9
Definition at line 413 of file logger.cpp.
References DISPLAY_SPLASH_DURATION_MS, log(), and VERBOSE.
Referenced by verbosef().
verbosef()
void Logger::verbosef (const String & tag, const char * format, ...) static
Printf-style verbose logging.
Printf-style formatted verbose logging convenience function.
Parameters
tag Component identifier
format Printf format string
... Variable arguments
Combines printf-style formatting with verbose-level logging for the most detailed message composition available. Designed for comprehensive system analysis and intensive debugging scenarios requiring maximum detail.
Parameters
tag Component or module identifier for message categorization
format Printf-style format string with embedded format specifiers
... Variable arguments matching format specifiers in format string
Note
Uses 512-byte internal buffer for formatted message assembly
Subject to build-time VERBOSE level filtering via LOGGER_LEVEL_VERBOSE
Calls verbose() internally after formatting variable arguments
Buffer overflow protection via vsnprintf size limiting
Highest verbosity level with potential performance impact
Intended for development environments only
See also
verbose() for simple string-based verbose logging
logf() for general-purpose formatted logging with explicit level
Level::VERBOSE for verbose level threshold definition
Since
v0.9
Definition at line 577 of file logger.cpp.
References DISPLAY_SPLASH_DURATION_MS, and verbose().
warn()
void Logger::warn (const String & tag, const String & message) static
Log warning-level message
Logs warning-level message with simplified interface.
Parameters
tag Component identifier
message Warning message content
Convenience wrapper for warning-level logging suitable for non-critical issues that deserve attention but do not prevent system operation. Ideal for recoverable errors, deprecated function usage, or configuration issues.
Parameters
tag Component or module identifier for message categorization
message Warning message content describing the condition
Note
Equivalent to calling log(WARN, tag, message)
Subject to build-time WARN level filtering via LOGGER_LEVEL_WARN
Second highest priority level for important but non-critical issues
See also
log() for general-purpose logging with explicit level specification
warnf() for printf-style formatted warning logging
Level::WARN for warning level threshold definition
Since
v0.9
Definition at line 337 of file logger.cpp.
References DISPLAY_SPLASH_DURATION_MS, log(), and WARN.
Referenced by printMemoryInfo(), printWiFiStatus(), and warnf().
warnf()
void Logger::warnf (const String & tag, const char * format, ...) static
Printf-style warning logging.
Printf-style formatted warning logging convenience function.
Parameters
tag Component identifier
format Printf format string
... Variable arguments
Combines printf-style formatting with warning-level logging for flexible non-critical issue message composition. Handles variable argument processing and buffer management for formatted warning message generation.
Parameters
tag Component or module identifier for message categorization
format Printf-style format string with embedded format specifiers
... Variable arguments matching format specifiers in format string
Note
Uses 512-byte internal buffer for formatted message assembly
Subject to build-time WARN level filtering via LOGGER_LEVEL_WARN
Calls warn() internally after formatting variable arguments
Buffer overflow protection via vsnprintf size limiting
Ideal for recoverable errors and configuration issue reporting
See also
warn() for simple string-based warning logging
logf() for general-purpose formatted logging with explicit level
Level::WARN for warning level threshold definition
Since
v0.9
Definition at line 474 of file logger.cpp.
References DISPLAY_SPLASH_DURATION_MS, and warn().
writeToFile()
void Logger::writeToFile (const String & message) static private
Writes message to log file if file logging is enabled.
Parameters
message Formatted log message to write to file
Internal function that handles writing formatted log messages to the current log file. Includes error handling and automatic file opening/closing for each write operation.
Parameters
message Formatted log message to write to file
Note
Internal function - not intended for direct use
Automatically handles file opening and closing
Includes basic error handling for write failures
Since
v0.9
Definition at line 713 of file logger.cpp.
References currentLogFile, DISPLAY_SPLASH_DURATION_MS, and fileLogging.
Referenced by disableFileLogging(), enableFileLogging(), and log().
Field Documentation
currentLogFile
String Logger::currentLogFile = "" static private
Current log file path.
Definition at line 65 of file logger.h.
Referenced by disableFileLogging(), enableFileLogging(), and writeToFile().
fileLogging
bool Logger::fileLogging = false static private
File logging enabled state.
Definition at line 64 of file logger.h.
Referenced by disableFileLogging(), enableFileLogging(), isFileLoggingEnabled(), log(), and writeToFile().
initialized
bool Logger::initialized = false static private
Lazy initialization state tracking.
Definition at line 63 of file logger.h.
Referenced by ensureInitialized(), and init().
The documentation for this class was generated from the following files:
include/logger.h
src/logger.cpp