Dual Display Billboard: TimeManager Class Reference
TimeManager Class Reference
Advanced time management system with NTP synchronization and timezone support.
#include <time_manager.h>
Public Member Functions
TimeManager ()
Constructs time manager with default configuration.
bool begin ()
Initializes time manager and establishes NTP synchronization.
bool isTimeValid ()
Validates current time synchronization status.
String getCurrentTime ()
Gets current time in HH:MM format.
String getCurrentDate ()
Gets current date in YYYY/MM/DD format.
String getFormattedDateTime (const String &format="%Y-%m-%d %H:%M:%S")
Gets formatted date/time with custom format string.
void setTimezone (const String &timezone)
Sets timezone using POSIX TZ format with persistent storage.
String getCurrentTimezone ()
Gets current configured timezone.
String getTimezoneOptions ()
Generates HTML option elements for timezone selection.
void setClockLabel (const String &label)
Sets custom clock label with persistent storage.
String getClockLabel ()
Gets current clock label.
bool getCurrentTimeStruct (struct tm *timeinfo)
Gets current time as struct tm for precise calculations.
void setNTPServer (const String &server1, const String &server2="", const String &server3="")
Configures custom NTP servers with persistent storage.
String getNTPServer1 ()
Gets primary NTP server configuration.
void resetToDefaultNTP ()
Resets NTP configuration to default servers.
void forceResync ()
Forces immediate time resynchronization with NTP servers.
Private Member Functions
void configureNTP ()
Configures NTP servers and timezone settings.
bool waitForTimeSync (int maxRetries=20)
Waits for NTP time synchronization with non-blocking approach.
bool saveTimezone (const String &timezone)
Saves timezone configuration to LittleFS persistence.
String loadTimezone ()
Loads timezone configuration from LittleFS persistence.
bool saveClockLabel (const String &label)
Saves clock label to LittleFS persistence.
String loadClockLabel ()
Loads clock label from LittleFS persistence.
bool saveNTPServer (const String &server)
Saves NTP server configuration to LittleFS persistence.
String loadNTPServer ()
Loads NTP server configuration from LittleFS persistence.
Private Attributes
String currentTimezone
Current timezone in POSIX TZ format.
bool timeInitialized
Flag indicating successful time synchronization.
String clockLabel
Custom label for clock display.
String customNTPServer1
Primary NTP server.
String customNTPServer2
Secondary NTP server
String customNTPServer3
Tertiary NTP server.
Static Private Attributes
static const char * TIMEZONE_FILE = "/timezone.txt"
LittleFS path for timezone storage.
static const char * CLOCK_LABEL_FILE = "/clock_label.txt"
LittleFS path for clock label storage.
static const char * NTP_SERVER_FILE = "/ntp_server.txt"
LittleFS path for NTP server storage.
Detailed Description
Advanced time management system with NTP synchronization and timezone support.
Manages time synchronization, timezone configuration, and time display formatting for the ESP32-based dual display billboard system. Provides persistent storage for user preferences and automatic time synchronization with configurable NTP servers.
Definition at line 36 of file time_manager.h.
Constructor & Destructor Documentation
TimeManager()
TimeManager::TimeManager ()
Constructs time manager with default configuration.
Constructor initializes time manager with default configuration.
Sets up default values for timezone, clock label, and NTP servers. Actual configuration loading from persistent storage occurs in begin().
Definition at line 45 of file time_manager.cpp.
References clockLabel, currentTimezone, customNTPServer1, customNTPServer2, customNTPServer3, DEFAULT_TIMEZONE, NTP_SERVER1, NTP_SERVER2, and NTP_SERVER3.
Member Function Documentation
begin()
bool TimeManager::begin ()
Initializes time manager and establishes NTP synchronization.
Returns
true if initialization and time sync successful, false otherwise
true if initialization and time sync successful, false otherwise
Initialization sequence:
Check for already initialized state
Load persistent configuration from LittleFS
Configure NTP servers and timezone
Wait for time synchronization
Validate and confirm successful initialization
Definition at line 66 of file time_manager.cpp.
References clockLabel, configureNTP(), currentTimezone, customNTPServer1, DISPLAY_SPLASH_DURATION_MS, getCurrentTime(), loadClockLabel(), loadNTPServer(), loadTimezone(), LOG_ERROR, LOG_INFO, LOG_INFOF, TAG, timeInitialized, and waitForTimeSync().
Referenced by loop().
configureNTP()
void TimeManager::configureNTP () private
Configures NTP servers and timezone settings.
Sets up SNTP (Simple Network Time Protocol) service with configured servers and applies the current timezone. Uses fallback to default servers if custom servers are not configured.
Configuration process:
Select custom or default NTP servers
Initialize ESP32 configTime with server list
Start SNTP service
Apply timezone settings with DST rules
Definition at line 126 of file time_manager.cpp.
References currentTimezone, customNTPServer1, customNTPServer2, customNTPServer3, DISPLAY_SPLASH_DURATION_MS, LOG_INFO, LOG_INFOF, NTP_SERVER1, NTP_SERVER2, NTP_SERVER3, and TAG.
Referenced by begin(), forceResync(), resetToDefaultNTP(), and setNTPServer().
forceResync()
void TimeManager::forceResync ()
Forces immediate time resynchronization with NTP servers.
Stops current SNTP service and reinitializes with configured servers. Useful for recovering from time sync failures or applying new NTP settings.
Definition at line 373 of file time_manager.cpp.
References configureNTP(), DISPLAY_SPLASH_DURATION_MS, getCurrentTime(), LOG_INFO, LOG_INFOF, LOG_WARN, TAG, and waitForTimeSync().
getClockLabel()
String TimeManager::getClockLabel ()
Gets current clock label.
Gets the current clock display label.
Returns
Current clock label string
The custom label string currently assigned to the clock
Definition at line 344 of file time_manager.cpp.
References clockLabel.
Referenced by DisplayClockManager::displayClockOnDisplay(), DisplayClockManager::getClockLabel(), and WiFiManager::setupNormalModeRoutes().
getCurrentDate()
String TimeManager::getCurrentDate ()
Gets current date in YYYY/MM/DD format.
Returns
Formatted date string or "----/--/--" if time invalid
Formatted date string or "----/--/--" if time invalid
Provides date information with timezone-aware conversion for consistent date display across the system.
Definition at line 228 of file time_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, and isTimeValid().
getCurrentTime()
String TimeManager::getCurrentTime ()
Gets current time in HH:MM format.
Returns
Formatted time string or "--:--" if time invalid
Formatted time string or "--:--" if time invalid
Returns human-readable time format for display purposes. Automatically handles timezone conversion and DST rules.
Definition at line 204 of file time_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS.
Referenced by begin(), forceResync(), setTimezone(), and WiFiManager::setupNormalModeRoutes().
getCurrentTimeStruct()
bool TimeManager::getCurrentTimeStruct (struct tm * timeinfo)
Gets current time as struct tm for precise calculations.
Parameters
timeinfo Pointer to struct tm to fill with current time
Returns
true if time is valid and structure filled, false otherwise
Provides centralized access to time structure for display calculations while maintaining proper timezone conversion and validation.
Definition at line 356 of file time_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, and isTimeValid().
getCurrentTimezone()
String TimeManager::getCurrentTimezone ()
Gets current configured timezone.
Returns
Current timezone string in POSIX TZ format
Definition at line 295 of file time_manager.cpp.
References currentTimezone.
getFormattedDateTime()
String TimeManager::getFormattedDateTime (const String & format = "%Y-%m-%d %H:%M:%S")
Gets formatted date/time with custom format string.
Parameters
format strftime-compatible format string (default: "%Y-%m-%d %H:%M:%S")
Returns
Formatted date/time string or "Invalid time" if sync failed
Parameters
format strftime-compatible format string (default: "%Y-%m-%d %H:%M:%S")
Returns
Formatted date/time string or "Invalid time" if sync failed
Provides flexible time formatting using standard strftime format specifiers. Automatically applies timezone conversion and validates time synchronization.
Definition at line 250 of file time_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, and isTimeValid().
getNTPServer1()
String TimeManager::getNTPServer1 ()
Gets primary NTP server configuration.
Gets the primary NTP server address.
Returns
Primary NTP server hostname or IP
The currently configured primary NTP server string
Definition at line 431 of file time_manager.cpp.
References customNTPServer1.
Referenced by WiFiManager::setupNormalModeRoutes().
getTimezoneOptions()
String TimeManager::getTimezoneOptions ()
Generates HTML option elements for timezone selection.
Returns
HTML options string with current timezone pre-selected
Creates HTML option elements from timezone definitions in timezone_config.h. Users can customize available timezones by modifying that configuration file.
Returns
HTML options string with current timezone pre-selected
Creates a complete set of HTML option elements for common timezones with proper POSIX TZ format strings and DST rules. The current timezone is automatically marked as selected.
Definition at line 308 of file time_manager.cpp.
References currentTimezone, DISPLAY_SPLASH_DURATION_MS, TIMEZONE_OPTIONS, and TIMEZONE_OPTIONS_COUNT.
Referenced by WiFiManager::setupNormalModeRoutes().
isTimeValid()
bool TimeManager::isTimeValid ()
Validates current time synchronization status.
Returns
true if time is synchronized and valid, false otherwise
true if time is synchronized and valid, false otherwise
Checks both initialization flag and time validity to ensure the system has properly synchronized time from NTP servers.
Definition at line 193 of file time_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, and timeInitialized.
Referenced by getCurrentDate(), getCurrentTimeStruct(), getFormattedDateTime(), and WiFiManager::setupNormalModeRoutes().
loadClockLabel()
String TimeManager::loadClockLabel () private
Loads clock label from LittleFS persistence.
Returns
Saved clock label string, or empty string if not found or error
Definition at line 515 of file time_manager.cpp.
References CLOCK_LABEL_FILE, DISPLAY_SPLASH_DURATION_MS, LOG_ERROR, and TAG.
Referenced by begin().
loadNTPServer()
String TimeManager::loadNTPServer () private
Loads NTP server configuration from LittleFS persistence.
Returns
Saved NTP server address string, or empty string if not found or error
Definition at line 553 of file time_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, LOG_ERROR, NTP_SERVER_FILE, server, and TAG.
Referenced by begin().
loadTimezone()
String TimeManager::loadTimezone () private
Loads timezone configuration from LittleFS persistence.
Returns
Saved timezone string, or empty string if not found or error
Definition at line 477 of file time_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, LOG_ERROR, TAG, and TIMEZONE_FILE.
Referenced by begin().
resetToDefaultNTP()
void TimeManager::resetToDefaultNTP ()
Resets NTP configuration to default servers.
Restores the default pool.ntp.org servers and applies the configuration immediately if time system is initialized. Automatically attempts time synchronization with restored servers.
Definition at line 441 of file time_manager.cpp.
References configureNTP(), customNTPServer1, customNTPServer2, customNTPServer3, DISPLAY_SPLASH_DURATION_MS, LOG_INFO, NTP_SERVER1, NTP_SERVER2, NTP_SERVER3, TAG, timeInitialized, and waitForTimeSync().
saveClockLabel()
bool TimeManager::saveClockLabel (const String & label) private
Saves clock label to LittleFS persistence.
Parameters
label Clock label string to save
Returns
true if saved successfully, false on file system error
Definition at line 499 of file time_manager.cpp.
References CLOCK_LABEL_FILE, DISPLAY_SPLASH_DURATION_MS, LOG_ERROR, and TAG.
Referenced by setClockLabel().
saveNTPServer()
bool TimeManager::saveNTPServer (const String & server) private
Saves NTP server configuration to LittleFS persistence.
Parameters
server NTP server address string to save
Returns
true if saved successfully, false on file system error
Definition at line 537 of file time_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, LOG_ERROR, NTP_SERVER_FILE, server, and TAG.
Referenced by setNTPServer().
saveTimezone()
bool TimeManager::saveTimezone (const String & timezone) private
Saves timezone configuration to LittleFS persistence.
Parameters
timezone POSIX timezone string to save
Returns
true if saved successfully, false on file system error
Definition at line 461 of file time_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, LOG_ERROR, TAG, and TIMEZONE_FILE.
Referenced by setTimezone().
setClockLabel()
void TimeManager::setClockLabel (const String & label)
Sets custom clock label with persistent storage.
Sets a custom display label for the clock.
Parameters
label Custom text label to display with clock
Stores the custom label in LittleFS persistence. The label is used for display purposes and persists across device reboots.
Parameters
label The custom label text to assign to the clock
Definition at line 327 of file time_manager.cpp.
References clockLabel, DISPLAY_SPLASH_DURATION_MS, LOG_INFOF, LOG_WARN, saveClockLabel(), and TAG.
Referenced by DisplayClockManager::setClockLabel(), and WiFiManager::setupNormalModeRoutes().
setNTPServer()
void TimeManager::setNTPServer (const String & server1, const String & server2 = "", const String & server3 = "")
Configures custom NTP servers with persistent storage.
Configures custom NTP servers for time synchronization.
Parameters
server1 Primary NTP server hostname or IP
server2 Optional secondary NTP server
server3 Optional tertiary NTP server
Sets up to three custom NTP servers and saves the primary server to LittleFS for persistence. Automatically applies new configuration if time system is already initialized.
Parameters
server1 Primary NTP server address (required)
server2 Secondary NTP server address (optional)
server3 Tertiary NTP server address (optional)
Definition at line 397 of file time_manager.cpp.
References configureNTP(), customNTPServer1, customNTPServer2, customNTPServer3, DISPLAY_SPLASH_DURATION_MS, LOG_INFO, LOG_INFOF, LOG_WARN, saveNTPServer(), TAG, timeInitialized, and waitForTimeSync().
Referenced by WiFiManager::setupNormalModeRoutes().
setTimezone()
void TimeManager::setTimezone (const String & timezone)
Sets timezone using POSIX TZ format with persistent storage.
Parameters
timezone POSIX timezone string (e.g., "CET-1CEST,M3.5.0,M10.5.0/3")
timezone POSIX timezone string (e.g., "CET-1CEST,M3.5.0,M10.5.0/3")
Updates the system timezone and saves the setting to LittleFS for persistence. If time is already initialized, immediately applies the new timezone setting. Timezone strings follow POSIX TZ format with daylight saving time rules.
Definition at line 272 of file time_manager.cpp.
References currentTimezone, DISPLAY_SPLASH_DURATION_MS, getCurrentTime(), LOG_INFOF, LOG_WARN, saveTimezone(), TAG, and timeInitialized.
Referenced by WiFiManager::setupNormalModeRoutes().
waitForTimeSync()
bool TimeManager::waitForTimeSync (int maxRetries = 20) private
Waits for NTP time synchronization with non-blocking approach.
Parameters
maxRetries Maximum number of sync attempts (default: 10)
Returns
true if time synchronization successful, false if timeout
Uses cooperative multitasking approach with yield() and microsecond delays instead of blocking delay() to maintain system responsiveness during sync.
Definition at line 158 of file time_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, LOG_ERRORF, LOG_INFO, LOG_INFOF, and TAG.
Referenced by begin(), forceResync(), resetToDefaultNTP(), and setNTPServer().
Field Documentation
CLOCK_LABEL_FILE
const char * TimeManager::CLOCK_LABEL_FILE = "/clock_label.txt" static private
LittleFS path for clock label storage.
Definition at line 50 of file time_manager.h.
Referenced by loadClockLabel(), and saveClockLabel().
clockLabel
String TimeManager::clockLabel private
Custom label for clock display.
Definition at line 41 of file time_manager.h.
Referenced by begin(), getClockLabel(), setClockLabel(), and TimeManager().
currentTimezone
String TimeManager::currentTimezone private
Current timezone in POSIX TZ format.
Definition at line 39 of file time_manager.h.
Referenced by begin(), configureNTP(), getCurrentTimezone(), getTimezoneOptions(), setTimezone(), and TimeManager().
customNTPServer1
String TimeManager::customNTPServer1 private
Primary NTP server.
Definition at line 44 of file time_manager.h.
Referenced by begin(), configureNTP(), getNTPServer1(), resetToDefaultNTP(), setNTPServer(), and TimeManager().
customNTPServer2
String TimeManager::customNTPServer2 private
Secondary NTP server
Definition at line 45 of file time_manager.h.
Referenced by configureNTP(), resetToDefaultNTP(), setNTPServer(), and TimeManager().
customNTPServer3
String TimeManager::customNTPServer3 private
Tertiary NTP server.
Definition at line 46 of file time_manager.h.
Referenced by configureNTP(), resetToDefaultNTP(), setNTPServer(), and TimeManager().
NTP_SERVER_FILE
const char * TimeManager::NTP_SERVER_FILE = "/ntp_server.txt" static private
LittleFS path for NTP server storage.
Definition at line 51 of file time_manager.h.
Referenced by loadNTPServer(), and saveNTPServer().
timeInitialized
bool TimeManager::timeInitialized private
Flag indicating successful time synchronization.
Definition at line 40 of file time_manager.h.
Referenced by begin(), isTimeValid(), resetToDefaultNTP(), setNTPServer(), and setTimezone().
TIMEZONE_FILE
const char * TimeManager::TIMEZONE_FILE = "/timezone.txt" static private
LittleFS path for timezone storage.
Definition at line 49 of file time_manager.h.
Referenced by loadTimezone(), and saveTimezone().
The documentation for this class was generated from the following files:
include/time_manager.h
src/time_manager.cpp