Dual Display Billboard: ImageManager Class Reference
ImageManager Class Reference
Comprehensive image management system.
#include <image_manager.h>
Public Member Functions
ImageManager (DisplayManager *dm)
Constructs ImageManager with display hardware integration.
~ImageManager ()
Destructor - cleans up singleton references.
void setDisplayType (DisplayType type)
Sets the display type for validation and rendering.
DisplayType getDisplayType () const
Gets current display type.
String getDisplayTypeString () const
Gets human-readable display type string.
String getRequiredResolution () const
Gets required resolution string for current display type.
bool handleImageUpload (const String &filename, uint8_t *data, size_t length)
Handles complete image upload with validation and storage.
bool validateImageFile (const String &filename, uint8_t *data, size_t length)
Comprehensive validation of uploaded image file data.
bool saveImage (const String &filename, uint8_t *data, size_t length)
Save validated image data to LittleFS with metadata tracking.
bool deleteImage (const String &filename)
Delete a JPEG image file from the LittleFS storage system and update the internal image list cache to reflect the removal.
bool imageExists (const String &filename)
Check if a specific JPEG image file exists in the LittleFS storage system.
bool displayImage (const String &filename, uint8_t displayNum=1)
Display JPEG image on specified hardware display.
bool displayImageOnBoth (const String &filename)
Display image simultaneously on both hardware displays.
void showNoImagesMessage ()
Display a "No Images" message on both billboard displays when no JPEG images are available in the LittleFS storage.
String getImageListJson ()
Generate a comprehensive JSON representation of all JPEG images stored in the LittleFS filesystem, including metadata and system configuration information for web interface consumption and slideshow management.
ImageInfo getImageDetails (const String &filename)
uint32_t getImageCount ()
Count the total number of valid JPEG image files currently stored in the LittleFS images directory.
uint32_t getTotalImagesSize ()
String getSystemInfo ()
Generate comprehensive JSON system information including display configuration, storage statistics, image counts, and capacity limits for web interface monitoring and system administration.
bool isStorageAvailable (uint32_t requiredBytes)
Check if sufficient LittleFS storage space is available for storing a new image file of specified size.
String getLastError ()
Retrieve the most recent error message from ImageManager operations for debugging and user feedback purposes.
bool begin ()
Initializes the image management system.
Private Member Functions
bool validateImageDimensions (uint16_t width, uint16_t height)
Validates image dimensions against display capabilities.
bool saveImageInfo (const ImageInfo &info)
Saves image metadata to persistent storage.
ImageInfo getImageInfo (const String &filename)
Retrieves image metadata from storage.
void updateImageList ()
Updates the master image list file.
Static Private Member Functions
static bool tft_output (int16_t x, int16_t y, uint16_t w, uint16_t h, uint16_t *bitmap)
TJpg_Decoder output callback.
Private Attributes
DisplayManager * displayManager
Reference to display hardware manager.
DisplayType currentDisplayType
Current display type (ST7735/ST7789)
uint16_t displayWidth
Display width in pixels.
uint16_t displayHeight
Display height in pixels.
uint8_t currentTargetDisplay
Active display for TJpg callback routing.
String lastErrorMessage
Detailed error message storage.
Static Private Attributes
static const char * IMAGES_DIR = "/images"
Directory path for image storage.
static const char * IMAGE_LIST_FILE = "/images/image_list.json"
Metadata file for image tracking.
static const uint32_t MAX_IMAGE_SIZE = 50000
Maximum file size (50KB)
static const uint32_t MAX_IMAGE_COUNT = 10
Maximum number of images (10)
static ImageManager * instance = nullptr
Singleton instance for static callbacks.
Detailed Description
Comprehensive image management system.
Handles all aspects of image storage and display for the billboard system. Integrates with DisplayManager for hardware control and provides web API endpoints for image upload and management.
Key features:
Automatic image count limiting (MAX_IMAGE_COUNT)
Size validation (MAX_IMAGE_SIZE)
Dimension validation per display type
LittleFS storage management
TJpg_Decoder integration for efficient rendering
Detailed error reporting
Definition at line 66 of file image_manager.h.
Constructor & Destructor Documentation
ImageManager()
ImageManager::ImageManager (DisplayManager * dm)
Constructs ImageManager with display hardware integration.
Parameters
dm Pointer to DisplayManager instance for hardware control
Definition at line 22 of file image_manager.cpp.
References currentDisplayType, currentTargetDisplay, displayHeight, displayWidth, g_imageManager, instance, ST7735, and ST7789.
~ImageManager()
ImageManager::~ImageManager ()
Destructor - cleans up singleton references.
Definition at line 40 of file image_manager.cpp.
References g_imageManager, and instance.
Member Function Documentation
begin()
bool ImageManager::begin ()
Initializes the image management system.
Returns
true if initialization successful, false otherwise
Sets up:
LittleFS file system
Image storage directory structure
TJpg_Decoder library configuration
Hardware-specific display settings
Definition at line 56 of file image_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, IMAGES_DIR, and tft_output().
deleteImage()
bool ImageManager::deleteImage (const String & filename)
Delete a JPEG image file from the LittleFS storage system and update the internal image list cache to reflect the removal.
This operation permanently removes the specified image file and cannot be undone.
The method performs validation to ensure the file exists before attempting deletion, then removes the file from the filesystem and updates the cached image list to maintain consistency with the storage state.
Parameters
filename The base filename of the image to delete (without path)
Returns
true if the image was successfully deleted, false if file not found or deletion failed
Note
File existence is validated before deletion attempt
Image list cache is automatically updated after successful deletion
Deletion is permanent and cannot be undone
Only affects files in the designated images directory
Logging statements removed to prevent compilation issues
See also
imageExists() for checking file existence before deletion
updateImageList() for cache maintenance after deletion
getImageListJson() for retrieving updated image inventory
LittleFS::remove() for filesystem deletion operation
Since
v0.9
Definition at line 556 of file image_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, IMAGES_DIR, and updateImageList().
Referenced by WiFiManager::setupImageRoutes().
displayImage()
bool ImageManager::displayImage (const String & filename, uint8_t displayNum = 1)
Display JPEG image on specified hardware display.
Parameters
filename Name of image file in /images/ directory
displayNum Target display number (1 or 2)
Returns
true if image displayed successfully, false otherwise
Complete image rendering process:
Loads image file from LittleFS storage
Allocates memory buffer for image data
Configures target display via DisplayManager
Clears display with black background
Uses TJpg_Decoder to render JPEG directly to display
Handles proper display selection/deselection
Manages memory cleanup
Note
Requires sufficient heap memory for image buffer
Uses callback mechanism for pixel-by-pixel rendering
See also
tft_output() for TJpg_Decoder callback implementation
Since
v0.9
Definition at line 333 of file image_manager.cpp.
References currentTargetDisplay, DisplayManager::deselectAll(), DISPLAY_SPLASH_DURATION_MS, displayManager, DisplayManager::getTFT(), IMAGES_DIR, DisplayManager::selectDisplayForImage(), and DisplayManager::setRotation().
Referenced by displayImageOnBoth(), and WiFiManager::setupImageRoutes().
displayImageOnBoth()
bool ImageManager::displayImageOnBoth (const String & filename)
Display image simultaneously on both hardware displays.
Parameters
filename Name of image file in /images/ directory
Returns
true if image displayed successfully on both displays, false otherwise
Renders the same image on both display outputs by calling displayImage() sequentially for each display. Currently implemented as sequential rendering for memory efficiency.
Note
Both displays must succeed for true return value
Uses sequential rendering to minimize memory usage
See also
displayImage() for single display rendering details
Since
v0.9
Definition at line 407 of file image_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, and displayImage().
Referenced by WiFiManager::setupImageRoutes(), and SlideshowManager::showNextImage().
getDisplayType()
DisplayType ImageManager::getDisplayType () const inline
Gets current display type.
Returns
Currently configured display type
Definition at line 147 of file image_manager.h.
References currentDisplayType.
getDisplayTypeString()
String ImageManager::getDisplayTypeString () const
Gets human-readable display type string.
Get string representation of current display type.
Returns
"ST7735" or "ST7789"
Display type as string ("ST7789" or "ST7735")
Provides human-readable display type identifier for debugging, logging, and web interface display purposes.
Since
v0.9
Definition at line 110 of file image_manager.cpp.
References currentDisplayType, and ST7789.
Referenced by getImageListJson(), and getSystemInfo().
getImageCount()
uint32_t ImageManager::getImageCount ()
Count the total number of valid JPEG image files currently stored in the LittleFS images directory.
This method provides a simple numeric count for system monitoring and slideshow management.
The method scans the images directory and counts files with .jpg or .jpeg extensions, filtering out directories and non-JPEG files to provide an accurate count of displayable images available for the slideshow system.
Returns
Total count of JPEG files in the images directory, 0 if directory inaccessible
Note
Only counts files with .jpg or .jpeg extensions
Returns 0 if images directory cannot be accessed
Does not validate JPEG format or file integrity
Excludes subdirectories from the count
Used for slideshow management and system status reporting
See also
getImageListJson() for detailed image information
getSystemInfo() for comprehensive system statistics
isStorageAvailable() for storage capacity checking
MAX_IMAGE_COUNT for maximum allowed image count
Since
v0.9
Definition at line 700 of file image_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, and IMAGES_DIR.
Referenced by getSystemInfo(), and handleImageUpload().
getImageDetails()
ImageInfo ImageManager::getImageDetails (const String & filename)
getImageInfo()
ImageInfo ImageManager::getImageInfo (const String & filename) private
Retrieves image metadata from storage.
Parameters
filename Image filename
Returns
ImageInfo structure with file details
getImageListJson()
String ImageManager::getImageListJson ()
Generate a comprehensive JSON representation of all JPEG images stored in the LittleFS filesystem, including metadata and system configuration information for web interface consumption and slideshow management.
This method scans the images directory and builds a structured JSON object containing individual image details (filename, size, validity) along with system-wide information like display configuration, image count, and storage requirements. The JSON is formatted for direct consumption by web interfaces and API endpoints.
Returns
String containing complete JSON object with image list and system metadata
Note
Scans images directory dynamically for real-time accuracy
Filters files by .jpg and .jpeg extensions for JPEG validation
Includes system configuration data for display requirements
Removes path prefixes from filenames for consistent naming
Returns error information if directory access fails
JSON format suitable for direct web API responses
See also
getImageCount() for simple image counting
getSystemInfo() for detailed system configuration
getDisplayTypeString() for current display configuration
getRequiredResolution() for display resolution requirements
Since
v0.9
Definition at line 631 of file image_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, getDisplayTypeString(), getRequiredResolution(), and IMAGES_DIR.
Referenced by WiFiManager::setupImageRoutes().
getLastError()
String ImageManager::getLastError ()
Retrieve the most recent error message from ImageManager operations for debugging and user feedback purposes.
Provides access to detailed error information when image operations fail.
This method returns the last recorded error message string that was set during failed image operations such as upload validation, file saving, or display rendering. The error message can be used for debugging, logging, or providing user feedback through web interfaces.
Returns
String containing the most recent error message, empty if no errors
Note
Error message is set by various ImageManager operations on failure
Returns empty string if no errors have occurred
Error message persists until next operation or system reset
Used for debugging and user feedback in web interfaces
Thread-safe for concurrent access to error state
See also
validateImageFile() for operations that set validation error messages
saveImage() for operations that set file storage error messages
displayImage() for operations that set display error messages
handleImageUpload() for upload-specific error handling
Since
v0.9
Definition at line 825 of file image_manager.cpp.
References lastErrorMessage.
Referenced by WiFiManager::setupImageRoutes().
getRequiredResolution()
String ImageManager::getRequiredResolution () const
Gets required resolution string for current display type.
Get required image resolution string for current display type.
Returns
Resolution description for validation feedback
Resolution string ("240x240" for ST7789, "160x80" for ST7735)
Used for web interface validation messages and user guidance. Provides exact pixel dimensions required for uploaded images to display correctly without distortion.
Since
v0.9
Definition at line 124 of file image_manager.cpp.
References currentDisplayType, and ST7789.
Referenced by getImageListJson(), and getSystemInfo().
getSystemInfo()
String ImageManager::getSystemInfo ()
Generate comprehensive JSON system information including display configuration, storage statistics, image counts, and capacity limits for web interface monitoring and system administration.
This method compiles real-time system status data into a structured JSON object containing display type, resolution requirements, current image inventory, storage utilization, and operational limits. The JSON format enables direct consumption by web interfaces and monitoring systems.
Returns
String containing complete JSON object with system configuration and statistics
Note
Provides real-time storage statistics from LittleFS
Includes display configuration and resolution requirements
Shows current vs maximum image count limits
Calculates free storage space dynamically
JSON format suitable for direct web API responses
Used by system monitoring and administrative interfaces
See also
getImageListJson() for detailed individual image information
getImageCount() for simple image counting
isStorageAvailable() for storage capacity validation
getDisplayTypeString() for current display configuration
getRequiredResolution() for display resolution requirements
Since
v0.9
Definition at line 786 of file image_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, getDisplayTypeString(), getImageCount(), getRequiredResolution(), MAX_IMAGE_COUNT, and MAX_IMAGE_SIZE.
Referenced by WiFiManager::setupImageRoutes().
getTotalImagesSize()
uint32_t ImageManager::getTotalImagesSize ()
handleImageUpload()
bool ImageManager::handleImageUpload (const String & filename, uint8_t * data, size_t length)
Handles complete image upload with validation and storage.
Primary image upload handler with comprehensive validation.
Parameters
filename Original filename including extension
data Raw JPEG file data
length Data size in bytes
Returns
true if image uploaded and validated successfully
Performs comprehensive validation:
Image count limit check (MAX_IMAGE_COUNT)
File size validation (MAX_IMAGE_SIZE)
JPEG format validation
Dimension validation for display type
Storage space verification
Parameters
filename Original filename with extension
data Raw JPEG file data
length File size in bytes
Returns
true if upload successful, false with detailed error in lastErrorMessage
Validation pipeline:
Image count limit enforcement (MAX_IMAGE_COUNT)
File format and structure validation
Dimension compatibility check
Storage space verification
Atomic file save operation
Definition at line 283 of file image_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, getImageCount(), isStorageAvailable(), lastErrorMessage, MAX_IMAGE_COUNT, saveImage(), and validateImageFile().
Referenced by WiFiManager::setupImageRoutes().
imageExists()
bool ImageManager::imageExists (const String & filename)
Check if a specific JPEG image file exists in the LittleFS storage system.
This method provides a quick validation mechanism to verify file presence before performing operations like display or deletion.
The method constructs the full file path by combining the images directory path with the provided filename and queries the LittleFS filesystem for file existence using the native filesystem API.
Parameters
filename The base filename to check for existence (without path)
Returns
true if the image file exists in storage, false otherwise
Note
Only checks for file existence, not file validity or format
Uses LittleFS native existence checking for efficiency
Filename should not include directory path components
Does not validate JPEG format or file integrity
See also
deleteImage() for removing existing files
saveImage() for creating new image files
validateImageFile() for comprehensive file validation
LittleFS::exists() for filesystem existence checking
Since
v0.9
Definition at line 599 of file image_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, and IMAGES_DIR.
isStorageAvailable()
bool ImageManager::isStorageAvailable (uint32_t requiredBytes)
Check if sufficient LittleFS storage space is available for storing a new image file of specified size.
Includes safety buffer to prevent filesystem corruption and ensure stable system operation.
This method calculates available storage space by determining the difference between total filesystem capacity and current usage, then compares against the required bytes plus a 10KB safety buffer to prevent filesystem issues and maintain system stability during image storage operations.
Parameters
requiredBytes The number of bytes needed for the new image file
Returns
true if sufficient space is available with safety buffer, false otherwise
Note
Includes 10KB safety buffer to prevent filesystem corruption
Checks actual filesystem usage vs capacity in real-time
Should be called before attempting image upload or storage operations
Safety buffer ensures stable system operation even after storage
Returns false if filesystem queries fail
See also
saveImage() for image storage operations requiring space validation
getSystemInfo() for detailed storage statistics
MAX_IMAGE_SIZE for maximum allowed image file size
LittleFS::totalBytes() for filesystem capacity information
LittleFS::usedBytes() for current storage usage
Since
v0.9
Definition at line 750 of file image_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS.
Referenced by handleImageUpload().
saveImage()
bool ImageManager::saveImage (const String & filename, uint8_t * data, size_t length)
Save validated image data to LittleFS with metadata tracking.
Parameters
filename Name for the saved image file
data Raw image data buffer
length Size of image data in bytes
Returns
true if image saved successfully with metadata, false otherwise
Performs complete image persistence process:
Creates file in /images/ directory
Writes raw data to LittleFS
Verifies write integrity
Extracts and stores image metadata (dimensions, size, timestamp)
Updates image list for slideshow management
Note
Automatically removes corrupted files on write failure
Creates ImageInfo metadata for slideshow integration
See also
saveImageInfo() for metadata persistence
updateImageList() for slideshow list maintenance
Since
v0.9
Definition at line 226 of file image_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, ImageInfo::filename, ImageInfo::fileSize, ImageInfo::height, IMAGES_DIR, ImageInfo::isValid, saveImageInfo(), updateImageList(), ImageInfo::uploadTime, and ImageInfo::width.
Referenced by handleImageUpload().
saveImageInfo()
bool ImageManager::saveImageInfo (const ImageInfo & info) private
Saves image metadata to persistent storage.
Save image metadata information to a persistent database or cache for enhanced image management and slideshow functionality.
Parameters
info Image information structure
Returns
true if metadata saved successfully
Currently implements a simplified approach but designed for future expansion.
This method provides a framework for storing detailed image metadata such as dimensions, file size, upload timestamp, and display preferences. The current implementation is simplified but the interface is designed to support future database integration for advanced image management features.
Parameters
info ImageInfo structure containing metadata to be saved
Returns
true if metadata was successfully saved, false on error
Note
Current implementation is simplified and always returns true
Designed for future expansion to support detailed metadata database
Could store information like upload time, display count, preferences
Interface prepared for caching and advanced slideshow features
Thread-safe for concurrent metadata operations
See also
updateImageList() for image list cache management
getImageListJson() for retrieving image metadata
ImageInfo structure for metadata field definitions
saveImage() for file storage operations
Since
v0.9
Definition at line 856 of file image_manager.cpp.
Referenced by saveImage().
setDisplayType()
void ImageManager::setDisplayType (DisplayType type)
Sets the display type for validation and rendering.
Configure display type and corresponding resolution parameters.
Parameters
type ST7735 or ST7789 display type
type Display hardware type (ST7735 or ST7789)
Updates internal display dimensions and hardware-specific settings:
ST7789: 240x240 square display
ST7735: 160x80 landscape display
Note
Must be called before image operations to ensure proper scaling
Since
v0.9
Definition at line 87 of file image_manager.cpp.
References currentDisplayType, DISPLAY_SPLASH_DURATION_MS, displayHeight, displayWidth, and ST7789.
showNoImagesMessage()
void ImageManager::showNoImagesMessage ()
Display a "No Images" message on both billboard displays when no JPEG images are available in the LittleFS storage.
Provides visual feedback to users when the image directory is empty or when all images have been removed from the slideshow system.
This method serves as a fallback display state when the slideshow has no content to show. The message is centered on both displays using white text on black background for maximum visibility and contrast. Each display is individually selected and configured to ensure proper rendering.
Note
Message is displayed on both displays simultaneously
Uses text size 2 for good readability at typical viewing distances
Background is cleared to black before displaying the message
Text positioning is automatically calculated for center alignment
Individual display selection ensures proper hardware configuration
See also
getImageCount() for checking available image count
getImageListJson() for retrieving complete image inventory
displayImage() for normal image display functionality
DisplayManager::selectDisplay() for display activation
Since
v0.9
Definition at line 439 of file image_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, displayHeight, displayManager, displayWidth, DisplayManager::getTFT(), and DisplayManager::selectDisplay().
Referenced by SlideshowManager::showNoImagesMessage().
tft_output()
bool ImageManager::tft_output (int16_t x, int16_t y, uint16_t w, uint16_t h, uint16_t * bitmap) static private
TJpg_Decoder output callback.
Static callback function for TJpg_Decoder library to output decoded JPEG pixel data directly to the currently targeted TFT display.
Parameters
x X coordinate for pixel block
y Y coordinate for pixel block
w Width of pixel block
h Height of pixel block
bitmap RGB565 pixel data
Returns
true if pixels written successfully
This function serves as the bridge between the JPEG decoder and the display hardware, enabling efficient streaming of decoded image data.
The TJpg_Decoder library calls this function repeatedly with chunks of decoded pixel data during JPEG decompression. The function uses the singleton instance to access the display manager and renders pixels to the currently selected target display using hardware-accelerated operations.
Parameters
x Left coordinate of the pixel block being rendered
y Top coordinate of the pixel block being rendered
w Width of the pixel block in pixels
h Height of the pixel block in pixels
bitmap Pointer to RGB565 pixel data array for the block
Returns
true if pixels were successfully written to display, false on error
Note
This is a static function called by TJpg_Decoder during decompression
Uses singleton instance to access display manager and target display
Pixel data is in RGB565 format ready for TFT display
Display rotation and orientation must be set before calling decoder
Function validates instance and display manager before pixel operations
See also
displayImage() for complete JPEG display process
TJpg_Decoder::setJpgScale() for image scaling configuration
DisplayManager::getTFT() for display hardware access
TFT_eSPI::pushImage() for pixel data rendering
Since
v0.9
Definition at line 512 of file image_manager.cpp.
References currentTargetDisplay, DISPLAY_SPLASH_DURATION_MS, displayManager, DisplayManager::getTFT(), and instance.
Referenced by begin().
updateImageList()
void ImageManager::updateImageList () private
Updates the master image list file.
Update the internal image list cache to reflect current filesystem state after image addition or removal operations.
Maintains cache consistency for improved performance and accurate system status.
This method provides a framework for maintaining cached image list data that can improve performance by avoiding repeated filesystem scans. The current implementation uses dynamic generation but the interface is designed to support future caching optimizations for better responsiveness.
Note
Current implementation generates image list dynamically
Designed for future expansion to support intelligent caching
Called automatically after image addition or deletion operations
Could cache metadata for faster web interface responses
Interface prepared for advanced slideshow and management features
Thread-safe for concurrent list update operations
See also
deleteImage() for operations that trigger image list updates
saveImage() for operations that require list cache refresh
getImageListJson() for accessing current image list data
getImageCount() for simple image counting without caching
Since
v0.9
Definition at line 886 of file image_manager.cpp.
Referenced by deleteImage(), and saveImage().
validateImageDimensions()
bool ImageManager::validateImageDimensions (uint16_t width, uint16_t height) private
Validates image dimensions against display capabilities.
Validate image dimensions against current display type requirements.
Parameters
width Image width in pixels
height Image height in pixels
Returns
true if dimensions are acceptable for current display type
Parameters
width Image width in pixels
height Image height in pixels
Returns
true if dimensions are valid for current display type, false otherwise
Validates image dimensions according to display hardware specifications:
ST7789: Requires exact 240x240 pixels (square format)
ST7735: Accepts 160x80 (landscape) or 80x160 (portrait) orientations
Note
Used during image upload validation process
Since
v0.9
Definition at line 145 of file image_manager.cpp.
References currentDisplayType, and ST7789.
Referenced by validateImageFile().
validateImageFile()
bool ImageManager::validateImageFile (const String & filename, uint8_t * data, size_t length)
Comprehensive validation of uploaded image file data.
Parameters
filename Name of the image file (used for extension validation)
data Raw image file data buffer
length Size of image data in bytes
Returns
true if image passes all validation checks, false otherwise
Performs multi-stage validation:
File extension check (.jpg/.jpeg only)
File size limits (100 bytes minimum, MAX_IMAGE_SIZE maximum)
JPEG format validation using TJpg_Decoder
Dimension validation against display requirements
Note
Critical for preventing corrupt uploads and memory issues
See also
validateImageDimensions() for dimension checking logic
Since
v0.9
Definition at line 171 of file image_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, MAX_IMAGE_SIZE, and validateImageDimensions().
Referenced by handleImageUpload().
Field Documentation
currentDisplayType
DisplayType ImageManager::currentDisplayType private
Current display type (ST7735/ST7789)
Definition at line 76 of file image_manager.h.
Referenced by getDisplayType(), getDisplayTypeString(), getRequiredResolution(), ImageManager(), setDisplayType(), and validateImageDimensions().
currentTargetDisplay
uint8_t ImageManager::currentTargetDisplay private
Active display for TJpg callback routing.
Definition at line 79 of file image_manager.h.
Referenced by displayImage(), ImageManager(), and tft_output().
displayHeight
uint16_t ImageManager::displayHeight private
Display height in pixels.
Definition at line 78 of file image_manager.h.
Referenced by ImageManager(), setDisplayType(), and showNoImagesMessage().
displayManager
DisplayManager* ImageManager::displayManager private
Reference to display hardware manager.
Definition at line 75 of file image_manager.h.
Referenced by displayImage(), showNoImagesMessage(), and tft_output().
displayWidth
uint16_t ImageManager::displayWidth private
Display width in pixels.
Definition at line 77 of file image_manager.h.
Referenced by ImageManager(), setDisplayType(), and showNoImagesMessage().
IMAGE_LIST_FILE
const char * ImageManager::IMAGE_LIST_FILE = "/images/image_list.json" static private
Metadata file for image tracking.
Definition at line 70 of file image_manager.h.
IMAGES_DIR
const char * ImageManager::IMAGES_DIR = "/images" static private
Directory path for image storage.
Definition at line 69 of file image_manager.h.
Referenced by begin(), deleteImage(), displayImage(), getImageCount(), getImageListJson(), imageExists(), and saveImage().
instance
ImageManager * ImageManager::instance = nullptr static private
Singleton instance for static callbacks.
Definition at line 83 of file image_manager.h.
Referenced by ImageManager(), tft_output(), and ~ImageManager().
lastErrorMessage
String ImageManager::lastErrorMessage private
Detailed error message storage.
Definition at line 80 of file image_manager.h.
Referenced by getLastError(), and handleImageUpload().
MAX_IMAGE_COUNT
const uint32_t ImageManager::MAX_IMAGE_COUNT = 10 static private
Maximum number of images (10)
Definition at line 72 of file image_manager.h.
Referenced by getSystemInfo(), and handleImageUpload().
MAX_IMAGE_SIZE
const uint32_t ImageManager::MAX_IMAGE_SIZE = 50000 static private
Maximum file size (50KB)
Definition at line 71 of file image_manager.h.
Referenced by getSystemInfo(), and validateImageFile().
The documentation for this class was generated from the following files:
include/image_manager.h
src/image_manager.cpp