Dual Display Billboard: MemoryManager Class Reference
MemoryManager Class Reference
Comprehensive memory monitoring and management system.
#include <memory_manager.h>
Data Structures
struct MemoryStats
Memory statistics structure.
Public Types
enum HealthStatus {
EXCELLENT = 0 , GOOD = 1 , WARNING = 2 , CRITICAL = 3 ,
EMERGENCY = 4
}
Memory health status levels.
enum MemoryType { HEAP_INTERNAL = 0 , PSRAM_EXTERNAL = 1 , STACK_MEMORY = 2 }
Memory subsystem types.
Static Public Member Functions
static bool initialize (unsigned long monitorIntervalMs=10000, bool enableAutoCleanup=true)
Initialize the memory monitoring system.
static void update ()
Update memory statistics and perform health checks.
static const MemoryStats & getStats ()
Get current memory statistics.
static HealthStatus getOverallHealth ()
Get overall memory health status.
static HealthStatus getHealthStatus (MemoryType type)
Get memory health status for specific subsystem.
static size_t getAvailableMemory (MemoryType type)
Get available memory for specific subsystem.
static float getUsagePercentage (MemoryType type)
Calculate memory usage percentage.
static size_t forceCleanup ()
Trigger immediate memory cleanup.
static void setAutoCleanup (bool enabled)
Enable or disable automatic memory cleanup.
static void setMonitoringEnabled (bool enabled)
Enable or disable memory monitoring (for critical operations)
static void setMonitorInterval (unsigned long intervalMs)
Set memory monitoring interval.
static bool canAllocate (size_t requestedBytes, MemoryType type=HEAP_INTERNAL)
Check if memory is available for allocation.
static void printMemoryReport (bool includeHistory=false)
Print comprehensive memory report to logger.
static void printMemoryStatus ()
Print compact memory status for regular monitoring.
static const char * getHealthStatusString (HealthStatus status)
Get human-readable health status string.
static const char * getMemoryTypeString (MemoryType type)
Get human-readable memory type string.
static void resetStatistics ()
Reset memory statistics counters.
static bool isLowMemory ()
Check if system is in low memory condition.
static bool isCriticalMemory ()
Check if system is in critical memory condition.
static String getMemoryStatsJson ()
Get memory statistics as JSON string for web interface.
Static Private Member Functions
static void updateHeapStats ()
Updates internal ESP32 heap memory statistics and health metrics.
static void updatePsramStats ()
Updates PSRAM memory statistics with platform-specific handling.
static void updateHealthStatus ()
Updates health status metrics for all memory subsystems.
static void updateFragmentation ()
Calculates heap memory fragmentation metrics.
static HealthStatus calculateHealthStatus (size_t free, size_t total)
Calculates health status based on memory usage percentage.
static void triggerCleanupIfNeeded ()
Triggers automatic memory cleanup when critical thresholds are reached.
static void recordMemoryEvent (MemoryType type, HealthStatus status)
Records memory events for statistical tracking and alerting.
Static Private Attributes
static const char * TAG = "MEMORY"
static MemoryStats currentStats = {}
static unsigned long lastMonitorTime = 0
static unsigned long monitorInterval = 10000
static bool autoCleanupEnabled = true
static bool monitoringEnabled = true
static size_t heapSampleCount = 0
static size_t heapSampleSum = 0
Detailed Description
Comprehensive memory monitoring and management system.
Provides real-time monitoring of ESP32-S3 memory subsystems including internal heap, PSRAM, and system health metrics. Includes automatic cleanup triggers and memory optimization strategies.
Definition at line 34 of file memory_manager.h.
Member Enumeration Documentation
HealthStatus
enum MemoryManager::HealthStatus
Memory health status levels.
Enumerator
EXCELLENT
>80% memory available, optimal performance
GOOD
>60% memory available, normal operation
WARNING
>40% memory available, monitor closely
CRITICAL
>20% memory available, cleanup needed
EMERGENCY
<20% memory available, immediate action required
Definition at line 39 of file memory_manager.h.
MemoryType
enum MemoryManager::MemoryType
Memory subsystem types.
Enumerator
HEAP_INTERNAL
Internal ESP32 heap memory.
PSRAM_EXTERNAL
External PSRAM memory.
STACK_MEMORY
Stack memory usage.
Definition at line 50 of file memory_manager.h.
Member Function Documentation
calculateHealthStatus()
MemoryManager::HealthStatus MemoryManager::calculateHealthStatus (size_t free, size_t total) static private
Calculates health status based on memory usage percentage.
Converts free memory metrics into standardized health status levels that provide intuitive assessment of memory conditions. Uses percentage-based thresholds to classify memory health across all subsystems consistently.
Health level thresholds:
EXCELLENT: ≥80% free memory (optimal performance)
GOOD: 60-79% free memory (normal operation)
WARNING: 40-59% free memory (monitor closely)
CRITICAL: 20-39% free memory (cleanup recommended)
EMERGENCY: <20% free memory (immediate action required)
Parameters
free Amount of free memory in bytes for the subsystem
total Total memory capacity in bytes for the subsystem
Returns
HealthStatus enumeration indicating current memory health level Returns EXCELLENT if total is zero (not applicable case)
Note
This is an internal utility method used by updateHealthStatus()
Percentage calculation handles zero total gracefully
Thresholds are designed for typical ESP32 memory usage patterns
Same thresholds apply to both heap and PSRAM subsystems
See also
updateHealthStatus() for comprehensive health status updates
getHealthStatusString() for human-readable health status names
HealthStatus enumeration for complete status level definitions
Since
v0.9
Definition at line 433 of file memory_manager.cpp.
References CRITICAL, DISPLAY_SPLASH_DURATION_MS, EMERGENCY, EXCELLENT, GOOD, and WARNING.
Referenced by updateHealthStatus().
canAllocate()
bool MemoryManager::canAllocate (size_t requestedBytes, MemoryType type = HEAP_INTERNAL) static
Check if memory is available for allocation.
Checks if memory allocation request is feasible with safety margins.
Parameters
requestedBytes Number of bytes requested for allocation
type Memory type to check (default: HEAP_INTERNAL)
Returns
true if allocation is likely to succeed, false otherwise
Analyzes whether requested memory allocation can be safely performed on specified subsystem without risking system stability. Includes safety margins to prevent memory exhaustion and maintain system responsiveness.
Allocation assessment includes:
Current available memory for specified subsystem
Safety margin calculation (10% of available or 4KB minimum)
Buffer to prevent system instability from memory exhaustion
Subsystem-specific availability checking
Safety margins ensure system remains stable even after large allocations by reserving memory for critical system operations and emergency cleanup.
Parameters
requestedBytes Size of memory allocation request in bytes
type Memory subsystem for allocation (HEAP_INTERNAL, PSRAM_EXTERNAL)
Returns
bool true if allocation can be safely performed, false otherwise
Note
Safety margin is 10% of available memory or 4KB, whichever is larger
PSRAM allocations return false when PSRAM is not available
Stack memory allocation checking is not yet supported
Recommendation: check before large allocations to prevent failures
See also
getAvailableMemory() for raw memory availability
getUsagePercentage() for current memory utilization
MemoryType enumeration for supported allocation targets
Since
v0.9
Definition at line 913 of file memory_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, and getAvailableMemory().
forceCleanup()
size_t MemoryManager::forceCleanup () static
Trigger immediate memory cleanup.
Performs comprehensive memory cleanup and optimization.
Forces immediate cleanup of unnecessary memory allocations, cache clearing, and garbage collection.
Returns
Number of bytes freed during cleanup
Executes manual memory cleanup operations to free unused memory and optimize system performance. Combines multiple cleanup strategies to maximize memory recovery and improve system responsiveness.
Cleanup operations performed:
Multiple rounds of yield() calls for garbage collection
Heap integrity checking and defragmentation (ESP-IDF systems)
Cache clearing and temporary buffer cleanup (future implementation)
Memory measurement before and after cleanup for effectiveness analysis
The cleanup process is designed to be safe and non-disruptive while maximizing memory recovery. Multiple yield cycles ensure thorough garbage collection without blocking system operation.
Returns
size_t Amount of memory freed during cleanup operation in bytes May return 0 if no additional memory could be recovered
Note
This operation may take several milliseconds to complete
Cleanup effectiveness varies based on current memory fragmentation
Statistics are automatically updated after cleanup completion
Safe to call manually even when auto-cleanup is enabled
See also
triggerCleanupIfNeeded() for automatic cleanup triggering
setAutoCleanup() for enabling automatic cleanup behavior
updateHeapStats() for post-cleanup statistics updates
Since
v0.9
Definition at line 754 of file memory_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, LOG_INFOF, TAG, updateHealthStatus(), and updateHeapStats().
Referenced by WiFiManager::checkHeapHealth(), and triggerCleanupIfNeeded().
getAvailableMemory()
size_t MemoryManager::getAvailableMemory (MemoryType type) static
Get available memory for specific subsystem.
Retrieves available memory for specific subsystem.
Parameters
type Memory subsystem type to query
Returns
Available memory in bytes, 0 if not available
Returns current free memory amount for specified memory subsystem in bytes. Essential for allocation planning and memory availability assessment before performing memory-intensive operations.
Memory subsystem availability:
HEAP_INTERNAL: Current free heap memory in bytes
PSRAM_EXTERNAL: Free PSRAM memory (0 if not available)
STACK_MEMORY: Stack monitoring not implemented (returns 0)
Parameters
type Memory subsystem type to query
Returns
size_t Available memory in bytes for specified subsystem Returns 0 for unavailable or unsupported subsystems
Note
PSRAM returns 0 when not available or on non-PSRAM platforms
Stack memory monitoring is not yet implemented
Values reflect most recent update() cycle measurements
Useful for pre-allocation memory availability checks
See also
canAllocate() for allocation feasibility checking with safety margins
getUsagePercentage() for memory utilization assessment
MemoryType enumeration for supported subsystem types
Since
v0.9
Definition at line 657 of file memory_manager.cpp.
References currentStats, DISPLAY_SPLASH_DURATION_MS, HEAP_INTERNAL, MemoryManager::MemoryStats::heapFree, PSRAM_EXTERNAL, MemoryManager::MemoryStats::psramAvailable, MemoryManager::MemoryStats::psramFree, and STACK_MEMORY.
Referenced by canAllocate(), WiFiManager::checkHeapHealth(), and WiFiManager::setupRoutes().
getHealthStatus()
MemoryManager::HealthStatus MemoryManager::getHealthStatus (MemoryType type) static
Get memory health status for specific subsystem.
Retrieves health status for specific memory subsystem.
Parameters
type Memory subsystem type to check
Returns
Health status for specified memory type
Returns health status for individual memory subsystems allowing targeted monitoring and diagnostic analysis. Enables subsystem-specific health assessment and troubleshooting of memory-related issues.
Supported subsystem types:
HEAP_INTERNAL: ESP32 internal heap memory status
PSRAM_EXTERNAL: External PSRAM memory status (ESP32-S3 only)
STACK_MEMORY: Stack memory usage (not yet implemented)
Parameters
type Memory subsystem type to query
Returns
HealthStatus Current health status for specified subsystem Returns EXCELLENT for unsupported or non-applicable subsystems
Note
Stack memory monitoring is not yet implemented (returns GOOD)
PSRAM health only meaningful on ESP32-S3 with PSRAM enabled
Heap health is always available on all ESP32 platforms
Unknown subsystem types default to EXCELLENT status
See also
getOverallHealth() for system-wide health assessment
MemoryType enumeration for supported subsystem types
HealthStatus enumeration for status level definitions
Since
v0.9
Definition at line 616 of file memory_manager.cpp.
References currentStats, DISPLAY_SPLASH_DURATION_MS, EXCELLENT, GOOD, HEAP_INTERNAL, MemoryManager::MemoryStats::heapHealth, PSRAM_EXTERNAL, MemoryManager::MemoryStats::psramHealth, and STACK_MEMORY.
Referenced by WiFiManager::setupRoutes().
getHealthStatusString()
const char * MemoryManager::getHealthStatusString (HealthStatus status) static
Get human-readable health status string.
Converts health status enumeration to human-readable string.
Parameters
status Health status to convert
Returns
Human-readable health status string
Provides string representation of health status levels for logging, display interfaces, and JSON serialization. Essential for user-friendly status reporting and system integration.
Health status mappings:
EXCELLENT: "EXCELLENT" (>80% free memory)
GOOD: "GOOD" (60-79% free memory)
WARNING: "WARNING" (40-59% free memory)
CRITICAL: "CRITICAL" (20-39% free memory)
EMERGENCY: "EMERGENCY" (<20% free memory)
Unknown: "UNKNOWN" (error fallback)
Parameters
status HealthStatus enumeration value to convert
Returns
const char* Human-readable string representation of health status Never returns NULL; unknown values return "UNKNOWN"
Note
Return value is const char* pointing to static string (safe for logging)
Unknown status values default to "UNKNOWN" for error handling
String values are uppercase for consistency with logging standards
Used internally by reporting functions and available for external use
See also
getMemoryTypeString() for memory type string conversion
printMemoryReport() for usage in comprehensive reporting
getMemoryStatsJson() for JSON serialization using these strings
Since
v0.9
Definition at line 1082 of file memory_manager.cpp.
References CRITICAL, DISPLAY_SPLASH_DURATION_MS, EMERGENCY, EXCELLENT, GOOD, and WARNING.
Referenced by WiFiManager::checkHeapHealth(), getMemoryStatsJson(), printMemoryReport(), printMemoryStatus(), recordMemoryEvent(), WiFiManager::setupRoutes(), and triggerCleanupIfNeeded().
getMemoryStatsJson()
String MemoryManager::getMemoryStatsJson () static
Get memory statistics as JSON string for web interface.
Exports memory statistics as JSON formatted string.
Returns
JSON formatted memory statistics
Generates comprehensive memory statistics in JSON format for web APIs, remote monitoring systems, and data export applications. Provides structured data access to all memory metrics and health indicators.
JSON structure includes:
Heap memory statistics (total, free, used, usage percentage, fragmentation)
Heap health status as readable string
PSRAM availability flag and statistics (when available)
PSRAM health status (when applicable)
Overall system health assessment
System uptime and event counters
The JSON output is suitable for REST APIs, monitoring dashboards, and integration with external monitoring systems requiring structured memory data.
Returns
String JSON-formatted string containing comprehensive memory statistics Always returns valid JSON; missing data is handled gracefully
Note
PSRAM fields only included when PSRAM is available
All numeric values included as JSON numbers (not strings)
Health status values included as JSON strings
Floating-point values rounded to 1 decimal place for readability
See also
getStats() for programmatic access to raw statistics
printMemoryReport() for human-readable formatted output
getHealthStatusString() for health status string conversion
Since
v0.9
Definition at line 1262 of file memory_manager.cpp.
References MemoryManager::MemoryStats::cleanupTriggers, MemoryManager::MemoryStats::criticalEvents, currentStats, DISPLAY_SPLASH_DURATION_MS, getHealthStatusString(), getUsagePercentage(), HEAP_INTERNAL, MemoryManager::MemoryStats::heapFragmentation, MemoryManager::MemoryStats::heapFree, MemoryManager::MemoryStats::heapHealth, MemoryManager::MemoryStats::heapTotal, MemoryManager::MemoryStats::heapUsed, MemoryManager::MemoryStats::lowMemoryEvents, MemoryManager::MemoryStats::overallHealth, PSRAM_EXTERNAL, MemoryManager::MemoryStats::psramAvailable, MemoryManager::MemoryStats::psramFree, MemoryManager::MemoryStats::psramHealth, MemoryManager::MemoryStats::psramTotal, MemoryManager::MemoryStats::psramUsed, and MemoryManager::MemoryStats::uptimeMs.
Referenced by WiFiManager::setupNormalModeRoutes(), and WiFiManager::setupRoutes().
getMemoryTypeString()
const char * MemoryManager::getMemoryTypeString (MemoryType type) static
Get human-readable memory type string.
Converts memory type enumeration to human-readable string.
Parameters
type Memory type to convert
Returns
Human-readable memory type string
Provides string representation of memory subsystem types for logging, error reporting, and system integration. Essential for clear identification of memory subsystems in diagnostic output and event logging.
Memory type mappings:
HEAP_INTERNAL: "HEAP" (ESP32 internal heap memory)
PSRAM_EXTERNAL: "PSRAM" (External PSRAM memory)
STACK_MEMORY: "STACK" (Stack memory usage)
Unknown: "UNKNOWN" (error fallback)
Parameters
type MemoryType enumeration value to convert
Returns
const char* Human-readable string representation of memory type Never returns NULL; unknown values return "UNKNOWN"
Note
Return value is const char* pointing to static string (safe for logging)
Unknown memory types default to "UNKNOWN" for error handling
String values are uppercase for consistency with logging standards
Used internally by event logging and available for external use
See also
getHealthStatusString() for health status string conversion
recordMemoryEvent() for usage in event logging
MemoryType enumeration for complete type definitions
Since
v0.9
Definition at line 1122 of file memory_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, HEAP_INTERNAL, PSRAM_EXTERNAL, and STACK_MEMORY.
Referenced by recordMemoryEvent().
getOverallHealth()
MemoryManager::HealthStatus MemoryManager::getOverallHealth () static
Get overall memory health status.
Retrieves overall system memory health status.
Returns
Current memory health status
Returns the current overall memory health indicator representing the worst-case health status across all monitored memory subsystems. Provides single-value assessment of system memory conditions for quick status checks.
Overall health determination:
Represents worst health status among all subsystems
Heap memory health always considered
PSRAM health included when PSRAM is available
Updated automatically during each monitoring cycle
Returns
HealthStatus Current overall memory health level (EXCELLENT, GOOD, WARNING, CRITICAL, or EMERGENCY)
Note
Overall health always reflects the most critical subsystem
Updated automatically by updateHealthStatus() during monitoring
Useful for quick system health checks and dashboard displays
Does not require knowledge of individual subsystem details
See also
getHealthStatus() for subsystem-specific health status
HealthStatus enumeration for status level definitions
updateHealthStatus() for health calculation methodology
Since
v0.9
Definition at line 584 of file memory_manager.cpp.
References currentStats, and MemoryManager::MemoryStats::overallHealth.
Referenced by WiFiManager::checkHeapHealth(), and WiFiManager::setupRoutes().
getStats()
const MemoryManager::MemoryStats & MemoryManager::getStats () static
Get current memory statistics.
Retrieves comprehensive memory statistics structure.
Returns
Reference to current memory statistics structure
Provides read-only access to the complete MemoryStats structure containing all current memory metrics, health indicators, and historical statistics. Essential for system monitoring, web interfaces, and diagnostic reporting.
Statistics include:
Current heap and PSRAM usage and availability
Health status for all memory subsystems
Historical peak usage and average metrics
Event counters for low memory and critical conditions
System uptime and monitoring timestamps
Returns
const MemoryStats& Reference to current memory statistics structure providing comprehensive system memory information
Note
Statistics are updated automatically by the update() method
Structure contains both instantaneous and historical metrics
All values are current as of the last update() call
Thread-safe read-only access to memory statistics
See also
MemoryStats structure for complete field documentation
update() for statistics update frequency
printMemoryReport() for formatted statistics display
Since
v0.9
Definition at line 553 of file memory_manager.cpp.
References currentStats.
Referenced by ConfigValidator::validateSystem().
getUsagePercentage()
float MemoryManager::getUsagePercentage (MemoryType type) static
Calculate memory usage percentage.
Calculates memory usage percentage for specific subsystem.
Parameters
type Memory subsystem type to calculate
Returns
Usage percentage (0-100), or -1 if not available
Computes current memory utilization as percentage of total capacity for specified memory subsystem. Provides normalized usage metrics for capacity planning and utilization monitoring across different subsystems.
Calculation methodology:
Percentage = (used memory / total memory) × 100
Returns -1.0 for unavailable or unsupported subsystems
Handles zero total memory gracefully
Accurate to floating-point precision
Parameters
type Memory subsystem type to analyze
Returns
float Memory usage percentage (0.0-100.0) Returns -1.0 if subsystem is unavailable or not supported
Note
Returns -1.0 for PSRAM when not available or on non-PSRAM platforms
Stack memory monitoring not implemented (returns -1.0)
Zero total memory results in -1.0 (error condition)
Useful for dashboard displays and utilization alerts
See also
getAvailableMemory() for absolute memory availability
getHealthStatus() for health assessment based on usage
MemoryType enumeration for supported subsystem types
Since
v0.9
Definition at line 699 of file memory_manager.cpp.
References currentStats, DISPLAY_SPLASH_DURATION_MS, HEAP_INTERNAL, MemoryManager::MemoryStats::heapTotal, MemoryManager::MemoryStats::heapUsed, PSRAM_EXTERNAL, MemoryManager::MemoryStats::psramAvailable, MemoryManager::MemoryStats::psramTotal, MemoryManager::MemoryStats::psramUsed, and STACK_MEMORY.
Referenced by getMemoryStatsJson(), printMemoryReport(), and printMemoryStatus().
initialize()
bool MemoryManager::initialize (unsigned long monitorIntervalMs = 10000, bool enableAutoCleanup = true) static
Initialize the memory monitoring system.
Initializes the memory monitoring system with configurable parameters.
Parameters
monitorIntervalMs Monitoring update interval in milliseconds (default: 10000ms)
enableAutoCleanup Enable automatic memory cleanup (default: true)
Returns
true if initialization successful, false otherwise
Sets up the comprehensive memory monitoring framework for ESP32-S3 dual display systems. Configures monitoring intervals, enables automatic cleanup triggers, and performs initial memory system scans to establish baseline metrics.
The initialization process includes:
Setting up monitoring intervals and cleanup behavior
Clearing all statistical counters and establishing baselines
Performing complete memory subsystem scan (heap + PSRAM)
Calculating initial health metrics and fragmentation levels
Logging system configuration and detected memory resources
Parameters
monitorIntervalMs Memory monitoring update interval in milliseconds (default 10000ms = 10 seconds). Lower values provide more frequent updates but consume more CPU resources
enableAutoCleanup Enable automatic memory cleanup when critical thresholds are reached. When enabled, system will automatically trigger cleanup when memory health reaches CRITICAL or EMERGENCY levels
Returns
true Always returns true indicating successful initialization (system is designed to be fault-tolerant)
Note
This method should be called once during system startup, preferably before initializing other memory-intensive subsystems
On ESP32-S3 systems, PSRAM detection and configuration is automatically performed during initialization
Initial memory statistics are immediately available after this call
See also
update() for periodic memory monitoring updates
setMonitorInterval() for runtime interval adjustments
setAutoCleanup() for runtime cleanup behavior changes
Since
v0.9
Definition at line 64 of file memory_manager.cpp.
References autoCleanupEnabled, currentStats, DISPLAY_SPLASH_DURATION_MS, MemoryManager::MemoryStats::heapFree, MemoryManager::MemoryStats::lastUpdateMs, LOG_INFOF, LOG_WARNF, monitorInterval, MemoryManager::MemoryStats::psramAvailable, MemoryManager::MemoryStats::psramFree, TAG, updateFragmentation(), updateHealthStatus(), updateHeapStats(), updatePsramStats(), and MemoryManager::MemoryStats::uptimeMs.
Referenced by setup().
isCriticalMemory()
bool MemoryManager::isCriticalMemory () static
Check if system is in critical memory condition.
Checks if system is in critical memory condition.
Returns
true if any memory subsystem is in CRITICAL or EMERGENCY condition
Provides boolean assessment of critical memory conditions requiring immediate attention or intervention. Returns true when memory health indicates system stability may be at risk.
Critical memory condition is defined as overall health status of CRITICAL or EMERGENCY, indicating severe memory pressure that requires immediate action to prevent system instability or failure.
Returns
bool true if overall health is CRITICAL or EMERGENCY false if overall health is EXCELLENT, GOOD, or WARNING
Note
Based on overall health status combining all memory subsystems
CRITICAL level indicates <40% memory available system-wide
EMERGENCY level indicates <20% memory available system-wide
Should trigger immediate cleanup or resource reduction actions
See also
isLowMemory() for broader low memory condition checking
getOverallHealth() for complete health status details
forceCleanup() for cleanup actions when critical condition detected
Since
v0.9
Definition at line 1225 of file memory_manager.cpp.
References CRITICAL, currentStats, and MemoryManager::MemoryStats::overallHealth.
Referenced by WiFiManager::setupRoutes().
isLowMemory()
bool MemoryManager::isLowMemory () static
Check if system is in low memory condition.
Checks if system is in low memory condition.
Returns
true if any memory subsystem is in WARNING or worse condition
Provides boolean assessment of low memory conditions for simplified status checking and conditional logic. Returns true when overall memory health indicates attention is needed.
Low memory condition is defined as overall health status of WARNING or worse, indicating that available memory has dropped below optimal levels and monitoring or intervention may be required.
Returns
bool true if overall health is WARNING, CRITICAL, or EMERGENCY false if overall health is EXCELLENT or GOOD
Note
Based on overall health status combining all memory subsystems
WARNING level indicates <60% memory available system-wide
Useful for conditional logic and automated response triggers
Updated automatically during each monitoring cycle
See also
isCriticalMemory() for more severe memory condition checking
getOverallHealth() for complete health status details
HealthStatus enumeration for threshold definitions
Since
v0.9
Definition at line 1196 of file memory_manager.cpp.
References currentStats, MemoryManager::MemoryStats::overallHealth, and WARNING.
Referenced by WiFiManager::setupRoutes().
printMemoryReport()
void MemoryManager::printMemoryReport (bool includeHistory = false) static
Print comprehensive memory report to logger.
Generates comprehensive memory report with detailed statistics.
Parameters
includeHistory Include historical statistics in report (default: false)
Produces detailed memory analysis report including current usage, health metrics, and optional historical statistics. Essential for system diagnostics, capacity planning, and performance analysis.
Report sections include:
System uptime and monitoring status
Complete heap memory analysis (total, free, used, fragmentation)
PSRAM memory statistics (when available)
Health status assessments for all subsystems
Optional historical metrics (peak usage, event counts, cleanup triggers)
The comprehensive report provides administrators with complete visibility into memory subsystem performance and helps identify potential issues before they impact system stability.
Parameters
includeHistory true to include historical statistics and event counts, false for current status only. Historical data includes peak usage tracking, average calculations, and event counters for trend analysis
Note
Report is output via LOG_INFOF for integration with system logging
Historical statistics provide valuable trend analysis data
PSRAM section only included when PSRAM is available
All memory values displayed in both bytes and kilobytes for readability
See also
printMemoryStatus() for brief status summary
getStats() for programmatic access to memory statistics
getMemoryStatsJson() for JSON-formatted statistics export
Since
v0.9
Definition at line 956 of file memory_manager.cpp.
References MemoryManager::MemoryStats::avgFreeHeap, MemoryManager::MemoryStats::cleanupTriggers, MemoryManager::MemoryStats::criticalEvents, currentStats, DISPLAY_SPLASH_DURATION_MS, getHealthStatusString(), getUsagePercentage(), HEAP_INTERNAL, MemoryManager::MemoryStats::heapFragmentation, MemoryManager::MemoryStats::heapFree, MemoryManager::MemoryStats::heapHealth, MemoryManager::MemoryStats::heapMaxAlloc, MemoryManager::MemoryStats::heapMinFree, MemoryManager::MemoryStats::heapTotal, MemoryManager::MemoryStats::heapUsed, LOG_INFOF, MemoryManager::MemoryStats::lowMemoryEvents, MemoryManager::MemoryStats::overallHealth, MemoryManager::MemoryStats::peakHeapUsage, PSRAM_EXTERNAL, MemoryManager::MemoryStats::psramAvailable, MemoryManager::MemoryStats::psramFree, MemoryManager::MemoryStats::psramHealth, MemoryManager::MemoryStats::psramTotal, MemoryManager::MemoryStats::psramUsed, TAG, and MemoryManager::MemoryStats::uptimeMs.
printMemoryStatus()
void MemoryManager::printMemoryStatus () static
Print compact memory status for regular monitoring.
Displays concise memory status for dashboard and monitoring.
Provides brief memory status summary optimized for dashboard displays and frequent monitoring updates. Shows essential memory metrics with visual health indicators for quick system assessment.
Status display includes:
Visual health indicator (icon) based on overall health
Heap memory availability in kilobytes and percentage
Overall health status as readable string
PSRAM availability when present
Visual indicators provide immediate health assessment:
EXCELLENT/GOOD health status
WARNING health status
CRITICAL/EMERGENCY health status
Note
Output formatted for dashboard displays and frequent updates
Health icons provide immediate visual health assessment
PSRAM status included only when PSRAM is available
Memory displayed in kilobytes for readability
See also
printMemoryReport() for comprehensive detailed analysis
getOverallHealth() for health status used in indicator selection
getUsagePercentage() for percentage calculations displayed
Since
v0.9
Definition at line 1033 of file memory_manager.cpp.
References CRITICAL, currentStats, DISPLAY_SPLASH_DURATION_MS, getHealthStatusString(), getUsagePercentage(), HEAP_INTERNAL, MemoryManager::MemoryStats::heapFree, LOG_INFOF, MemoryManager::MemoryStats::overallHealth, PSRAM_EXTERNAL, MemoryManager::MemoryStats::psramAvailable, MemoryManager::MemoryStats::psramFree, TAG, and WARNING.
recordMemoryEvent()
void MemoryManager::recordMemoryEvent (MemoryType type, HealthStatus status) static private
Records memory events for statistical tracking and alerting.
Maintains comprehensive event logging for memory health deterioration and critical memory conditions. Provides statistical tracking for system administration and automated alerting when memory issues occur.
Event classification:
Low memory events: WARNING level or worse health status
Critical events: CRITICAL level or worse health status
Event counters maintained in MemoryStats structure
Logging provides immediate notification of critical conditions
Parameters
type Memory subsystem type (HEAP_INTERNAL, PSRAM_EXTERNAL, STACK_MEMORY)
status Current health status that triggered the event
Note
This is an internal method called automatically during health monitoring
Events are counted cumulatively until statistics are reset
Critical events trigger immediate warning log messages
Event counters help identify patterns in memory usage
See also
update() for automatic event recording during monitoring
getStats() for retrieving event counters
resetStatistics() for clearing event counters
Since
v0.9
Definition at line 513 of file memory_manager.cpp.
References CRITICAL, MemoryManager::MemoryStats::criticalEvents, currentStats, DISPLAY_SPLASH_DURATION_MS, getHealthStatusString(), getMemoryTypeString(), LOG_WARNF, MemoryManager::MemoryStats::lowMemoryEvents, TAG, and WARNING.
Referenced by update().
resetStatistics()
void MemoryManager::resetStatistics () static
Reset memory statistics counters.
Resets all historical statistics and event counters.
Resets event counters and averages but preserves current readings. Useful for long-running systems to prevent counter overflow.
Clears accumulated statistical data and resets counters to baseline values for fresh monitoring cycle initiation. Useful for periodic statistics reset or after significant system changes.
Reset operations include:
Clearing all event counters (low memory, critical events, cleanup triggers)
Resetting peak usage tracking to current usage levels
Reinitializing running average calculations with current values
Maintaining current memory measurements (not historical data)
Current memory statistics remain unchanged; only historical tracking and accumulated counters are reset to provide clean baseline for future monitoring cycles.
Note
Current memory usage statistics are preserved
Peak usage tracking resets to current usage levels
Running averages restart from current free memory values
Event counters reset to zero for fresh tracking cycle
See also
getStats() for accessing statistics that will be reset
recordMemoryEvent() for events that increment counters
update() for monitoring that accumulates statistics
Since
v0.9
Definition at line 1159 of file memory_manager.cpp.
References MemoryManager::MemoryStats::avgFreeHeap, MemoryManager::MemoryStats::cleanupTriggers, MemoryManager::MemoryStats::criticalEvents, currentStats, MemoryManager::MemoryStats::heapFree, heapSampleCount, heapSampleSum, MemoryManager::MemoryStats::heapUsed, LOG_INFOF, MemoryManager::MemoryStats::lowMemoryEvents, MemoryManager::MemoryStats::peakHeapUsage, and TAG.
setAutoCleanup()
void MemoryManager::setAutoCleanup (bool enabled) static
Enable or disable automatic memory cleanup.
Configures automatic memory cleanup behavior.
Parameters
enabled true to enable automatic cleanup, false to disable
Enables or disables automatic memory cleanup operations that trigger when memory health reaches critical levels. Provides runtime control over automated memory management without requiring system restart.
When enabled, automatic cleanup triggers when:
Overall memory health reaches CRITICAL or EMERGENCY levels
Memory monitoring detects sustained high memory usage
System approaches memory exhaustion conditions
Parameters
enabled true to enable automatic cleanup, false to disable
Note
Changes take effect immediately during next monitoring cycle
Manual cleanup via forceCleanup() remains available regardless of setting
Cleanup triggers are logged for system monitoring and analysis
Recommended to keep enabled for autonomous operation
See also
triggerCleanupIfNeeded() for automatic cleanup implementation
forceCleanup() for manual cleanup operations
initialize() for initial auto-cleanup configuration
Since
v0.9
Definition at line 814 of file memory_manager.cpp.
References autoCleanupEnabled, LOG_INFOF, and TAG.
setMonitoringEnabled()
void MemoryManager::setMonitoringEnabled (bool enabled) static
Enable or disable memory monitoring (for critical operations)
Enables or disables memory monitoring operations.
Parameters
enabled true to enable monitoring, false to disable temporarily
Provides runtime control over memory monitoring system operation allowing temporary suspension of monitoring activities during critical operations or system maintenance. Useful for reducing overhead during intensive tasks.
When monitoring is disabled:
update() method returns immediately without processing
No statistics updates or health calculations performed
Automatic cleanup operations are suspended
Current statistics remain unchanged until monitoring resumes
Parameters
enabled true to enable monitoring, false to temporarily disable
Note
Monitoring state change takes effect immediately
Disabling monitoring does not affect manual operations like forceCleanup()
Current statistics are preserved during monitoring suspension
Recommended to re-enable monitoring promptly to maintain system visibility
See also
update() for main monitoring loop affected by this setting
initialize() for initial monitoring setup
setMonitorInterval() for monitoring frequency adjustment
Since
v0.9
Definition at line 845 of file memory_manager.cpp.
References LOG_INFOF, monitoringEnabled, and TAG.
Referenced by WiFiManager::setupImageRoutes().
setMonitorInterval()
void MemoryManager::setMonitorInterval (unsigned long intervalMs) static
Set memory monitoring interval.
Configures memory monitoring update interval.
Parameters
intervalMs New monitoring interval in milliseconds
Sets the frequency of memory monitoring updates providing control over monitoring overhead versus update granularity. Lower intervals provide more responsive monitoring while higher intervals reduce CPU usage.
Interval considerations:
Lower values (1-5 seconds): High responsiveness, higher CPU overhead
Medium values (10-30 seconds): Balanced monitoring for normal operation
Higher values (>60 seconds): Low overhead for background monitoring
Parameters
intervalMs Memory monitoring update interval in milliseconds Recommended range: 1000ms (1 second) to 300000ms (5 minutes)
Note
Changes take effect immediately during next update() call
Very low intervals (<1000ms) may impact system performance
Very high intervals (>300s) may delay critical event detection
Default interval is 10000ms (10 seconds) providing good balance
See also
initialize() for initial interval configuration
update() for monitoring loop affected by this interval
setMonitoringEnabled() for suspending monitoring entirely
Since
v0.9
Definition at line 876 of file memory_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, LOG_INFOF, monitorInterval, and TAG.
triggerCleanupIfNeeded()
void MemoryManager::triggerCleanupIfNeeded () static private
Triggers automatic memory cleanup when critical thresholds are reached.
Monitors overall memory health and automatically initiates cleanup operations when memory conditions reach critical or emergency levels. Provides automated memory management without manual intervention when auto-cleanup is enabled.
Cleanup trigger conditions:
Overall health status reaches CRITICAL or worse
Auto-cleanup feature is enabled via setAutoCleanup()
Cleanup operations are logged for system monitoring
When triggered, performs comprehensive memory cleanup including:
Forced garbage collection and heap optimization
Cache clearing and temporary buffer cleanup
Memory defragmentation where possible
Updated statistics collection post-cleanup
Note
This is an internal method called automatically by update()
Cleanup only occurs when autoCleanupEnabled flag is true
Each cleanup operation increments the cleanupTriggers counter
Cleanup effectiveness is logged for system monitoring
See also
forceCleanup() for the actual cleanup implementation
setAutoCleanup() for enabling/disabling automatic cleanup
update() for the monitoring loop that calls this method
Since
v0.9
Definition at line 474 of file memory_manager.cpp.
References MemoryManager::MemoryStats::cleanupTriggers, CRITICAL, currentStats, DISPLAY_SPLASH_DURATION_MS, forceCleanup(), getHealthStatusString(), LOG_INFOF, LOG_WARNF, MemoryManager::MemoryStats::overallHealth, and TAG.
Referenced by update().
update()
void MemoryManager::update () static
Update memory statistics and perform health checks.
Performs periodic memory monitoring and maintenance updates.
Should be called regularly from main loop. Updates all memory statistics, calculates health scores, and triggers cleanup if necessary.
Core monitoring method that should be called regularly from the main loop to maintain real-time memory statistics and trigger automatic maintenance. Updates all memory subsystem statistics, calculates health metrics, and triggers cleanup operations when configured thresholds are exceeded.
The update process includes:
Checking if monitoring interval has elapsed (rate limiting)
Updating heap memory statistics and fragmentation metrics
Scanning PSRAM status and usage (ESP32-S3 only)
Recalculating health status for all memory subsystems
Recording memory events when warning thresholds are exceeded
Triggering automatic cleanup if enabled and conditions warrant
Rate limiting ensures updates only occur at the configured interval to minimize CPU overhead while maintaining accurate monitoring.
Note
This method should be called frequently from main loop (every loop iteration) as it includes built-in rate limiting based on monitorInterval
If monitoring is temporarily disabled via setMonitoringEnabled(false), this method returns immediately without performing any updates
Memory health deterioration automatically triggers event logging
Automatic cleanup is only triggered if autoCleanupEnabled is true
See also
initialize() for initial setup and configuration
setMonitorInterval() for adjusting update frequency
setMonitoringEnabled() for temporarily disabling monitoring
forceCleanup() for manual memory cleanup operations
Since
v0.9
Definition at line 130 of file memory_manager.cpp.
References autoCleanupEnabled, currentStats, DISPLAY_SPLASH_DURATION_MS, HEAP_INTERNAL, MemoryManager::MemoryStats::heapHealth, lastMonitorTime, MemoryManager::MemoryStats::lastUpdateMs, monitoringEnabled, monitorInterval, PSRAM_EXTERNAL, MemoryManager::MemoryStats::psramAvailable, MemoryManager::MemoryStats::psramHealth, recordMemoryEvent(), triggerCleanupIfNeeded(), updateFragmentation(), updateHealthStatus(), updateHeapStats(), updatePsramStats(), MemoryManager::MemoryStats::uptimeMs, and WARNING.
updateFragmentation()
void MemoryManager::updateFragmentation () static private
Calculates heap memory fragmentation metrics.
Analyzes heap fragmentation by comparing the largest possible single allocation with total free memory. High fragmentation indicates memory is scattered in small blocks, potentially limiting large allocations.
Fragmentation calculation:
Compares heapMaxAlloc (largest single allocation) to heapFree (total free)
Calculates fragmentation as percentage of unusable free memory
Applies bounds checking to ensure valid percentage range (0-100%)
Handles edge cases like zero free memory gracefully
Low fragmentation (0-20%) indicates efficient memory usage while high fragmentation (>80%) suggests need for memory cleanup or defragmentation.
Note
This is an internal method called automatically by update()
Fragmentation percentage is clamped to valid range 0-100%
Zero free memory results in 100% fragmentation
Lower fragmentation percentages indicate better memory organization
See also
update() for the main monitoring loop that calls this method
forceCleanup() for operations that may improve fragmentation
updateHeapStats() for heap statistics that feed this calculation
Since
v0.9
Definition at line 388 of file memory_manager.cpp.
References currentStats, DISPLAY_SPLASH_DURATION_MS, MemoryManager::MemoryStats::heapFragmentation, MemoryManager::MemoryStats::heapFree, and MemoryManager::MemoryStats::heapMaxAlloc.
Referenced by initialize(), and update().
updateHealthStatus()
void MemoryManager::updateHealthStatus () static private
Updates health status metrics for all memory subsystems.
Calculates and updates health status indicators for heap memory, PSRAM, and overall system memory health. Health status provides quick assessment of memory conditions and triggers for automated maintenance actions.
Health calculation process:
Individual subsystem health assessment (heap, PSRAM)
Overall health determination using worst-case principle
PSRAM health only calculated when PSRAM is available
Non-applicable subsystems default to EXCELLENT status
Health levels range from EXCELLENT (>80% free) to EMERGENCY (<20% free) providing clear indicators for system administrators and automated systems.
Note
This is an internal method called automatically by update()
Overall health always reflects the worst individual subsystem health
PSRAM health is marked EXCELLENT when PSRAM is not available
Health calculations are based on free memory percentages
See also
calculateHealthStatus() for individual subsystem health calculation
update() for the main monitoring loop that calls this method
getOverallHealth() for retrieving current health status
Since
v0.9
Definition at line 344 of file memory_manager.cpp.
References calculateHealthStatus(), currentStats, EXCELLENT, MemoryManager::MemoryStats::heapFree, MemoryManager::MemoryStats::heapHealth, MemoryManager::MemoryStats::heapTotal, MemoryManager::MemoryStats::overallHealth, MemoryManager::MemoryStats::psramAvailable, MemoryManager::MemoryStats::psramFree, MemoryManager::MemoryStats::psramHealth, and MemoryManager::MemoryStats::psramTotal.
Referenced by forceCleanup(), initialize(), and update().
updateHeapStats()
void MemoryManager::updateHeapStats () static private
Updates internal ESP32 heap memory statistics and health metrics.
Comprehensive heap memory analysis including corruption detection, usage tracking, and performance metrics calculation. Implements robust error handling to detect and recover from heap corruption scenarios.
Statistical updates include:
Total and free heap memory measurements
Minimum free heap tracking for worst-case analysis
Maximum single allocation size for fragmentation analysis
Peak usage tracking for capacity planning
Running average calculation for trend analysis
Sample count management to prevent overflow
Safety features:
Heap corruption detection with sanity checks
Platform-specific fallback values for corrupted readings
Conservative estimates when corruption is detected
Automatic recovery with safe default values
Note
This is an internal method called automatically by update()
Corruption detection helps prevent system crashes from invalid readings
Peak usage tracking persists across monitoring cycles
Running averages use overflow-safe sample counting
ESP32-S3 and ESP32 classic have different heap size expectations
See also
update() for the main monitoring loop that calls this method
updatePsramStats() for PSRAM-specific memory updates
calculateHealthStatus() for health metric calculation
Since
v0.9
Definition at line 201 of file memory_manager.cpp.
References MemoryManager::MemoryStats::avgFreeHeap, currentStats, DISPLAY_SPLASH_DURATION_MS, MemoryManager::MemoryStats::heapFree, MemoryManager::MemoryStats::heapMaxAlloc, MemoryManager::MemoryStats::heapMinFree, heapSampleCount, heapSampleSum, MemoryManager::MemoryStats::heapTotal, MemoryManager::MemoryStats::heapUsed, and MemoryManager::MemoryStats::peakHeapUsage.
Referenced by forceCleanup(), initialize(), and update().
updatePsramStats()
void MemoryManager::updatePsramStats () static private
Updates PSRAM memory statistics with platform-specific handling.
Manages PSRAM memory monitoring specifically for ESP32-S3 platforms while ensuring proper handling on ESP32 classic systems that lack PSRAM support. Includes corruption detection and platform-appropriate reporting.
ESP32-S3 PSRAM handling:
Detects PSRAM presence using psramFound()
Measures total and free PSRAM capacity
Implements corruption detection with sanity checks
Calculates usage statistics for health assessment
ESP32 Classic handling:
Explicitly sets PSRAM as unavailable
Prevents false reporting of PSRAM capabilities
Ensures consistent behavior across platforms
Safety features:
PSRAM corruption detection with bounds checking
Graceful fallback when corruption is detected
Platform-conditional compilation for optimal performance
Consistent unavailable state for non-PSRAM platforms
Note
This is an internal method called automatically by update()
ESP32 classic systems will always report PSRAM as unavailable
ESP32-S3 systems require PSRAM to be properly configured in board settings
Corruption detection prevents invalid memory calculations
PSRAM availability flag is updated on every scan
See also
update() for the main monitoring loop that calls this method
updateHeapStats() for internal heap memory updates
calculateHealthStatus() for PSRAM health assessment
Since
v0.9
Definition at line 281 of file memory_manager.cpp.
References currentStats, DISPLAY_SPLASH_DURATION_MS, MemoryManager::MemoryStats::psramAvailable, MemoryManager::MemoryStats::psramFree, MemoryManager::MemoryStats::psramTotal, and MemoryManager::MemoryStats::psramUsed.
Referenced by initialize(), and update().
Field Documentation
autoCleanupEnabled
bool MemoryManager::autoCleanupEnabled = true static private
Definition at line 96 of file memory_manager.h.
Referenced by initialize(), setAutoCleanup(), and update().
currentStats
MemoryManager::MemoryStats MemoryManager::currentStats = {} static private
Definition at line 19 of file memory_manager.h.
Referenced by getAvailableMemory(), getHealthStatus(), getMemoryStatsJson(), getOverallHealth(), getStats(), getUsagePercentage(), initialize(), isCriticalMemory(), isLowMemory(), printMemoryReport(), printMemoryStatus(), recordMemoryEvent(), resetStatistics(), triggerCleanupIfNeeded(), update(), updateFragmentation(), updateHealthStatus(), updateHeapStats(), and updatePsramStats().
heapSampleCount
size_t MemoryManager::heapSampleCount = 0 static private
Definition at line 98 of file memory_manager.h.
Referenced by resetStatistics(), and updateHeapStats().
heapSampleSum
size_t MemoryManager::heapSampleSum = 0 static private
Definition at line 99 of file memory_manager.h.
Referenced by resetStatistics(), and updateHeapStats().
lastMonitorTime
unsigned long MemoryManager::lastMonitorTime = 0 static private
Definition at line 94 of file memory_manager.h.
Referenced by update().
monitoringEnabled
bool MemoryManager::monitoringEnabled = true static private
Definition at line 97 of file memory_manager.h.
Referenced by setMonitoringEnabled(), and update().
monitorInterval
unsigned long MemoryManager::monitorInterval = 10000 static private
Definition at line 95 of file memory_manager.h.
Referenced by initialize(), setMonitorInterval(), and update().
TAG
const char * MemoryManager::TAG = "MEMORY" static private
Definition at line 92 of file memory_manager.h.
Referenced by forceCleanup(), initialize(), printMemoryReport(), printMemoryStatus(), recordMemoryEvent(), resetStatistics(), setAutoCleanup(), setMonitoringEnabled(), setMonitorInterval(), and triggerCleanupIfNeeded().
The documentation for this class was generated from the following files:
include/memory_manager.h
src/memory_manager.cpp