Dual Display Billboard: DCCManager Class Reference
DCCManager Class Reference
Digital Command Control accessory decoder for model railway integration.
#include <dcc_manager.h>
Public Member Functions
DCCManager (SettingsManager *sm, SlideshowManager *slideshow)
Constructs DCC manager with required component dependencies.
bool begin ()
Initializes DCC decoder with current configuration.
void loop ()
Processes DCC signals in main application loop.
void restart ()
Restarts DCC decoder with current configuration.
void setEnabled (bool enable)
Enable or disable DCC interface processing.
bool isEnabled ()
Get current DCC interface enable state.
void setAddress (int addr)
Set DCC accessory decoder address.
int getAddress ()
Get current DCC decoder address.
void setPin (int pinNumber)
Set GPIO pin for DCC signal input.
int getPin ()
Get current DCC signal GPIO pin.
bool getCurrentState ()
Get current DCC command state.
void setState (bool state)
Manually set DCC state (for testing or manual control)
bool isInitialized ()
Check if DCC decoder is properly initialized.
Static Public Member Functions
static void notifyDccAccTurnoutOutput (uint16_t Addr, uint8_t Direction, uint8_t OutputPower)
Static callback function for NmraDcc library turnout notifications.
Private Member Functions
void handleDCCCommand (uint16_t addr, bool activate)
Processes received DCC command and updates system state.
void switchToGallery ()
Switches display system to gallery slideshow mode.
void switchToClock ()
Switches display system to clock display mode.
Private Attributes
NmraDcc dcc
NmraDcc library instance for signal decoding.
bool enabled
DCC interface enable state.
int address
DCC accessory decoder address (1-2048)
int pin
GPIO pin number for DCC signal input.
bool initialized
Initialization state of DCC decoder.
bool currentState
Current decoder state (true=activated/clock, false=deactivated/gallery)
unsigned long lastCommandTime
Timestamp of last received DCC command.
SettingsManager * settingsManager
Reference to configuration persistence manager.
SlideshowManager * slideshowManager
Reference to slideshow control manager.
Static Private Attributes
static const char * TAG = "DCC"
Logging tag for component identification.
static DCCManager * instance = nullptr
Static instance pointer for C callback integration.
Detailed Description
Digital Command Control accessory decoder for model railway integration.
Implements a DCC accessory decoder that responds to turnout commands to control display modes. Provides seamless integration between model railway DCC systems and the dual display billboard functionality.
The manager operates as a standard DCC accessory decoder, listening for commands on a configurable address. When commands are received, it automatically switches the display system between gallery slideshow mode and clock display mode.
Technical Implementation:
Uses NmraDcc library for robust DCC signal decoding
Configurable GPIO pin with internal pull-up for reliable signal reception
Static callback integration to meet NmraDcc C library requirements
Address validation ensures commands target the correct decoder
State management with command timestamp tracking
Definition at line 54 of file dcc_manager.h.
Constructor & Destructor Documentation
DCCManager()
DCCManager::DCCManager (SettingsManager * sm, SlideshowManager * slideshow)
Constructs DCC manager with required component dependencies.
Constructor - initializes DCC manager with component dependencies.
Parameters
sm Pointer to SettingsManager instance for configuration persistence
slideshow Pointer to SlideshowManager instance for display mode control
Initializes the DCC manager with default configuration values and establishes component dependencies for configuration and display control.
Parameters
sm Pointer to SettingsManager for configuration persistence
slideshow Pointer to SlideshowManager for display mode control
Definition at line 49 of file dcc_manager.cpp.
References address, currentState, DISPLAY_SPLASH_DURATION_MS, enabled, initialized, instance, lastCommandTime, pin, settingsManager, and slideshowManager.
Member Function Documentation
begin()
bool DCCManager::begin ()
Initializes DCC decoder with current configuration.
Initialize DCC decoder with current configuration settings.
Returns
true if initialization successful, false on failure
Loads configuration from settings manager, configures GPIO pin, initializes NmraDcc library, and starts DCC signal processing if enabled.
Returns
true if initialization successful, false on failure
Definition at line 72 of file dcc_manager.cpp.
References address, enabled, SettingsManager::getDCCAddress(), SettingsManager::getDCCPin(), SettingsManager::isDCCEnabled(), LOG_ERROR, LOG_INFO, LOG_INFOF, pin, restart(), settingsManager, and TAG.
getAddress()
int DCCManager::getAddress ()
Get current DCC decoder address.
Returns
Currently configured DCC address
Definition at line 213 of file dcc_manager.cpp.
References address.
getCurrentState()
bool DCCManager::getCurrentState ()
Get current DCC command state.
Returns
true if last command was activate (clock mode), false if deactivate (gallery mode)
Returns the state from the most recently processed DCC command. Useful for monitoring current display mode from external components.
Returns
true if last command was activate (clock mode), false if deactivate (gallery mode)
Definition at line 256 of file dcc_manager.cpp.
References currentState.
getPin()
int DCCManager::getPin ()
Get current DCC signal GPIO pin.
Returns
Currently configured GPIO pin number
Definition at line 244 of file dcc_manager.cpp.
References pin.
handleDCCCommand()
void DCCManager::handleDCCCommand (uint16_t addr, bool activate) private
Processes received DCC command and updates system state.
Process received DCC command and update system state.
Parameters
addr DCC address of received command
activate Command direction (true=thrown/clock, false=closed/gallery)
Validates the command address against the configured decoder address and triggers appropriate mode switching if the address matches.
Parameters
addr DCC address of received command
activate Command direction (true=thrown/clock, false=closed/gallery)
Definition at line 295 of file dcc_manager.cpp.
References address, DISPLAY_SPLASH_DURATION_MS, LOG_INFOF, setState(), and TAG.
Referenced by notifyDccAccTurnoutOutput().
isEnabled()
bool DCCManager::isEnabled ()
Get current DCC interface enable state.
Returns
true if DCC interface is enabled, false if disabled
Definition at line 182 of file dcc_manager.cpp.
References enabled.
Referenced by notifyDccAccTurnoutOutput().
isInitialized()
bool DCCManager::isInitialized ()
Check if DCC decoder is properly initialized.
Returns
true if decoder is initialized and ready to process commands
Indicates whether the DCC decoder hardware and software initialization completed successfully and is ready to process incoming DCC signals.
Returns
true if decoder is initialized and ready to process commands
Definition at line 282 of file dcc_manager.cpp.
References initialized.
Referenced by notifyDccAccTurnoutOutput().
loop()
void DCCManager::loop ()
Processes DCC signals in main application loop.
Process DCC signals in main application loop.
Must be called regularly from main loop to process incoming DCC signals. Only processes signals when DCC interface is enabled and initialized.
Must be called regularly from main loop to process incoming DCC signals. Only processes when DCC interface is enabled and properly initialized.
Definition at line 107 of file dcc_manager.cpp.
References dcc, enabled, and initialized.
notifyDccAccTurnoutOutput()
void DCCManager::notifyDccAccTurnoutOutput (uint16_t Addr, uint8_t Direction, uint8_t OutputPower) static
Static callback function for NmraDcc library turnout notifications.
Parameters
Addr DCC accessory address of received command
Direction Command direction (0=closed, 1=thrown)
OutputPower Command power state (not used in implementation)
Required static callback to interface with NmraDcc C library. Routes DCC commands to appropriate instance method for processing.
Definition at line 355 of file dcc_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, handleDCCCommand(), instance, isEnabled(), and isInitialized().
Referenced by notifyDccAccTurnoutOutput().
restart()
void DCCManager::restart ()
Restarts DCC decoder with current configuration.
Restart DCC decoder with current configuration.
Stops current DCC processing, reconfigures hardware with current settings, and restarts DCC signal processing. Used when configuration changes.
Stops current processing, reconfigures hardware, and restarts DCC signal processing. Used when configuration changes or during initial setup.
Definition at line 123 of file dcc_manager.cpp.
References address, dcc, DISPLAY_SPLASH_DURATION_MS, enabled, initialized, LOG_ERRORF, LOG_INFO, LOG_INFOF, pin, and TAG.
Referenced by begin(), setAddress(), setEnabled(), and setPin().
setAddress()
void DCCManager::setAddress (int addr)
Set DCC accessory decoder address.
Parameters
addr DCC address for this decoder (valid range: 1-2048)
Sets the DCC address this decoder will respond to. Only commands targeting this specific address will trigger mode switching. Configuration is automatically persisted and DCC decoder restarted.
Parameters
addr DCC address for this decoder (valid range: 1-2048)
Definition at line 190 of file dcc_manager.cpp.
References address, DISPLAY_SPLASH_DURATION_MS, enabled, LOG_INFOF, restart(), SettingsManager::setDCCAddress(), settingsManager, and TAG.
Referenced by WiFiManager::setupNormalModeRoutes().
setEnabled()
void DCCManager::setEnabled (bool enable)
Enable or disable DCC interface processing.
Parameters
enable true to enable DCC processing, false to disable
Controls whether the DCC interface actively processes incoming signals. Configuration is automatically persisted through settings manager. When disabled, stops DCC signal processing and releases hardware resources.
Parameters
enable true to enable DCC processing, false to disable
Definition at line 159 of file dcc_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, enabled, initialized, LOG_INFO, restart(), SettingsManager::setDCCEnabled(), settingsManager, and TAG.
Referenced by WiFiManager::setupNormalModeRoutes().
setPin()
void DCCManager::setPin (int pinNumber)
Set GPIO pin for DCC signal input.
Parameters
pinNumber GPIO pin number for DCC signal (valid range: 0-39)
Configures which GPIO pin receives DCC signals. Pin is automatically configured with internal pull-up resistor for reliable signal reception. Configuration is automatically persisted and DCC decoder restarted.
Parameters
pinNumber GPIO pin number for DCC signal (valid range: 0-39)
Definition at line 221 of file dcc_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, enabled, LOG_INFOF, pin, restart(), SettingsManager::setDCCPin(), settingsManager, and TAG.
Referenced by WiFiManager::setupNormalModeRoutes().
setState()
void DCCManager::setState (bool state)
Manually set DCC state (for testing or manual control)
Parameters
state true for activate/clock mode, false for deactivate/gallery mode
Allows manual state changes for testing purposes or external control. Updates timestamp and triggers appropriate display mode switching.
Parameters
state true for activate/clock mode, false for deactivate/gallery mode
Definition at line 264 of file dcc_manager.cpp.
References currentState, DISPLAY_SPLASH_DURATION_MS, lastCommandTime, LOG_INFOF, switchToClock(), switchToGallery(), and TAG.
Referenced by handleDCCCommand().
switchToClock()
void DCCManager::switchToClock () private
Switches display system to clock display mode.
Switch display system to clock display mode.
Activates clock display through slideshow manager coordination. Called when DCC command direction is 1 (thrown/diverging).
Definition at line 330 of file dcc_manager.cpp.
References LOG_INFO, LOG_WARN, SlideshowManager::showClock(), slideshowManager, and TAG.
Referenced by setState().
switchToGallery()
void DCCManager::switchToGallery () private
Switches display system to gallery slideshow mode.
Switch display system to gallery slideshow mode.
Activates the slideshow manager to begin image gallery display mode. Called when DCC command direction is 0 (closed/straight).
Activates slideshow manager to begin image gallery display. Called when DCC command direction is 0 (closed/straight).
Definition at line 312 of file dcc_manager.cpp.
References LOG_INFO, LOG_WARN, slideshowManager, SlideshowManager::startSlideshow(), and TAG.
Referenced by setState().
Field Documentation
address
int DCCManager::address private
DCC accessory decoder address (1-2048)
Definition at line 68 of file dcc_manager.h.
Referenced by begin(), DCCManager(), getAddress(), handleDCCCommand(), restart(), and setAddress().
currentState
bool DCCManager::currentState private
Current decoder state (true=activated/clock, false=deactivated/gallery)
Definition at line 73 of file dcc_manager.h.
Referenced by DCCManager(), getCurrentState(), and setState().
dcc
NmraDcc DCCManager::dcc private
NmraDcc library instance for signal decoding.
Definition at line 64 of file dcc_manager.h.
Referenced by loop(), and restart().
enabled
bool DCCManager::enabled private
DCC interface enable state.
Definition at line 67 of file dcc_manager.h.
Referenced by begin(), DCCManager(), isEnabled(), loop(), restart(), setAddress(), setEnabled(), and setPin().
initialized
bool DCCManager::initialized private
Initialization state of DCC decoder.
Definition at line 70 of file dcc_manager.h.
Referenced by DCCManager(), isInitialized(), loop(), restart(), and setEnabled().
instance
DCCManager * DCCManager::instance = nullptr static private
Static instance pointer for C callback integration.
Static instance for C callback integration.
Definition at line 82 of file dcc_manager.h.
Referenced by DCCManager(), and notifyDccAccTurnoutOutput().
lastCommandTime
unsigned long DCCManager::lastCommandTime private
Timestamp of last received DCC command.
Definition at line 74 of file dcc_manager.h.
Referenced by DCCManager(), and setState().
pin
int DCCManager::pin private
GPIO pin number for DCC signal input.
Definition at line 69 of file dcc_manager.h.
Referenced by begin(), DCCManager(), getPin(), restart(), and setPin().
settingsManager
SettingsManager* DCCManager::settingsManager private
Reference to configuration persistence manager.
Definition at line 79 of file dcc_manager.h.
Referenced by begin(), DCCManager(), setAddress(), setEnabled(), and setPin().
slideshowManager
SlideshowManager* DCCManager::slideshowManager private
Reference to slideshow control manager.
Definition at line 80 of file dcc_manager.h.
Referenced by DCCManager(), switchToClock(), and switchToGallery().
TAG
const char * DCCManager::TAG = "DCC" static private
Logging tag for component identification.
Logging component identifier.
Definition at line 59 of file dcc_manager.h.
Referenced by begin(), handleDCCCommand(), restart(), setAddress(), setEnabled(), setPin(), setState(), switchToClock(), and switchToGallery().
The documentation for this class was generated from the following files:
include/dcc_manager.h
src/dcc_manager.cpp