Dual Display Billboard: WiFiManager Class Reference
WiFiManager Class Reference
Advanced WiFi management system with dual-mode operation.
#include <wifi_manager.h>
Public Types
enum OperationMode { MODE_SETUP , MODE_NORMAL }
Public Member Functions
WiFiManager (AsyncWebServer *webServer, TimeManager *timeManager, SettingsManager *settingsManager, DisplayManager *displayManager, ImageManager *imageManager, class SlideshowManager *slideshowManager=nullptr, class DCCManager *dccManager=nullptr)
void startBackgroundScan (unsigned long ttlMs=30000)
void initializeAP (const String &ssid="Billboard-Portal", const String &password=PORTAL_PASSWORD)
void setupRoutes ()
Configures comprehensive web server routes for setup mode.
void startServer ()
Starts the HTTP web server for client request handling.
String scanNetworks ()
Performs WiFi network scan and returns formatted HTML results.
bool connectToWiFi (const String &ssid, const String &password)
Establishes WiFi connection with comprehensive error handling.
void handleConnect (AsyncWebServerRequest *request)
Handles HTTP POST requests for WiFi connection from web interface.
void checkHeapHealth ()
Monitors system memory health and triggers automatic cleanup.
void checkConnectionSuccessDisplay ()
Manages transition from connection success display to normal mode.
bool initializeFromCredentials ()
Initializes WiFi connection using stored credentials with fallback handling.
bool connectToSavedNetwork ()
void switchToNormalMode ()
Transitions system from setup mode to full operational normal mode.
void switchToSetupMode ()
Transitions system from normal mode to setup mode for configuration.
void checkConnectionStatus ()
Monitors WiFi connection status and handles automatic reconnection.
void checkGpio0FactoryReset ()
Monitors GPIO0 button for factory reset activation.
void setupNormalModeRoutes ()
Configures web server routes for normal operation mode.
void setupImageRoutes ()
Sets up image management HTTP routes for file upload and manipulation.
void setupOTARoutes ()
Configures Over-The-Air (OTA) firmware update web endpoints.
void checkScheduledRestart ()
Executes scheduled system restart when timeout reached.
void checkPortalModeSwitch ()
Checks for pending portal mode switch requests and executes transition.
bool validateFirmwareFilename (const String &filename)
Validates firmware filename for platform and display compatibility.
bool validateFirmwareBinary (uint8_t *data, size_t length)
Validates firmware binary content for ESP32 compatibility.
String getFirmwareVersion ()
Returns comprehensive firmware version information string.
OperationMode getCurrentMode () const
bool isConnectedToWiFi () const
Checks current WiFi connection status and operational mode.
String getWiFiIP () const
Retrieves current WiFi IP address for network identification.
bool isShowingConnectionSuccess () const
Returns current connection success display state.
Static Public Member Functions
static void scanTask (void *pvParameters)
Private Attributes
AsyncWebServer * server
TimeManager * timeManager
SettingsManager * settingsManager
DisplayManager * displayManager
ImageManager * imageManager
class SlideshowManager * slideshowManager
class DCCManager * dccManager
String apSSID
String apPassword
OperationMode currentMode
unsigned long lastConnectionAttempt
int connectionRetryCount
unsigned long lastGpio0Check
bool gpio0Pressed
unsigned long gpio0PressStart
bool restartPending
unsigned long restartScheduledTime
bool switchToPortalMode
bool connectionSuccessDisplayed
unsigned long connectionSuccessStartTime
String cachedNetworksJson
unsigned long lastScanMs
bool scanInProgress
unsigned long scanTTLMs
Static Private Attributes
static const int MAX_RETRY_ATTEMPTS = 3
static const unsigned long RETRY_DELAYS [] = { 5000, 15000, 30000 }
static const unsigned long FACTORY_RESET_DURATION = 6000
static const int GPIO0_PIN = 0
Detailed Description
Advanced WiFi management system with dual-mode operation.
Comprehensive WiFi connectivity manager that handles both station and access point modes simultaneously, providing robust network connectivity and web-based configuration interface for the ESP32 dual display billboard system.
The WiFiManager automatically manages connection states, provides fallback connectivity options, and integrates web server functionality for remote system management and content updates.
Key Responsibilities:
Network connection establishment and maintenance
Web server hosting for configuration interface
OTA firmware update processing
API endpoint management for system control
Integration with credential storage and time synchronization
Definition at line 79 of file wifi_manager.h.
Member Enumeration Documentation
OperationMode
enum WiFiManager::OperationMode
Enumerator
MODE_SETUP
MODE_NORMAL
Definition at line 81 of file wifi_manager.h.
Constructor & Destructor Documentation
WiFiManager()
WiFiManager::WiFiManager (AsyncWebServer * webServer, TimeManager * timeManager, SettingsManager * settingsManager, DisplayManager * displayManager, ImageManager * imageManager, class SlideshowManager * slideshowManager = nullptr, class DCCManager * dccManager = nullptr)
Definition at line 57 of file wifi_manager.cpp.
References apPassword, apSSID, cachedNetworksJson, connectionRetryCount, connectionSuccessDisplayed, connectionSuccessStartTime, currentMode, dccManager, DISPLAY_SPLASH_DURATION_MS, displayManager, gpio0Pressed, gpio0PressStart, imageManager, lastConnectionAttempt, lastGpio0Check, lastScanMs, MODE_SETUP, restartPending, restartScheduledTime, scanInProgress, scanTTLMs, server, settingsManager, slideshowManager, switchToPortalMode, and timeManager.
Member Function Documentation
checkConnectionStatus()
void WiFiManager::checkConnectionStatus ()
Monitors WiFi connection status and handles automatic reconnection.
Continuously monitors the WiFi connection health in normal mode and implements intelligent reconnection strategies to maintain network connectivity.
Monitoring Features: Periodic connection health checks (every 30 seconds) Signal strength (RSSI) monitoring and logging Connection failure detection and counting Automatic reconnection attempts with exponential backoff Mode switching on persistent connection failures
Reconnection Strategy: First attempt: Simple reconnect to current network Second attempt: Full credential reload and connect Final attempt: Switch to setup mode for reconfiguration
Note
Only operates in MODE_NORMAL to avoid interference with setup mode
Logs connection statistics for debugging and monitoring
Warning
Persistent failures will trigger setup mode switch
Failure Thresholds: 3+ consecutive failures trigger credential reload 5+ consecutive failures trigger setup mode switch
See also
switchToSetupMode() for fallback handling
connectToSavedNetwork() for reconnection logic
Definition at line 2066 of file wifi_manager.cpp.
References connectionRetryCount, connectToSavedNetwork(), currentMode, DISPLAY_SPLASH_DURATION_MS, lastConnectionAttempt, LOG_ERRORF, LOG_INFO, LOG_WARN, LOG_WARNF, MAX_RETRY_ATTEMPTS, MODE_NORMAL, RETRY_DELAYS, and TAG.
checkConnectionSuccessDisplay()
void WiFiManager::checkConnectionSuccessDisplay ()
Manages transition from connection success display to normal mode.
Monitors display state timing to transition from connection success message back to normal operation display after configured delay period. Provides visual feedback continuity and automatic return to standard operation.
Display Transition Process: Checks if connection success message is currently displayed Monitors elapsed time since success message started Automatically transitions to normal mode after 5-second delay Updates internal state flags and logs transition
Timing Considerations: Success message displayed for exactly 5 seconds Automatic transition prevents indefinite success display Non-blocking operation maintains system responsiveness State tracking ensures proper display mode management
Note
Called periodically in main loop for timing management
Transition is automatic and requires no external intervention
Warning
Display mode changes are immediate and visible to users
See also
isShowingConnectionSuccess() for current display state checking
WiFi connection handling for success trigger conditions
Definition at line 2330 of file wifi_manager.cpp.
References connectionSuccessDisplayed, connectionSuccessStartTime, currentMode, DISPLAY_MODE_SWITCH_DURATION_MS, DISPLAY_SPLASH_DURATION_MS, LOG_INFO, MODE_NORMAL, switchToNormalMode(), and TAG.
checkGpio0FactoryReset()
void WiFiManager::checkGpio0FactoryReset ()
Monitors GPIO0 button for factory reset activation.
Continuously monitors GPIO0 pin for factory reset trigger with debouncing and configurable hold time. Provides secure system restoration capability while preventing accidental resets through timing requirements.
Factory Reset Process: Continuous GPIO0 monitoring with 100ms polling interval Button state debouncing to prevent false triggers Configurable hold time requirement (default: 5 seconds) Visual countdown feedback during reset process Complete credential and settings erasure upon activation Automatic system restart in setup mode after reset
Safety Features: Requires sustained button press to prevent accidental activation Visual feedback shows remaining hold time Immediate release cancels reset process Confirmation logging before executing reset
Note
GPIO0 configured with internal pullup resistor (LOW when pressed)
Factory reset is irreversible - clears all stored credentials
Warning
All network settings and configurations will be lost
See also
CredentialManager::clearCredentials() for reset implementation
switchToSetupMode() for post-reset mode handling
Definition at line 2134 of file wifi_manager.cpp.
References CredentialManager::clearCredentials(), DISPLAY_SPLASH_DURATION_MS, FACTORY_RESET_DURATION, GPIO0_PIN, gpio0Pressed, gpio0PressStart, lastGpio0Check, LOG_DEBUG, LOG_DEBUGF, LOG_INFO, LOG_WARN, restartPending, restartScheduledTime, and TAG.
checkHeapHealth()
void WiFiManager::checkHeapHealth ()
Monitors system memory health and triggers automatic cleanup.
Continuously monitors ESP32 memory health using MemoryManager integration. Provides proactive memory management with automatic cleanup triggers and emergency response protocols to prevent system crashes and ensure stable operation.
Health Monitoring: Real-time memory health status assessment using MemoryManager Warning level detection with enhanced monitoring activation Critical level response with immediate cleanup operations Emergency level handling with system stability protocols Detailed logging for memory trend analysis and debugging
Automated Responses: WARNING: Enhanced monitoring with detailed status logging CRITICAL: Immediate forceCleanup() execution to reclaim memory EMERGENCY: System stability protocols and potential restart scheduling HEALTHY: Normal operation with periodic status verification
Note
Called periodically during WiFiManager operations to ensure system stability
Memory cleanup operations may cause brief service interruptions
Emergency conditions may trigger automatic system restart for recovery
Definition at line 845 of file wifi_manager.cpp.
References MemoryManager::CRITICAL, DISPLAY_SPLASH_DURATION_MS, MemoryManager::EMERGENCY, MemoryManager::forceCleanup(), MemoryManager::getAvailableMemory(), MemoryManager::getHealthStatusString(), MemoryManager::getOverallHealth(), MemoryManager::HEAP_INTERNAL, LOG_ERRORF, LOG_WARNF, TAG, and MemoryManager::WARNING.
checkPortalModeSwitch()
void WiFiManager::checkPortalModeSwitch ()
Checks for pending portal mode switch requests and executes transition.
Monitors internal flag for portal mode switch requests typically triggered by user interface actions or system conditions requiring configuration access. Provides controlled transition to setup mode when requested.
Portal Mode Switch Process: Checks switchToPortalMode flag state Logs transition request for debugging purposes
Resets flag to prevent repeated switching Executes immediate transition to setup mode
Common Triggers: User request via settings interface System configuration requirements Administrative access needs Troubleshooting mode activation
Transition Behavior: Flag-based triggering prevents race conditions Single execution per flag setting Immediate mode switching without delay Comprehensive logging for troubleshooting
Note
Called periodically in main loop to check switch requests
Flag automatically reset after processing to prevent repeat switches
Mode switching involves brief service interruption
See also
switchToSetupMode() for actual mode transition implementation
Settings interface for user-triggered portal mode requests
Definition at line 2296 of file wifi_manager.cpp.
References LOG_INFO, switchToPortalMode, switchToSetupMode(), and TAG.
checkScheduledRestart()
void WiFiManager::checkScheduledRestart ()
Executes scheduled system restart when timeout reached.
Monitors for pending restart conditions and executes system restart when scheduled time is reached. Provides controlled restart capability for mode transitions and system recovery operations.
Restart Conditions: Restart flag is pending (restartPending = true) Scheduled time has been reached or exceeded System is in a stable state for restart execution
Common Restart Triggers: Factory reset completion Mode transition requirements Critical system recovery needs Configuration changes requiring reboot
Note
Called periodically in main loop to check restart scheduling
Restart execution is immediate and non-recoverable
Warning
All unsaved data will be lost during restart
See also
checkGpio0FactoryReset() for factory reset restart triggers
switchToSetupMode() for mode transition restart needs
Definition at line 2257 of file wifi_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, LOG_INFO, restartPending, restartScheduledTime, and TAG.
connectToSavedNetwork()
bool WiFiManager::connectToSavedNetwork ()
Definition at line 938 of file wifi_manager.cpp.
References connectionRetryCount, connectionSuccessDisplayed, connectionSuccessStartTime, connectToWiFi(), DISPLAY_SPLASH_DURATION_MS, displayManager, CredentialManager::loadCredentials(), LOG_ERROR, LOG_INFOF, DisplayManager::showConnecting(), DisplayManager::showConnectionSuccess(), and TAG.
Referenced by checkConnectionStatus(), and initializeFromCredentials().
connectToWiFi()
bool WiFiManager::connectToWiFi (const String & ssid, const String & password)
Establishes WiFi connection with comprehensive error handling.
Initiates WiFi connection to specified network with robust timeout management, connection status monitoring, and visual feedback through display system. Provides detailed logging and error reporting for troubleshooting connectivity issues.
Connection Process: Network credential validation and sanitization WiFi hardware configuration for station mode Connection initiation with specified credentials Timeout-based connection monitoring (20-second limit) Connection status verification and IP address assignment Visual feedback through display manager status updates Comprehensive error logging for failed connection attempts
Parameters
ssid Target WiFi network name (SSID) for connection
password Network password for WPA/WPA2 authentication
Returns
bool True if connection established successfully with valid IP assignment, false if connection failed or timed out
Note
Connection timeout set to 20 seconds to prevent indefinite hanging
Displays connection status on attached displays for user feedback
Failed connections leave WiFi in disconnected state for retry attempts
Establishes WiFi connection with enhanced crash prevention
Connects ESP32 to specified WiFi network with comprehensive authentication failure handling and crash prevention mechanisms. Implements aggressive timeout management, early failure detection, and graceful disconnection to prevent ESP32 WiFi stack abort() crashes that occur during prolonged authentication failures.
Enhanced Safety Features (v0.9.1): Authentication Failure Prevention: Detects and aborts early on auth failures Aggressive Timeout Management: Reduced to 8 seconds to prevent prolonged failures Real-time Status Monitoring: 250ms status checks for rapid failure detection Early Abort Logic: Stops after 2 quick failures to prevent crash conditions Aggressive Cleanup: Forces disconnection after failures with delay Visual Feedback: Display integration for connection status and failures
Connection Process: Pre-connection cleanup with forced disconnect and delay Real-time WiFi status monitoring with 250ms granularity Authentication failure counting with early abort (max 2 attempts) Stuck connection detection (disconnected state > 3 seconds) Comprehensive cleanup on failure with forced disconnect and delay
Safety Mechanisms: Prevents ESP32 WiFi stack abort() crashes during authentication failures Detects WL_CONNECT_FAILED and WL_CONNECTION_LOST states early Monitors for prolonged WL_DISCONNECTED states indicating stuck connections Forces WiFi hardware reset on failure to ensure clean state
Parameters
ssid Target network SSID for connection attempt
password Network password for WPA/WPA2 authentication
Returns
bool True if connection established successfully with valid IP assignment, false if connection failed, timed out, or aborted due to safety mechanisms
Note
Connection timeout aggressively reduced to 8 seconds to prevent auth crashes
Displays connection status on attached displays for user feedback
Failed connections leave WiFi in clean disconnected state with hardware reset
Multiple quick failures trigger early abort to prevent system crash
See also
WiFi.onEvent() for complementary event-based crash prevention
displayManager->showConnecting() for visual feedback integration
Warning
Authentication failures can cause ESP32 WiFi stack crashes if not handled properly
Version
0.9.1 - Enhanced crash prevention and authentication failure handling
Definition at line 680 of file wifi_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, displayManager, LOG_DEBUGF, LOG_ERRORF, LOG_INFOF, DisplayManager::showQuickStatus(), and TAG.
Referenced by connectToSavedNetwork(), and handleConnect().
getCurrentMode()
OperationMode WiFiManager::getCurrentMode () const inline
Definition at line 157 of file wifi_manager.h.
References currentMode.
getFirmwareVersion()
String WiFiManager::getFirmwareVersion ()
Returns comprehensive firmware version information string.
Generates formatted version string containing firmware version, build type, and build date for system identification, debugging, and compatibility verification during OTA updates and system management.
Version String Format: Base version number (e.g., "0.9") Build type identifier (debug, production, latest) Build date stamp for temporal identification Combined format: "0.9-production-250815"
Version Components: FIRMWARE_VERSION: Core version number from build system BUILD_TYPE: Compilation configuration (debug/production/latest) BUILD_DATE: Automated build timestamp (YYMMDD format)
Common Use Cases: OTA update compatibility verification System status reporting and monitoring Debug log identification and correlation User interface version display Support and troubleshooting identification
Returns
String Formatted firmware version information
Format: "{version}-{type}-{date}" (e.g., "0.9-production-250815")
Note
Version information populated automatically during build process
Build date uses YYMMDD format for compact representation
Version string used in OTA update validation and system reporting
See also
include/version.h for version management and automated build numbering
platformio.ini for version configuration and build type definitions
Definition at line 2773 of file wifi_manager.cpp.
References BUILD_DATE, BUILD_TYPE, DISPLAY_SPLASH_DURATION_MS, and FIRMWARE_VERSION.
Referenced by setupOTARoutes().
getWiFiIP()
String WiFiManager::getWiFiIP () const
Retrieves current WiFi IP address for network identification.
Returns the assigned WiFi IP address when in normal mode with active connection. Provides network identification information for status displays and remote access.
Connection Requirements: Active WiFi connection (WL_CONNECTED) Normal operational mode (MODE_NORMAL) Valid IP assignment from DHCP or static configuration
Returns
String Current WiFi IP address in dot notation (e.g., "192.168.1.100"), or "N/A" if not connected or in setup mode
Note
Returns "N/A" for setup mode or disconnected state for clear status indication
IP address used for remote access and network troubleshooting
Commonly used in web APIs and status displays for network information
See also
isConnectedToWiFi() for connection status verification
checkConnectionStatus() for connectivity monitoring
Definition at line 2225 of file wifi_manager.cpp.
References currentMode, DISPLAY_SPLASH_DURATION_MS, and MODE_NORMAL.
handleConnect()
void WiFiManager::handleConnect (AsyncWebServerRequest * request)
Handles HTTP POST requests for WiFi connection from web interface.
Processes WiFi connection requests submitted through the web portal interface. Validates submitted credentials, attempts network connection, manages credential storage, and provides immediate HTTP response with connection status and next steps.
Request Processing: Validates presence of required SSID and password parameters Sanitizes and extracts network credentials from HTTP form data Initiates WiFi connection attempt using connectToWiFi() Manages credential persistence through CredentialManager integration Schedules system restart for mode transition upon successful connection Provides detailed HTTP response with connection status and user instructions
Response Handling: Success: Returns status page with restart notification and IP information Failure: Returns error page with retry instructions and troubleshooting tips Missing Parameters: Returns error response indicating required field validation Credential Storage: Logs success/failure of credential persistence operations
Parameters
request Pointer to AsyncWebServerRequest containing WiFi credentials and metadata
Note
Successful connections trigger 3-second delayed restart to transition to normal mode
Failed connections leave system in setup mode for additional retry attempts
All credential handling logged for security auditing and debugging purposes
Definition at line 749 of file wifi_manager.cpp.
References connectionSuccessDisplayed, connectionSuccessStartTime, connectToWiFi(), DISPLAY_SPLASH_DURATION_MS, displayManager, LOG_ERROR, LOG_INFO, LOG_INFOF, LOG_WARN, restartPending, restartScheduledTime, CredentialManager::saveCredentials(), DisplayManager::showConnecting(), DisplayManager::showConnectionSuccess(), DisplayManager::showQuickStatus(), and TAG.
Referenced by setupRoutes().
initializeAP()
void WiFiManager::initializeAP (const String & ssid = "Billboard-Portal", const String & password = PORTAL_PASSWORD)
Definition at line 177 of file wifi_manager.cpp.
References apPassword, apSSID, currentMode, DISPLAY_SPLASH_DURATION_MS, displayManager, LOG_DEBUG, LOG_DEBUGF, LOG_ERROR, LOG_INFO, LOG_INFOF, MODE_SETUP, PORTAL_SSID, DisplayManager::showAPStarting(), DisplayManager::showPortalSequence(), DisplayManager::showQuickStatus(), and TAG.
Referenced by switchToSetupMode().
initializeFromCredentials()
bool WiFiManager::initializeFromCredentials ()
Initializes WiFi connection using stored credentials with fallback handling.
Attempts to establish WiFi connection using previously saved network credentials. Provides automatic fallback to setup mode if credentials are missing, invalid, or connection attempts fail. Integrates with CredentialManager for secure storage access.
Initialization Process: Checks for existence of saved WiFi credentials in persistent storage Validates credential integrity and format before connection attempt Attempts network connection using stored SSID and password Transitions to normal mode upon successful connection establishment Falls back to setup mode if any step fails for user intervention
Fallback Scenarios: No saved credentials Setup mode for initial configuration Invalid credentials Setup mode for credential correction Connection failure Setup mode for network troubleshooting Network unavailable Setup mode with retry capability
Returns
bool True if connection established successfully using saved credentials, false if fallback to setup mode required
Note
Automatic mode switching ensures system remains accessible for configuration
Credential validation prevents connection attempts with corrupted data
Definition at line 908 of file wifi_manager.cpp.
References connectToSavedNetwork(), DISPLAY_SPLASH_DURATION_MS, CredentialManager::hasCredentials(), CredentialManager::loadCredentials(), LOG_ERROR, LOG_INFO, LOG_INFOF, LOG_WARN, switchToSetupMode(), and TAG.
isConnectedToWiFi()
bool WiFiManager::isConnectedToWiFi () const
Checks current WiFi connection status and operational mode.
Verifies both WiFi hardware connection state and system operational mode. Ensures accurate connection reporting by validating both network connectivity and proper normal mode operation for reliable status indication.
Validation Criteria: WiFi hardware connection state (WL_CONNECTED) System operational mode (MODE_NORMAL) Network interface availability and functionality
Returns
bool True if connected to WiFi network AND in normal operational mode, false if disconnected or in setup mode
Note
Connection status requires both WL_CONNECTED state and MODE_NORMAL operation
Setup mode returns false even if technically connected to validate operational state
Used by web APIs and system monitoring for accurate status reporting
See also
getWiFiIP() for retrieving connection details when connected
checkConnectionStatus() for connection monitoring implementation
Definition at line 2200 of file wifi_manager.cpp.
References currentMode, DISPLAY_SPLASH_DURATION_MS, and MODE_NORMAL.
isShowingConnectionSuccess()
bool WiFiManager::isShowingConnectionSuccess () const
Returns current connection success display state.
Provides read-only access to the connection success display flag, indicating whether the system is currently showing a WiFi connection success message on the displays.
State Information: Returns true when success message is actively displayed Returns false during normal operation or other display modes State automatically managed by success display timing logic Used for display coordination and status checking
Common Use Cases: Display mode coordination and conflict prevention Status checking for external monitoring systems Debugging display state management issues Integration with other display management components
Returns
bool Current connection success display state
Return values
true Success message is currently displayed
false Normal operation or other display mode active
Note
This is a const method and does not modify system state
State is automatically managed by display timing logic
See also
checkConnectionSuccessDisplay() for state transition management
DisplayManager for actual display rendering coordination
Definition at line 2380 of file wifi_manager.cpp.
References connectionSuccessDisplayed.
scanNetworks()
String WiFiManager::scanNetworks ()
Performs WiFi network scan and returns formatted HTML results.
Executes comprehensive WiFi network discovery scan and formats results as HTML for web interface display. Provides detailed network information including signal strength, security type, and channel information for user network selection.
Scan Features: Clears previous scan results to ensure fresh data Comprehensive network discovery with signal strength analysis Security type detection (Open, WEP, WPA/WPA2, WPA3) Signal strength visualization with colored indicators Channel information for interference analysis HTML formatted output for direct web interface integration Error handling for scan failures and timeout conditions
Returns
String HTML formatted list of discovered networks with selection interface
Note
Returns "No networks found" message if scan yields no results
Scan may take 5-10 seconds depending on channel coverage and network density
Definition at line 505 of file wifi_manager.cpp.
References currentMode, DISPLAY_SPLASH_DURATION_MS, LOG_DEBUG, LOG_DEBUGF, LOG_ERROR, LOG_INFO, LOG_INFOF, and TAG.
Referenced by setupRoutes().
scanTask()
void WiFiManager::scanTask (void * pvParameters) static
Definition at line 88 of file wifi_manager.cpp.
References currentMode, DISPLAY_SPLASH_DURATION_MS, LOG_ERROR, LOG_INFO, LOG_INFOF, and TAG.
Referenced by startBackgroundScan().
setupImageRoutes()
void WiFiManager::setupImageRoutes ()
Sets up image management HTTP routes for file upload and manipulation.
Configures comprehensive image handling endpoints including: File upload with chunk processing and validation Image conversion and optimization Gallery management and listing Direct image display and preview Slideshow control integration
Features: Multi-format support (JPEG, PNG, BMP) Automatic resize and optimization Progress tracking during upload Memory-efficient chunk processing Integration with ImageManager for processing
Note
Requires ImageManager to be initialized
Handles large file uploads via chunked processing
Warning
Upload endpoint processes raw binary data - ensure proper validation
Routes configured: POST /upload - Multi-part file upload with progress tracking GET /images - Image gallery listing and management POST /image-action - Image manipulation commands GET /preview - Image preview and thumbnail generation
See also
ImageManager for file processing capabilities
SlideshowManager for display integration
Definition at line 1716 of file wifi_manager.cpp.
References ImageManager::deleteImage(), DISPLAY_SPLASH_DURATION_MS, ImageManager::displayImage(), ImageManager::displayImageOnBoth(), SlideshowManager::getImageEnabledStates(), ImageManager::getImageListJson(), ImageManager::getLastError(), ImageManager::getSystemInfo(), ImageManager::handleImageUpload(), imageManager, LOG_ERROR, LOG_ERRORF, LOG_INFO, LOG_INFOF, LOG_WARN, SlideshowManager::refreshImageList(), server, MemoryManager::setMonitoringEnabled(), slideshowManager, TAG, and SlideshowManager::updateImageEnabledState().
Referenced by setupNormalModeRoutes().
setupNormalModeRoutes()
void WiFiManager::setupNormalModeRoutes ()
Configures web server routes for normal operation mode.
Establishes production web interface endpoints for billboard operation, system management, and user interaction. Provides comprehensive routing for all normal mode functionality including display control, settings, and system monitoring.
Normal Mode Routes: GET / - Main billboard interface with live display data GET /settings - System configuration and management page
POST /settings - Configuration updates and system changes GET /api/status - Real-time system status and health data GET /api/images - Current image library and metadata Integration with image upload and slideshow management
Route Features: Dynamic HTML templating with live system data RESTful API endpoints for programmatic access Real-time status monitoring and health checks Settings management with validation and persistence Image library management and slideshow control
Template Processing: Live system data injection (WiFi status, memory usage) Device information display (IP address, firmware version) Dynamic content updates based on current system state Error handling for missing templates or data
Note
Routes configured for production operation after WiFi connection
All routes include proper CORS headers for web compatibility
Template processing includes security considerations
See also
setupImageRoutes() for image management endpoint configuration
getIndexHTML() for main interface template processing
Definition at line 1111 of file wifi_manager.cpp.
References CredentialManager::clearCredentials(), dccManager, DisplayManager::deselectAll(), DISPLAY_SPLASH_DURATION_MS, displayManager, SettingsManager::getBrightness(), SettingsManager::getClockFace(), TimeManager::getClockLabel(), TimeManager::getCurrentTime(), SettingsManager::getDCCAddress(), SettingsManager::getDCCPin(), SettingsManager::getImageInterval(), MemoryManager::getMemoryStatsJson(), TimeManager::getNTPServer1(), PlatformDetector::getPlatformSummary(), DisplayManager::getTFT(), TimeManager::getTimezoneOptions(), SettingsManager::isClockEnabled(), SettingsManager::isDCCEnabled(), SettingsManager::isImageEnabled(), SettingsManager::isSecondDisplayEnabled(), TimeManager::isTimeValid(), LOG_DEBUG, LOG_ERROR, LOG_INFO, LOG_INFOF, LOG_WARN, LOG_WARNF, restartPending, restartScheduledTime, DisplayManager::selectDisplay(), server, DCCManager::setAddress(), SettingsManager::setBrightness(), DisplayManager::setBrightness(), SettingsManager::setClockEnabled(), SettingsManager::setClockFace(), TimeManager::setClockLabel(), SettingsManager::setDCCAddress(), SettingsManager::setDCCEnabled(), SettingsManager::setDCCPin(), DCCManager::setEnabled(), SettingsManager::setImageEnabled(), SettingsManager::setImageInterval(), TimeManager::setNTPServer(), DCCManager::setPin(), SettingsManager::setSecondDisplayEnabled(), TimeManager::setTimezone(), settingsManager, setupImageRoutes(), setupOTARoutes(), switchToPortalMode, TAG, and timeManager.
Referenced by switchToNormalMode().
setupOTARoutes()
void WiFiManager::setupOTARoutes ()
Configures Over-The-Air (OTA) firmware update web endpoints.
Establishes secure web-based firmware update capability allowing remote system updates without physical device access. Implements comprehensive validation, progress monitoring, and error handling for safe updates.
OTA Update Features: Secure firmware binary validation before installation Real-time upload progress monitoring and feedback Comprehensive error handling and recovery mechanisms Platform-specific firmware compatibility checking Automatic system restart after successful update
Configured Endpoints: POST /ota-update: Firmware binary upload and installation Filename validation for platform compatibility Binary signature verification for security Progress tracking for user feedback
Security Measures: Firmware filename validation against expected patterns Binary header verification for ESP32 compatibility Upload size limitations to prevent memory exhaustion Error state handling to prevent partial installations
Note
OTA updates require system restart to take effect
Failed updates maintain current firmware integrity
Warning
OTA process temporarily interrupts normal operations
See also
validateFirmwareFilename() for filename security checking
validateFirmwareBinary() for binary integrity verification
Definition at line 2421 of file wifi_manager.cpp.
References BUILD_DATE, BUILD_TYPE, PlatformDetector::CHIP_ESP32_CLASSIC, PlatformDetector::CHIP_ESP32_S3, PlatformDetector::detectPlatform(), DISPLAY_SPLASH_DURATION_MS, FIRMWARE_VERSION, getFirmwareVersion(), LOG_ERROR, LOG_ERRORF, LOG_INFO, LOG_INFOF, restartPending, restartScheduledTime, server, TAG, and validateFirmwareFilename().
Referenced by setupNormalModeRoutes(), and setupRoutes().
setupRoutes()
void WiFiManager::setupRoutes ()
Configures comprehensive web server routes for setup mode.
Establishes complete web interface routing for WiFi setup and initial system configuration. Provides memory-aware content serving, comprehensive system diagnostics, network scanning, credential management, and robust error handling for setup mode operations.
Route Categories: System Diagnostics: /test, /status, /memory endpoints for health monitoring Network Management: /, /portal for main interface, /scan for network discovery Connection Control: /connect for WiFi credential submission and validation Visual Interface: Portal HTML with responsive design and status feedback Memory Management: Dynamic content serving based on available heap memory Real-time Status: Live system information including memory health and connectivity
Key Features: Memory-aware content serving (minimal interface for low memory conditions) Chunked response handling for large HTML content Cross-Origin Resource Sharing (CORS) support for external access Comprehensive error handling with user-friendly feedback Real-time memory and system status reporting Network scanning with security information display
Note
Routes configured here are active only in setup mode. Normal mode uses setupNormalModeRoutes() for expanded functionality.
Memory threshold of 50KB used for content serving decisions to prevent crashes.
Definition at line 271 of file wifi_manager.cpp.
References currentMode, DisplayManager::deselectAll(), DISPLAY_SPLASH_DURATION_MS, displayManager, MemoryManager::getAvailableMemory(), MemoryManager::getHealthStatus(), MemoryManager::getHealthStatusString(), MemoryManager::getMemoryStatsJson(), MemoryManager::getOverallHealth(), DisplayManager::getTFT(), handleConnect(), MemoryManager::HEAP_INTERNAL, MemoryManager::isCriticalMemory(), MemoryManager::isLowMemory(), LOG_DEBUG, LOG_ERROR, LOG_INFO, LOG_INFOF, LOG_WARNF, MODE_SETUP, MemoryManager::PSRAM_EXTERNAL, scanNetworks(), DisplayManager::selectDisplay(), server, setupOTARoutes(), and TAG.
Referenced by switchToSetupMode().
startBackgroundScan()
void WiFiManager::startBackgroundScan (unsigned long ttlMs = 30000)
Definition at line 161 of file wifi_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, LOG_ERROR, scanInProgress, scanTask(), scanTTLMs, and TAG.
startServer()
void WiFiManager::startServer ()
Starts the HTTP web server for client request handling.
Activates the AsyncWebServer instance to begin listening for HTTP requests on port 80. Enables access to all configured routes including portal interface, system diagnostics, and WiFi configuration endpoints. Server activation is the final step in setup mode preparation.
Note
Server must be started after route configuration (setupRoutes()) to ensure all endpoints are properly registered and available to clients.
Default HTTP port 80 used for standard web browser compatibility.
Definition at line 475 of file wifi_manager.cpp.
References LOG_INFO, server, and TAG.
Referenced by switchToNormalMode(), and switchToSetupMode().
switchToNormalMode()
void WiFiManager::switchToNormalMode ()
Transitions system from setup mode to full operational normal mode.
Reconfigures WiFiManager for normal operation mode after successful WiFi connection. Stops setup mode web server, configures comprehensive normal mode routes, and restarts server with full system functionality including image management, DCC control, and advanced system monitoring capabilities.
Transition Process: Updates internal mode state from MODE_SETUP to MODE_NORMAL Gracefully stops existing web server to prevent connection conflicts Configures comprehensive normal mode route set via setupNormalModeRoutes() Restarts web server with expanded functionality and system integration Provides visual confirmation of successful mode transition
Normal Mode Features: Full web interface with image upload and management DCC command interface for model railroad control Comprehensive system status and configuration endpoints Real-time monitoring and diagnostic capabilities Advanced settings management and system control
Note
Mode transition involves brief service interruption during server restart
Normal mode provides access to full system functionality and integration
Server remains accessible via WiFi IP address after transition
Definition at line 1000 of file wifi_manager.cpp.
References currentMode, DISPLAY_SPLASH_DURATION_MS, LOG_INFO, LOG_INFOF, MODE_NORMAL, server, setupNormalModeRoutes(), startServer(), and TAG.
Referenced by checkConnectionSuccessDisplay().
switchToSetupMode()
void WiFiManager::switchToSetupMode ()
Transitions system from normal mode to setup mode for configuration.
Reconfigures WiFiManager for setup mode operation when WiFi connection is lost, factory reset is triggered, or manual configuration is required. Establishes Access Point mode for secure credential entry and system reconfiguration.
Transition Process: Updates internal mode state from MODE_NORMAL to MODE_SETUP Records setup mode initiation timestamp for timeout management Gracefully stops current web server to prevent service conflicts Disconnects from current WiFi network to free radio resources Initializes Access Point with predefined SSID and password Configures setup mode routes for credential entry and system configuration Restarts web server with portal interface for user access
Setup Mode Features: Isolated Access Point for secure configuration without external dependencies WiFi network scanning and selection interface Credential entry and validation system Basic system status and diagnostic capabilities Factory reset and system restoration options
Note
Setup mode provides isolated network environment for secure reconfiguration
Mode transition involves brief service interruption during server restart
Access Point credentials defined by PORTAL_SSID and PORTAL_PASSWORD constants
Definition at line 1043 of file wifi_manager.cpp.
References currentMode, DISPLAY_SPLASH_DURATION_MS, initializeAP(), LOG_INFO, LOG_INFOF, MODE_SETUP, PORTAL_PASSWORD, PORTAL_SSID, server, setupRoutes(), startServer(), and TAG.
Referenced by checkPortalModeSwitch(), and initializeFromCredentials().
validateFirmwareBinary()
bool WiFiManager::validateFirmwareBinary (uint8_t * data, size_t length)
Validates firmware binary content for ESP32 compatibility.
Performs binary-level validation of firmware data to ensure compatibility with ESP32 architecture and prevent installation of corrupted or invalid firmware that could damage the system or cause malfunction.
Binary Validation Checks: Size validation within ESP32 flash memory limits ESP32 binary header verification and magic numbers Segment structure validation for proper loading Checksum verification for data integrity
Size Constraints: Minimum size: 100KB (prevents invalid/incomplete binaries) Maximum size: 4MB (ESP32 flash memory partition limit) Realistic size range validation for typical firmware
ESP32 Binary Format: Magic number verification (0xE9 at offset 0) Segment count validation Load address verification Entry point validation
Security Features: Prevents upload of non-ESP32 binaries Detects corrupted firmware files Validates binary structure integrity Protects against malicious firmware uploads
Parameters
data Pointer to firmware binary data buffer
length Size of firmware binary in bytes
Returns
bool Binary validation result
Return values
true Binary is valid ESP32 firmware
false Binary is invalid or incompatible
Note
Validation includes both basic checks and ESP32-specific format verification
Failed validation prevents OTA update process from starting
Warning
Installing invalid firmware will cause system malfunction
See also
ESP32 Technical Reference Manual for binary format specifications
validateFirmwareFilename() for filename-based compatibility checking
Definition at line 2713 of file wifi_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, LOG_INFO, LOG_WARN, and TAG.
validateFirmwareFilename()
bool WiFiManager::validateFirmwareFilename (const String & filename)
Validates firmware filename for platform and display compatibility.
Performs security validation to ensure uploaded firmware matches current hardware platform and display configuration. Prevents installation of incompatible firmware that could cause system malfunction or damage.
Validation Criteria: Platform compatibility (ESP32 vs ESP32-S3) Display type matching (ST7735 vs ST7789) Filename pattern verification for expected format Build type identification (debug, production, latest)
Expected Filename Patterns: esp32_ST7735_*.bin - ESP32 with ST7735 display esp32_ST7789_*.bin - ESP32 with ST7789 display esp32s3_ST7735_*.bin - ESP32-S3 with ST7735 display esp32s3_ST7789_*.bin - ESP32-S3 with ST7789 display
Security Benefits: Prevents cross-platform firmware installation Avoids display driver incompatibility issues Reduces risk of hardware damage from wrong firmware Ensures proper functionality after update
Parameters
filename Firmware filename to validate against current hardware
Returns
bool Validation result indicating compatibility
Return values
true Firmware is compatible with current hardware
false Firmware is incompatible and should be rejected
Note
Uses PlatformDetector for current hardware identification
Display type determined from compile-time definitions
Warning
Installing incompatible firmware may render device inoperable
See also
PlatformDetector::detectPlatform() for hardware identification
validateFirmwareBinary() for binary content validation
Definition at line 2619 of file wifi_manager.cpp.
References PlatformDetector::CHIP_ESP32_CLASSIC, PlatformDetector::CHIP_ESP32_S3, PlatformDetector::detectPlatform(), DISPLAY_SPLASH_DURATION_MS, LOG_INFO, LOG_INFOF, LOG_WARN, LOG_WARNF, and TAG.
Referenced by setupOTARoutes().
Field Documentation
apPassword
String WiFiManager::apPassword private
Definition at line 95 of file wifi_manager.h.
Referenced by initializeAP(), and WiFiManager().
apSSID
String WiFiManager::apSSID private
Definition at line 94 of file wifi_manager.h.
Referenced by initializeAP(), and WiFiManager().
cachedNetworksJson
String WiFiManager::cachedNetworksJson private
Definition at line 117 of file wifi_manager.h.
Referenced by WiFiManager().
connectionRetryCount
int WiFiManager::connectionRetryCount private
Definition at line 98 of file wifi_manager.h.
Referenced by checkConnectionStatus(), connectToSavedNetwork(), and WiFiManager().
connectionSuccessDisplayed
bool WiFiManager::connectionSuccessDisplayed private
Definition at line 114 of file wifi_manager.h.
Referenced by checkConnectionSuccessDisplay(), connectToSavedNetwork(), handleConnect(), isShowingConnectionSuccess(), and WiFiManager().
connectionSuccessStartTime
unsigned long WiFiManager::connectionSuccessStartTime private
Definition at line 115 of file wifi_manager.h.
Referenced by checkConnectionSuccessDisplay(), connectToSavedNetwork(), handleConnect(), and WiFiManager().
currentMode
OperationMode WiFiManager::currentMode private
Definition at line 96 of file wifi_manager.h.
Referenced by checkConnectionStatus(), checkConnectionSuccessDisplay(), getCurrentMode(), getWiFiIP(), initializeAP(), isConnectedToWiFi(), scanNetworks(), scanTask(), setupRoutes(), switchToNormalMode(), switchToSetupMode(), and WiFiManager().
dccManager
class DCCManager* WiFiManager::dccManager private
Definition at line 93 of file wifi_manager.h.
Referenced by setupNormalModeRoutes(), and WiFiManager().
displayManager
DisplayManager* WiFiManager::displayManager private
Definition at line 90 of file wifi_manager.h.
Referenced by connectToSavedNetwork(), connectToWiFi(), handleConnect(), initializeAP(), setupNormalModeRoutes(), setupRoutes(), and WiFiManager().
FACTORY_RESET_DURATION
const unsigned long WiFiManager::FACTORY_RESET_DURATION = 6000 static private
Definition at line 106 of file wifi_manager.h.
Referenced by checkGpio0FactoryReset().
GPIO0_PIN
const int WiFiManager::GPIO0_PIN = 0 static private
Definition at line 107 of file wifi_manager.h.
Referenced by checkGpio0FactoryReset().
gpio0Pressed
bool WiFiManager::gpio0Pressed private
Definition at line 100 of file wifi_manager.h.
Referenced by checkGpio0FactoryReset(), and WiFiManager().
gpio0PressStart
unsigned long WiFiManager::gpio0PressStart private
Definition at line 101 of file wifi_manager.h.
Referenced by checkGpio0FactoryReset(), and WiFiManager().
imageManager
ImageManager* WiFiManager::imageManager private
Definition at line 91 of file wifi_manager.h.
Referenced by setupImageRoutes(), and WiFiManager().
lastConnectionAttempt
unsigned long WiFiManager::lastConnectionAttempt private
Definition at line 97 of file wifi_manager.h.
Referenced by checkConnectionStatus(), and WiFiManager().
lastGpio0Check
unsigned long WiFiManager::lastGpio0Check private
Definition at line 99 of file wifi_manager.h.
Referenced by checkGpio0FactoryReset(), and WiFiManager().
lastScanMs
unsigned long WiFiManager::lastScanMs private
Definition at line 118 of file wifi_manager.h.
Referenced by WiFiManager().
MAX_RETRY_ATTEMPTS
const int WiFiManager::MAX_RETRY_ATTEMPTS = 3 static private
Definition at line 104 of file wifi_manager.h.
Referenced by checkConnectionStatus().
restartPending
bool WiFiManager::restartPending private
Definition at line 109 of file wifi_manager.h.
Referenced by checkGpio0FactoryReset(), checkScheduledRestart(), handleConnect(), setupNormalModeRoutes(), setupOTARoutes(), and WiFiManager().
restartScheduledTime
unsigned long WiFiManager::restartScheduledTime private
Definition at line 110 of file wifi_manager.h.
Referenced by checkGpio0FactoryReset(), checkScheduledRestart(), handleConnect(), setupNormalModeRoutes(), setupOTARoutes(), and WiFiManager().
RETRY_DELAYS
const unsigned long WiFiManager::RETRY_DELAYS = { 5000, 15000, 30000 } static private
Definition at line 54 of file wifi_manager.h.
Referenced by checkConnectionStatus().
scanInProgress
bool WiFiManager::scanInProgress private
Definition at line 119 of file wifi_manager.h.
Referenced by startBackgroundScan(), and WiFiManager().
scanTTLMs
unsigned long WiFiManager::scanTTLMs private
Definition at line 120 of file wifi_manager.h.
Referenced by startBackgroundScan(), and WiFiManager().
server
AsyncWebServer* WiFiManager::server private
Definition at line 87 of file wifi_manager.h.
Referenced by setupImageRoutes(), setupNormalModeRoutes(), setupOTARoutes(), setupRoutes(), startServer(), switchToNormalMode(), switchToSetupMode(), and WiFiManager().
settingsManager
SettingsManager* WiFiManager::settingsManager private
Definition at line 89 of file wifi_manager.h.
Referenced by setupNormalModeRoutes(), and WiFiManager().
slideshowManager
class SlideshowManager* WiFiManager::slideshowManager private
Definition at line 92 of file wifi_manager.h.
Referenced by setupImageRoutes(), and WiFiManager().
switchToPortalMode
bool WiFiManager::switchToPortalMode private
Definition at line 111 of file wifi_manager.h.
Referenced by checkPortalModeSwitch(), setupNormalModeRoutes(), and WiFiManager().
timeManager
TimeManager* WiFiManager::timeManager private
Definition at line 88 of file wifi_manager.h.
Referenced by setupNormalModeRoutes(), and WiFiManager().
The documentation for this class was generated from the following files:
include/wifi_manager.h
src/wifi_manager.cpp