Dual Display Billboard: ConfigValidator Class Reference
ConfigValidator Class Reference
Comprehensive multiplatform configuration validation system.
#include <config_validator.h>
Data Structures
struct PlatformConstraints
Platform-specific GPIO constraints.
struct ValidationReport
Comprehensive validation report.
struct ValidationResult
Individual validation result.
Public Types
enum PlatformType { PLATFORM_ESP32_DEV = 0 , PLATFORM_ESP32_S3 = 1 , PLATFORM_UNKNOWN = 255 }
Platform identification enumeration.
enum DisplayType { DISPLAY_ST7735 = 0 , DISPLAY_ST7789 = 1 , DISPLAY_UNKNOWN = 255 }
Display driver enumeration.
enum ValidationSeverity { VALIDATION_OK = 0 , VALIDATION_WARNING = 1 , VALIDATION_ERROR = 2 , VALIDATION_FATAL = 3 }
Validation severity levels.
Static Public Member Functions
static bool initialize ()
Initialize the configuration validator.
static ValidationReport validateSystem (bool autoFix=true)
Perform comprehensive system validation.
static bool validateCategory (const String &category)
Validate specific configuration category.
static const ValidationReport & getLastReport ()
Get the last validation report.
static void printValidationReport (const ValidationReport *report=nullptr, bool includeDetails=true)
Print validation report to console.
static String getValidationReportJson (const ValidationReport *report=nullptr)
Get validation report as JSON string.
static bool isSystemReady ()
Check if system passed validation and is ready to operate.
static PlatformType getPlatformType ()
Get detected platform type.
static DisplayType getDisplayType ()
Get detected display type.
static const PlatformConstraints & getPlatformConstraints ()
Get platform constraints for current platform.
static bool isValidGPIO (uint8_t pin, const String &purpose="general")
Validate a specific GPIO pin for a purpose.
static std::vector< uint8_t > getAvailableGPIOs (const String &purpose="general")
Get list of available GPIO pins for a specific purpose.
static String getPlatformName (PlatformType platform=PLATFORM_UNKNOWN)
Get human-readable platform name.
static String getDisplayName (DisplayType display=DISPLAY_UNKNOWN)
Get human-readable display type name.
static String getSeverityName (ValidationSeverity severity)
Get severity level name for JSON output.
static String getSeverityIcon (ValidationSeverity severity)
Get emoji icon for severity level.
static ValidationReport revalidateSystem (bool autoFix=true)
Force re-validation of the entire system.
static void resetValidation ()
Reset validation state and clear cached results.
Static Private Member Functions
static PlatformType detectPlatform ()
Detect the ESP32 platform type through chip information analysis.
static DisplayType detectDisplayType ()
Detect display type through compile-time driver configuration.
static void loadPlatformConstraints (PlatformType platform)
🔧 Load platform-specific validation constraints based on detected hardware
static bool validateGPIOPin (uint8_t pin, const String &purpose)
Validate individual GPIO pin against platform constraints.
static bool checkGPIOConflicts ()
Check for GPIO pin conflicts between system components.
static bool validateSPIConfiguration ()
Validate SPI bus configuration and pin assignments.
static bool validateDCCSettings ()
Validate DCC (Digital Command Control) configuration settings.
static bool validateDisplaySettings ()
Validate display configuration and hardware settings.
static bool validateImageSettings ()
Validate image processing and slideshow configuration.
static bool validateNetworkSettings ()
Validate network and WiFi configuration settings.
static bool validateTimingSettings ()
Validate timing and interval configuration settings.
static bool validateMemoryConfiguration ()
Validate memory configuration and availability.
static bool validateFileSystemHealth ()
Validate LittleFS filesystem health and availability.
static bool validateDisplayHardware ()
Validate display hardware connectivity and functionality.
static bool autoFixGPIOConflicts ()
Attempt automatic correction of GPIO conflicts.
static bool autoFixInvalidSettings ()
Attempt automatic correction of invalid settings.
static void addResult (ValidationSeverity severity, const String &category, const String &message, const String &recommendation="", bool autoFixed=false)
Add validation result to current report with statistics update.
static ValidationSeverity calculateOverallSeverity ()
Calculate overall severity based on individual validation results.
Static Private Attributes
static const char * TAG = "ConfigValidator"
static ValidationReport lastReport
static PlatformConstraints currentConstraints
Detailed Description
Comprehensive multiplatform configuration validation system.
Validates all system configurations against platform-specific capabilities, GPIO constraints, and hardware requirements. Provides automatic error correction and detailed validation reporting.
Definition at line 42 of file config_validator.h.
Member Enumeration Documentation
DisplayType
enum ConfigValidator::DisplayType
Display driver enumeration.
Enumerator
DISPLAY_ST7735
ST7735 160x80 displays.
DISPLAY_ST7789
ST7789 240x240 displays.
DISPLAY_UNKNOWN
Unknown display type.
Definition at line 56 of file config_validator.h.
PlatformType
enum ConfigValidator::PlatformType
Platform identification enumeration.
Enumerator
PLATFORM_ESP32_DEV
Standard ESP32 development board.
PLATFORM_ESP32_S3
ESP32-S3 with enhanced capabilities.
PLATFORM_UNKNOWN
Unknown or unsupported platform.
Definition at line 47 of file config_validator.h.
ValidationSeverity
enum ConfigValidator::ValidationSeverity
Validation severity levels.
Enumerator
VALIDATION_OK
Configuration is valid.
VALIDATION_WARNING
Non-critical issues found.
VALIDATION_ERROR
Critical issues found.
VALIDATION_FATAL
Fatal errors, system cannot start.
Definition at line 65 of file config_validator.h.
Member Function Documentation
addResult()
void ConfigValidator::addResult (ValidationSeverity severity, const String & category, const String & message, const String & recommendation = "", bool autoFixed = false) static private
Add validation result to current report with statistics update.
Parameters
severity Severity level of the validation result
category Component category being validated
message Descriptive message about the validation result
recommendation Optional recommendation for issue resolution
autoFixed Flag indicating if issue was automatically corrected
Adds a new validation result to the current report and updates the appropriate severity counters for report statistics.
Definition at line 783 of file config_validator.cpp.
References ConfigValidator::ValidationReport::autoFixedCount, DISPLAY_SPLASH_DURATION_MS, ConfigValidator::ValidationReport::errorCount, ConfigValidator::ValidationReport::fatalCount, lastReport, ConfigValidator::ValidationReport::okCount, ConfigValidator::ValidationReport::results, VALIDATION_ERROR, VALIDATION_FATAL, VALIDATION_OK, VALIDATION_WARNING, and ConfigValidator::ValidationReport::warningCount.
Referenced by autoFixGPIOConflicts(), autoFixInvalidSettings(), checkGPIOConflicts(), validateDCCSettings(), validateDisplayHardware(), validateDisplaySettings(), validateFileSystemHealth(), validateGPIOPin(), validateImageSettings(), validateMemoryConfiguration(), validateNetworkSettings(), validateSPIConfiguration(), validateSystem(), and validateTimingSettings().
autoFixGPIOConflicts()
bool ConfigValidator::autoFixGPIOConflicts () static private
Attempt automatic correction of GPIO conflicts.
Returns
true if conflicts were resolved, false otherwise
Identifies and attempts to resolve GPIO pin conflicts by suggesting alternative pin assignments or configuration changes.
Definition at line 749 of file config_validator.cpp.
References addResult(), and VALIDATION_OK.
autoFixInvalidSettings()
bool ConfigValidator::autoFixInvalidSettings () static private
Attempt automatic correction of invalid settings.
Returns
true if settings were corrected, false otherwise
Identifies and corrects settings that are outside valid ranges or incompatible with current platform capabilities.
Definition at line 762 of file config_validator.cpp.
References addResult(), and VALIDATION_OK.
calculateOverallSeverity()
ConfigValidator::ValidationSeverity ConfigValidator::calculateOverallSeverity () static private
Calculate overall severity based on individual validation results.
Returns
Highest severity level found in validation results
Determines the overall system validation status by finding the most severe validation result across all tested components.
Definition at line 816 of file config_validator.cpp.
References ConfigValidator::ValidationReport::errorCount, ConfigValidator::ValidationReport::fatalCount, lastReport, VALIDATION_ERROR, VALIDATION_FATAL, VALIDATION_OK, VALIDATION_WARNING, and ConfigValidator::ValidationReport::warningCount.
Referenced by validateSystem().
checkGPIOConflicts()
bool ConfigValidator::checkGPIOConflicts () static private
Check for GPIO pin conflicts between system components.
Returns
true if no conflicts detected, false otherwise
Validates that no two system components are attempting to use the same GPIO pin simultaneously.
Definition at line 604 of file config_validator.cpp.
References addResult(), and VALIDATION_OK.
detectDisplayType()
ConfigValidator::DisplayType ConfigValidator::detectDisplayType () static private
Detect display type through compile-time driver configuration.
Returns
Detected display type based on TFT_eSPI driver configuration
Examines compile-time driver definitions to determine which display driver is configured for the current build, enabling display-specific validation.
Definition at line 118 of file config_validator.cpp.
References DISPLAY_ST7735, DISPLAY_ST7789, DISPLAY_UNKNOWN, LOG_INFOF, LOG_WARNF, and TAG.
Referenced by initialize(), and validateSystem().
detectPlatform()
ConfigValidator::PlatformType ConfigValidator::detectPlatform () static private
Detect the ESP32 platform type through chip information analysis.
Returns
Detected platform type with ESP32-S3 vs standard ESP32 classification
Uses ESP-IDF chip information API to determine the specific ESP32 variant and configure appropriate validation constraints for the detected hardware.
Definition at line 94 of file config_validator.cpp.
References DISPLAY_SPLASH_DURATION_MS, LOG_INFOF, LOG_WARNF, PLATFORM_ESP32_DEV, PLATFORM_ESP32_S3, PLATFORM_UNKNOWN, and TAG.
Referenced by initialize(), and validateSystem().
getAvailableGPIOs()
std::vector< uint8_t > ConfigValidator::getAvailableGPIOs (const String & purpose = "general") static
Get list of available GPIO pins for a specific purpose.
Parameters
purpose Purpose description (affects filtering)
Returns
Vector of available GPIO pin numbers
Definition at line 449 of file config_validator.cpp.
References currentConstraints, DISPLAY_SPLASH_DURATION_MS, ConfigValidator::PlatformConstraints::maxGPIO, ConfigValidator::PlatformConstraints::minGPIO, and validateGPIOPin().
getDisplayName()
String ConfigValidator::getDisplayName (DisplayType display = DISPLAY_UNKNOWN) static
Get human-readable display type name.
Get human-readable display name for reporting.
Parameters
display Display type (uses detected if not specified)
Returns
Display type name string
Parameters
display Display type to convert (uses detected display if UNKNOWN)
Returns
Human-readable display name with specifications
Definition at line 485 of file config_validator.cpp.
References ConfigValidator::ValidationReport::detectedDisplay, DISPLAY_SPLASH_DURATION_MS, DISPLAY_ST7735, DISPLAY_ST7789, DISPLAY_UNKNOWN, and lastReport.
Referenced by getValidationReportJson(), initialize(), printValidationReport(), and validateSystem().
getDisplayType()
ConfigValidator::DisplayType ConfigValidator::getDisplayType () static
Get detected display type.
Get detected display type from last validation.
Returns
Detected display type
Display type enumeration value
Returns the display type detected during the most recent validation based on compile-time driver configuration.
Definition at line 417 of file config_validator.cpp.
References ConfigValidator::ValidationReport::detectedDisplay, and lastReport.
getLastReport()
const ConfigValidator::ValidationReport & ConfigValidator::getLastReport () static
Get the last validation report.
Returns
Reference to the last validation report
Reference to the cached validation report
Returns the most recent validation report without re-executing validation. Useful for accessing validation results multiple times efficiently.
Definition at line 310 of file config_validator.cpp.
References lastReport.
getPlatformConstraints()
const ConfigValidator::PlatformConstraints & ConfigValidator::getPlatformConstraints () static
Get platform constraints for current platform.
Get current platform constraints for validation operations.
Returns
Platform-specific constraints
Reference to current platform constraints structure
Provides access to the platform-specific constraints loaded during initialization for use in external validation operations.
Definition at line 428 of file config_validator.cpp.
References currentConstraints.
getPlatformName()
String ConfigValidator::getPlatformName (PlatformType platform = PLATFORM_UNKNOWN) static
Get human-readable platform name.
Get human-readable platform name for reporting.
Parameters
platform Platform type (uses detected if not specified)
Returns
Platform name string
Parameters
platform Platform type to convert (uses detected platform if UNKNOWN)
Returns
Human-readable platform name string
Definition at line 470 of file config_validator.cpp.
References ConfigValidator::ValidationReport::detectedPlatform, DISPLAY_SPLASH_DURATION_MS, lastReport, PLATFORM_ESP32_DEV, PLATFORM_ESP32_S3, and PLATFORM_UNKNOWN.
Referenced by getValidationReportJson(), initialize(), printValidationReport(), and validateSystem().
getPlatformType()
ConfigValidator::PlatformType ConfigValidator::getPlatformType () static
Get detected platform type.
Get detected platform type from last validation.
Returns
Detected platform type
Platform type enumeration value
Returns the platform type detected during the most recent validation without re-executing platform detection.
Definition at line 406 of file config_validator.cpp.
References ConfigValidator::ValidationReport::detectedPlatform, and lastReport.
getSeverityIcon()
String ConfigValidator::getSeverityIcon (ValidationSeverity severity) static
Get emoji icon for severity level.
Parameters
severity Validation severity level
Returns
Emoji icon representing severity
Parameters
severity Validation severity level
Returns
Emoji icon representing the severity level
Definition at line 515 of file config_validator.cpp.
References VALIDATION_ERROR, VALIDATION_FATAL, VALIDATION_OK, and VALIDATION_WARNING.
Referenced by printValidationReport().
getSeverityName()
String ConfigValidator::getSeverityName (ValidationSeverity severity) static
Get severity level name for JSON output.
Get severity name string for JSON output.
Parameters
severity Validation severity level
Returns
String representation of severity
Parameters
severity Validation severity level
Returns
String representation of severity level
Definition at line 500 of file config_validator.cpp.
References VALIDATION_ERROR, VALIDATION_FATAL, VALIDATION_OK, and VALIDATION_WARNING.
Referenced by getValidationReportJson().
getValidationReportJson()
String ConfigValidator::getValidationReportJson (const ValidationReport * report = nullptr) static
Get validation report as JSON string.
Generate JSON representation of validation report.
Parameters
report Report to convert (uses last report if not specified)
Returns
JSON formatted validation report
Parameters
report Specific report to convert (uses cached report if null)
Returns
JSON formatted validation report string
Creates a structured JSON representation suitable for web interface integration and API responses.
Definition at line 366 of file config_validator.cpp.
References DISPLAY_SPLASH_DURATION_MS, getDisplayName(), getPlatformName(), getSeverityName(), and lastReport.
initialize()
bool ConfigValidator::initialize () static
Initialize the configuration validator.
Initialize the configuration validator with platform detection.
Returns
true if validator initialized successfully
true if validator initialized successfully, false on failure
Performs comprehensive system initialization including platform detection, display type identification, and constraint loading. Sets up the validator for subsequent validation operations with platform-specific rules.
Definition at line 68 of file config_validator.cpp.
References currentConstraints, detectDisplayType(), detectPlatform(), DISPLAY_SPLASH_DURATION_MS, getDisplayName(), getPlatformName(), ConfigValidator::PlatformConstraints::hasPSRAM, loadPlatformConstraints(), LOG_INFOF, ConfigValidator::PlatformConstraints::maxGPIO, ConfigValidator::PlatformConstraints::minGPIO, and TAG.
isSystemReady()
bool ConfigValidator::isSystemReady () static
Check if system passed validation and is ready to operate.
Check if system passed validation and is ready for operation.
Returns
true if system is ready, false if critical issues found
true if system is ready, false if critical issues found
Provides quick access to system readiness status without accessing the full validation report structure.
Definition at line 395 of file config_validator.cpp.
References lastReport, and ConfigValidator::ValidationReport::systemReady.
isValidGPIO()
bool ConfigValidator::isValidGPIO (uint8_t pin, const String & purpose = "general") static
Validate a specific GPIO pin for a purpose.
Validate GPIO pin against platform constraints.
Parameters
pin GPIO pin number to validate
purpose Description of intended use
Returns
true if pin is valid for the purpose
Parameters
pin GPIO pin number to validate
purpose Intended use description for logging
Returns
true if GPIO pin is valid for use, false otherwise
Performs comprehensive GPIO validation including range checking, reserved pin detection, and input-only pin restrictions.
Definition at line 445 of file config_validator.cpp.
References DISPLAY_SPLASH_DURATION_MS, and validateGPIOPin().
loadPlatformConstraints()
void ConfigValidator::loadPlatformConstraints (PlatformType platform) static private
🔧 Load platform-specific validation constraints based on detected hardware
Parameters
platform Detected platform type for constraint configuration
Configures platform-specific GPIO constraints, memory limits, and hardware capabilities based on the detected ESP32 variant. Essential for proper validation of user configurations against hardware limitations.
Definition at line 144 of file config_validator.cpp.
References currentConstraints, DISPLAY_SPLASH_DURATION_MS, ConfigValidator::PlatformConstraints::hasPSRAM, ConfigValidator::PlatformConstraints::inputOnlyPins, LOG_ERRORF, LOG_INFOF, ConfigValidator::PlatformConstraints::maxGPIO, ConfigValidator::PlatformConstraints::maxRAM, ConfigValidator::PlatformConstraints::minGPIO, PLATFORM_ESP32_DEV, PLATFORM_ESP32_S3, ConfigValidator::PlatformConstraints::platformName, ConfigValidator::PlatformConstraints::reservedPins, ConfigValidator::PlatformConstraints::spiPins, and TAG.
Referenced by initialize().
printValidationReport()
void ConfigValidator::printValidationReport (const ValidationReport * report = nullptr, bool includeDetails = true) static
Print validation report to console.
Print comprehensive validation report to console with detailed formatting.
Parameters
report Report to print (uses last report if not specified)
includeDetails Include detailed results in output
report Specific report to print (uses cached report if null)
includeDetails Include detailed validation results in output
Outputs a formatted validation report suitable for debugging and system monitoring. Provides both summary statistics and optional detailed result breakdown.
Definition at line 326 of file config_validator.cpp.
References DISPLAY_SPLASH_DURATION_MS, getDisplayName(), getPlatformName(), getSeverityIcon(), lastReport, LOG_INFOF, and TAG.
resetValidation()
void ConfigValidator::resetValidation () static
Reset validation state and clear cached results.
Clears all cached validation results and resets counters to prepare for fresh validation execution.
Definition at line 544 of file config_validator.cpp.
References lastReport.
Referenced by revalidateSystem().
revalidateSystem()
ConfigValidator::ValidationReport ConfigValidator::revalidateSystem (bool autoFix = true) static
Force re-validation of the entire system.
Re-execute system validation with fresh state.
Parameters
autoFix Enable automatic fixing
Returns
New validation report
Parameters
autoFix Enable automatic correction of non-critical issues
Returns
Fresh validation report
Clears cached validation state and performs complete system re-validation. Useful when system configuration may have changed since last validation.
Definition at line 533 of file config_validator.cpp.
References DISPLAY_SPLASH_DURATION_MS, resetValidation(), and validateSystem().
validateCategory()
bool ConfigValidator::validateCategory (const String & category) static
Validate specific configuration category.
Parameters
category Configuration category to validate
Returns
true if category passed validation
Parameters
category Configuration category to validate
Returns
true if category passed validation, false otherwise
Provides targeted validation for specific system components without executing full system validation. Useful for focused validation checks.
Definition at line 292 of file config_validator.cpp.
References LOG_WARNF, TAG, validateDisplayHardware(), validateDisplaySettings(), validateFileSystemHealth(), validateGPIOPin(), and validateMemoryConfiguration().
validateDCCSettings()
bool ConfigValidator::validateDCCSettings () static private
Validate DCC (Digital Command Control) configuration settings.
Returns
true if DCC settings are valid, false otherwise
Definition at line 638 of file config_validator.cpp.
References addResult(), and VALIDATION_OK.
validateDisplayHardware()
bool ConfigValidator::validateDisplayHardware () static private
Validate display hardware connectivity and functionality.
Returns
true if display hardware is accessible, false otherwise
Definition at line 732 of file config_validator.cpp.
References addResult(), and VALIDATION_OK.
Referenced by validateCategory().
validateDisplaySettings()
bool ConfigValidator::validateDisplaySettings () static private
Validate display configuration and hardware settings.
Returns
true if display settings are valid, false otherwise
Definition at line 647 of file config_validator.cpp.
References addResult(), and VALIDATION_OK.
Referenced by validateCategory().
validateFileSystemHealth()
bool ConfigValidator::validateFileSystemHealth () static private
Validate LittleFS filesystem health and availability.
Returns
true if filesystem is healthy, false otherwise
Definition at line 702 of file config_validator.cpp.
References addResult(), DISPLAY_SPLASH_DURATION_MS, VALIDATION_ERROR, VALIDATION_OK, and VALIDATION_WARNING.
Referenced by validateCategory(), and validateSystem().
validateGPIOPin()
bool ConfigValidator::validateGPIOPin (uint8_t pin, const String & purpose) static private
Validate individual GPIO pin against platform constraints.
Parameters
pin GPIO pin number to validate
purpose Intended use description for constraint checking
Returns
true if GPIO pin is valid and available, false otherwise
Performs comprehensive GPIO validation including range checking, reserved pin detection, input-only restrictions, and SPI conflicts.
Definition at line 561 of file config_validator.cpp.
References addResult(), currentConstraints, DISPLAY_SPLASH_DURATION_MS, ConfigValidator::PlatformConstraints::inputOnlyPins, ConfigValidator::PlatformConstraints::maxGPIO, ConfigValidator::PlatformConstraints::minGPIO, ConfigValidator::PlatformConstraints::reservedPins, VALIDATION_ERROR, and VALIDATION_OK.
Referenced by getAvailableGPIOs(), isValidGPIO(), validateCategory(), validateSPIConfiguration(), and validateSystem().
validateImageSettings()
bool ConfigValidator::validateImageSettings () static private
Validate image processing and slideshow configuration.
Returns
true if image settings are valid, false otherwise
Definition at line 656 of file config_validator.cpp.
References addResult(), and VALIDATION_OK.
validateMemoryConfiguration()
bool ConfigValidator::validateMemoryConfiguration () static private
Validate memory configuration and availability.
Returns
true if memory configuration is adequate, false otherwise
Definition at line 683 of file config_validator.cpp.
References addResult(), DISPLAY_SPLASH_DURATION_MS, VALIDATION_OK, and VALIDATION_WARNING.
Referenced by validateCategory(), and validateSystem().
validateNetworkSettings()
bool ConfigValidator::validateNetworkSettings () static private
Validate network and WiFi configuration settings.
Returns
true if network settings are valid, false otherwise
Definition at line 665 of file config_validator.cpp.
References addResult(), and VALIDATION_OK.
validateSPIConfiguration()
bool ConfigValidator::validateSPIConfiguration () static private
Validate SPI bus configuration and pin assignments.
Returns
true if SPI configuration is valid, false otherwise
Ensures SPI pins are properly configured and available for display and other peripheral communication.
Definition at line 617 of file config_validator.cpp.
References addResult(), currentConstraints, DISPLAY_SPLASH_DURATION_MS, ConfigValidator::PlatformConstraints::spiPins, validateGPIOPin(), VALIDATION_OK, and VALIDATION_WARNING.
validateSystem()
ConfigValidator::ValidationReport ConfigValidator::validateSystem (bool autoFix = true) static
Perform comprehensive system validation.
Perform comprehensive system validation across all components.
Parameters
autoFix Enable automatic fixing of correctable issues (default: true)
Returns
Comprehensive validation report
Parameters
autoFix Enable automatic correction of non-critical issues
Returns
Complete validation report with results and statistics
Executes full system validation including platform verification, GPIO configuration checking, settings validation, and hardware verification. Optionally applies automatic corrections for recoverable issues.
Definition at line 212 of file config_validator.cpp.
References addResult(), calculateOverallSeverity(), currentConstraints, detectDisplayType(), ConfigValidator::ValidationReport::detectedDisplay, ConfigValidator::ValidationReport::detectedPlatform, detectPlatform(), DISPLAY_SPLASH_DURATION_MS, DISPLAY_UNKNOWN, ConfigValidator::ValidationReport::errorCount, ConfigValidator::ValidationReport::fatalCount, getDisplayName(), getPlatformName(), MemoryManager::getStats(), ConfigValidator::PlatformConstraints::hasPSRAM, lastReport, LOG_INFOF, LOG_WARNF, ConfigValidator::ValidationReport::overallSeverity, PLATFORM_UNKNOWN, ConfigValidator::ValidationReport::systemReady, TAG, validateFileSystemHealth(), validateGPIOPin(), validateMemoryConfiguration(), VALIDATION_ERROR, VALIDATION_OK, and VALIDATION_WARNING.
Referenced by revalidateSystem().
validateTimingSettings()
bool ConfigValidator::validateTimingSettings () static private
Validate timing and interval configuration settings.
Returns
true if timing settings are valid, false otherwise
Definition at line 674 of file config_validator.cpp.
References addResult(), and VALIDATION_OK.
Field Documentation
currentConstraints
ConfigValidator::PlatformConstraints ConfigValidator::currentConstraints static private
Definition at line 126 of file config_validator.h.
Referenced by getAvailableGPIOs(), getPlatformConstraints(), initialize(), loadPlatformConstraints(), validateGPIOPin(), validateSPIConfiguration(), and validateSystem().
lastReport
ConfigValidator::ValidationReport ConfigValidator::lastReport static private
Definition at line 125 of file config_validator.h.
Referenced by addResult(), calculateOverallSeverity(), getDisplayName(), getDisplayType(), getLastReport(), getPlatformName(), getPlatformType(), getValidationReportJson(), isSystemReady(), printValidationReport(), resetValidation(), and validateSystem().
TAG
const char * ConfigValidator::TAG = "ConfigValidator" static private
Definition at line 124 of file config_validator.h.
Referenced by detectDisplayType(), detectPlatform(), initialize(), loadPlatformConstraints(), printValidationReport(), validateCategory(), and validateSystem().
The documentation for this class was generated from the following files:
include/config_validator.h
src/config_validator.cpp