Dual Display Billboard: CredentialManager Class Reference
CredentialManager Class Reference
Secure WiFi credential storage and management system.
#include <credential_manager.h>
Data Structures
struct WiFiCredentials
Container for WiFi network credentials with validation state.
Static Public Member Functions
static bool begin ()
Initialize credential manager and filesystem.
static bool saveCredentials (const String &ssid, const String &password)
Save WiFi credentials to persistent storage.
static WiFiCredentials loadCredentials ()
Load WiFi credentials from persistent storage.
static bool clearCredentials ()
Clear stored WiFi credentials.
static bool hasCredentials ()
Check if credentials are currently stored.
static void printFileSystemInfo ()
Print filesystem capacity and usage information.
Static Private Attributes
static const char * CREDENTIALS_FILE = "/wifi_creds.json"
LittleFS path for credential storage.
static const String TAG = "CRED"
Logging component identifier.
Detailed Description
Secure WiFi credential storage and management system.
Manages persistent storage of WiFi credentials using LittleFS filesystem with JSON-based structured storage. Provides comprehensive credential lifecycle management including storage, retrieval, validation, and secure deletion.
The manager implements a simple but robust approach to credential persistence suitable for embedded applications where device physical security is assumed. Credentials are stored in JSON format with basic input sanitization and validation to prevent filesystem corruption.
Definition at line 46 of file credential_manager.h.
Member Function Documentation
begin()
bool CredentialManager::begin () static
Initialize credential manager and filesystem.
Initialize credential manager and LittleFS filesystem.
Returns
true if initialization successful, false on failure
Initializes LittleFS filesystem with automatic formatting if mount fails. Performs filesystem health checks and reports storage capacity information. Must be called before any other credential operations.
Returns
true if initialization successful, false on failure
Definition at line 44 of file credential_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, LOG_ERROR, LOG_INFO, printFileSystemInfo(), and TAG.
Referenced by loop().
clearCredentials()
bool CredentialManager::clearCredentials () static
Clear stored WiFi credentials.
Clear stored WiFi credentials by removing the credentials file.
Returns
true if credentials cleared successfully, false on failure
Permanently removes stored WiFi credentials from filesystem. Returns true even if no credentials were stored (successful no-op). Use for factory reset or credential security purposes.
Returns
true if credentials cleared successfully or no credentials existed, false on failure
Definition at line 162 of file credential_manager.cpp.
References CREDENTIALS_FILE, DISPLAY_SPLASH_DURATION_MS, LOG_ERROR, LOG_INFO, and TAG.
Referenced by WiFiManager::checkGpio0FactoryReset(), and WiFiManager::setupNormalModeRoutes().
hasCredentials()
bool CredentialManager::hasCredentials () static
Check if credentials are currently stored.
Check if WiFi credentials are stored in the filesystem.
Returns
true if credentials file exists, false otherwise
Quick check for credential existence without loading or parsing. Useful for conditional logic and user interface state management.
Returns
true if credentials file exists, false otherwise
Definition at line 184 of file credential_manager.cpp.
References CREDENTIALS_FILE, DISPLAY_SPLASH_DURATION_MS, LOG_DEBUGF, and TAG.
Referenced by WiFiManager::initializeFromCredentials().
loadCredentials()
CredentialManager::WiFiCredentials CredentialManager::loadCredentials () static
Load WiFi credentials from persistent storage.
Load WiFi credentials from persistent storage (struct return version)
Returns
WiFiCredentials structure with loaded data or invalid state
Loads and parses stored WiFi credentials from LittleFS storage. Returns WiFiCredentials with isValid=false if no credentials exist or if parsing fails due to corruption or format errors.
Returns
WiFiCredentials struct populated with stored data or default invalid state
Definition at line 110 of file credential_manager.cpp.
References CREDENTIALS_FILE, DISPLAY_SPLASH_DURATION_MS, LOG_DEBUGF, LOG_ERROR, LOG_INFO, LOG_INFOF, and TAG.
Referenced by WiFiManager::connectToSavedNetwork(), and WiFiManager::initializeFromCredentials().
printFileSystemInfo()
void CredentialManager::printFileSystemInfo () static
Print filesystem capacity and usage information.
Print LittleFS filesystem usage statistics for debugging Outputs total, used, and free space information to the logger.
Outputs comprehensive LittleFS filesystem statistics including total capacity, used space, and available free space. Useful for debugging and system health monitoring.
Definition at line 194 of file credential_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, LOG_INFOF, and TAG.
Referenced by begin().
saveCredentials()
bool CredentialManager::saveCredentials (const String & ssid, const String & password) static
Save WiFi credentials to persistent storage.
Save WiFi credentials to persistent storage with input sanitization.
Parameters
ssid WiFi network SSID to store
password WiFi network password to store
Returns
true if credentials saved successfully, false on failure
Stores WiFi credentials in JSON format with input sanitization. Automatically escapes special characters to prevent JSON corruption. Overwrites any existing credentials with new values.
Parameters
ssid WiFi network SSID to store
password WiFi network password to store
Returns
true if credentials saved successfully, false on failure
Definition at line 73 of file credential_manager.cpp.
References CREDENTIALS_FILE, DISPLAY_SPLASH_DURATION_MS, LOG_ERROR, LOG_INFOF, and TAG.
Referenced by WiFiManager::handleConnect().
Field Documentation
CREDENTIALS_FILE
const char * CredentialManager::CREDENTIALS_FILE = "/wifi_creds.json" static private
LittleFS path for credential storage.
Storage file path.
Definition at line 51 of file credential_manager.h.
Referenced by clearCredentials(), hasCredentials(), loadCredentials(), and saveCredentials().
TAG
const String CredentialManager::TAG = "CRED" static private
Logging component identifier.
Logging identifier.
Definition at line 52 of file credential_manager.h.
Referenced by begin(), clearCredentials(), hasCredentials(), loadCredentials(), printFileSystemInfo(), and saveCredentials().
The documentation for this class was generated from the following files:
include/credential_manager.h
src/credential_manager.cpp