Dual Display Billboard: PlatformDetector Class Reference
PlatformDetector Class Reference
Platform detection and PSRAM testing utility.
#include <platform_detector.h>
Data Structures
struct PlatformInfo
Comprehensive platform information structure.
Public Types
enum ChipModel {
CHIP_ESP32_CLASSIC = 0 , CHIP_ESP32_S2 = 1 , CHIP_ESP32_S3 = 2 , CHIP_ESP32_C3 = 3 ,
CHIP_UNKNOWN = 99
}
Supported chip models.
Static Public Member Functions
static PlatformInfo detectPlatform ()
Detect current platform and capabilities.
static void printPlatformInfo (const PlatformInfo &info)
Print comprehensive platform information to log.
static bool testPSRAMAllocation ()
Test PSRAM allocation and functionality.
static String getPlatformSummary ()
Get concise platform summary string.
Static Private Attributes
static const char * TAG = "PLATFORM"
Logging tag.
Detailed Description
Platform detection and PSRAM testing utility.
This class provides comprehensive detection of ESP32 family hardware variants and their PSRAM capabilities, ensuring proper multiplatform support across ESP32, ESP32-S2, ESP32-S3, and ESP32-C3 variants.
Definition at line 25 of file platform_detector.h.
Member Enumeration Documentation
ChipModel
enum PlatformDetector::ChipModel
Supported chip models.
Enumerator
CHIP_ESP32_CLASSIC
Original ESP32.
CHIP_ESP32_S2
ESP32-S2.
CHIP_ESP32_S3
ESP32-S3 (with PSRAM variants)
CHIP_ESP32_C3
ESP32-C3.
CHIP_UNKNOWN
Unknown or unsupported chip.
Definition at line 30 of file platform_detector.h.
Member Function Documentation
detectPlatform()
PlatformDetector::PlatformInfo PlatformDetector::detectPlatform () static
Detect current platform and capabilities.
Performs comprehensive ESP32 family platform detection and analysis.
Returns
Complete platform information structure
Core detection function that identifies hardware platform characteristics including chip model, CPU configuration, memory specifications, and PSRAM availability. Provides complete hardware profile for optimal system configuration.
Detection Process:
ESP chip information retrieval via esp_chip_info()
Chip model classification (ESP32/S2/S3/C3)
CPU core count and frequency detection
Flash memory size determination
PSRAM configuration and presence validation
Board variant identification based on memory configuration
Heap memory statistics collection
Board Variant Detection:
ESP32 Classic: DevKit (No PSRAM)
ESP32-S3 N8: Standard without PSRAM
ESP32-S3 N8R2: 2MB PSRAM variant
ESP32-S3 N16R8: 8MB PSRAM variant
Custom configurations: Size-based classification
Returns
PlatformInfo Complete hardware profile structure
Note
Uses compile-time BOARD_HAS_PSRAM flag for PSRAM configuration detection
Distinguishes between PSRAM compilation support and actual hardware presence
Board variant identification assists with optimal memory allocation strategies
CPU frequency and core count enable platform-specific performance tuning
See also
printPlatformInfo() for formatted output of detection results
testPSRAMAllocation() for functional PSRAM validation
getPlatformSummary() for concise platform description
Since
v0.9
Definition at line 68 of file platform_detector.cpp.
References PlatformDetector::PlatformInfo::boardVariant, CHIP_ESP32_C3, CHIP_ESP32_CLASSIC, CHIP_ESP32_S2, CHIP_ESP32_S3, CHIP_UNKNOWN, PlatformDetector::PlatformInfo::chipModel, PlatformDetector::PlatformInfo::chipName, PlatformDetector::PlatformInfo::cpuCores, PlatformDetector::PlatformInfo::cpuFreqMHz, DISPLAY_SPLASH_DURATION_MS, PlatformDetector::PlatformInfo::expectedPSRAM, PlatformDetector::PlatformInfo::flashSize, PlatformDetector::PlatformInfo::heapFree, PlatformDetector::PlatformInfo::heapSize, PlatformDetector::PlatformInfo::psramActuallyPresent, PlatformDetector::PlatformInfo::psramConfigured, PlatformDetector::PlatformInfo::psramFree, and PlatformDetector::PlatformInfo::psramSize.
Referenced by getPlatformSummary(), setup(), WiFiManager::setupOTARoutes(), and WiFiManager::validateFirmwareFilename().
getPlatformSummary()
String PlatformDetector::getPlatformSummary () static
Get concise platform summary string.
Generates concise platform summary string for web interfaces and displays.
Returns
Brief platform description for web interfaces
Utility function that creates compact, user-friendly platform identification suitable for web interfaces, status displays, and API responses. Provides essential hardware information in minimal space while maintaining clarity.
Summary Format Examples:
"Platform: ESP32 DevKit (No PSRAM) | No PSRAM"
"Platform: ESP32-S3 N8R2 (2MB PSRAM) | PSRAM: 2MB"
"Platform: ESP32-S3 N16R8 (8MB PSRAM) | PSRAM: 8MB"
"Platform: ESP32-C3 Unknown | No PSRAM"
Information Components:
Chip name identification (ESP32, ESP32-S3, etc.)
Board variant classification (N8, N8R2, N16R8, DevKit)
PSRAM status and capacity (if present)
Compact formatting suitable for constrained display space
Returns
String Formatted platform summary for display purposes
Note
Uses detectPlatform() internally for current hardware analysis
PSRAM capacity displayed in MB units for readability
String format optimized for web UI status displays
Consistent formatting across all supported platforms
Suitable for JSON API responses and embedded displays
See also
detectPlatform() for comprehensive platform information
printPlatformInfo() for detailed diagnostic output
PlatformInfo for complete hardware specification structure
Since
v0.9
Definition at line 332 of file platform_detector.cpp.
References PlatformDetector::PlatformInfo::boardVariant, PlatformDetector::PlatformInfo::chipName, detectPlatform(), DISPLAY_SPLASH_DURATION_MS, PlatformDetector::PlatformInfo::psramActuallyPresent, and PlatformDetector::PlatformInfo::psramSize.
Referenced by WiFiManager::setupNormalModeRoutes().
printPlatformInfo()
void PlatformDetector::printPlatformInfo (const PlatformInfo & info) static
Print comprehensive platform information to log.
Outputs comprehensive platform detection results via logging system.
Parameters
info Platform information to display
Formatted display function that presents complete hardware platform analysis through the centralized logging infrastructure. Provides structured output ideal for system diagnostics, development debugging, and user support.
Output Information Categories:
Chip identification (model, cores, frequency)
Board variant classification and memory configuration
Flash memory capacity and heap statistics
PSRAM configuration status and functional verification
Platform compatibility assessment and optimization recommendations
PSRAM Status Reporting:
CONFIGURED BUT NOT DETECTED: Hardware mismatch indication
DETECTED AND FUNCTIONAL: Optimal configuration confirmation
NOT CONFIGURED: ESP32 Classic mode identification
Compatibility Assessment:
OPTIMAL: Hardware matches chip expectations (S3 with PSRAM, ESP32 without)
SUBOPTIMAL: Configuration mismatch requiring attention
Parameters
info Platform information structure from detectPlatform()
Note
Requires INFO level logging for standard output visibility
Uses WARNING level for hardware mismatch conditions
All output tagged with "PLATFORM" for easy log filtering
Memory sizes displayed in user-friendly MB/KB units
Compatibility status guides optimal system configuration
See also
detectPlatform() for platform information collection
Logger::infof() for formatted logging output mechanism
Logger::warnf() for hardware mismatch warnings
Since
v0.9
Definition at line 191 of file platform_detector.cpp.
References PlatformDetector::PlatformInfo::boardVariant, PlatformDetector::PlatformInfo::chipName, PlatformDetector::PlatformInfo::cpuCores, PlatformDetector::PlatformInfo::cpuFreqMHz, PlatformDetector::PlatformInfo::expectedPSRAM, PlatformDetector::PlatformInfo::flashSize, PlatformDetector::PlatformInfo::heapFree, PlatformDetector::PlatformInfo::heapSize, LOG_INFOF, LOG_WARNF, PlatformDetector::PlatformInfo::psramActuallyPresent, PlatformDetector::PlatformInfo::psramConfigured, PlatformDetector::PlatformInfo::psramFree, PlatformDetector::PlatformInfo::psramSize, and TAG.
Referenced by setup().
testPSRAMAllocation()
bool PlatformDetector::testPSRAMAllocation () static
Test PSRAM allocation and functionality.
Performs comprehensive PSRAM functionality testing and validation.
Returns
true if PSRAM tests pass (or not applicable)
Advanced testing function that validates PSRAM hardware functionality through systematic allocation tests across multiple memory sizes. Essential for confirming PSRAM reliability before production deployment and memory-intensive operations.
Test Methodology:
PSRAM presence verification via psramFound()
Progressive allocation testing (1KB → 256KB)
Memory write pattern validation (0xAA test pattern)
Boundary condition verification (first/last byte integrity)
Proper memory deallocation and cleanup
Success rate calculation and reporting
Test Allocation Sizes:
1KB: Small allocation baseline
4KB: Page-size allocation testing
16KB: Medium buffer validation
64KB: Large buffer capability
256KB: Maximum typical allocation test
Returns
true if all PSRAM tests pass or not applicable for platform
false if PSRAM configured but tests fail
Note
Only executes when BOARD_HAS_PSRAM compile flag is enabled
Uses heap_caps_malloc() with MALLOC_CAP_SPIRAM for PSRAM-specific allocation
Test pattern 0xAA provides reliable write/read verification
Boundary testing ensures full allocation integrity
All test results logged with detailed size and status information
Non-PSRAM platforms return true (not considered an error condition)
See also
detectPlatform() for PSRAM configuration detection
printPlatformInfo() for PSRAM status reporting
heap_caps_malloc() for PSRAM-specific memory allocation
Since
v0.9
Definition at line 256 of file platform_detector.cpp.
References DISPLAY_SPLASH_DURATION_MS, LOG_ERRORF, LOG_INFOF, LOG_WARNF, and TAG.
Referenced by setup().
Field Documentation
TAG
const char * PlatformDetector::TAG = "PLATFORM" static private
Logging tag.
Definition at line 85 of file platform_detector.h.
Referenced by printPlatformInfo(), and testPSRAMAllocation().
The documentation for this class was generated from the following files:
include/platform_detector.h
src/platform_detector.cpp