Dual Display Billboard: SettingsManager Class Reference
SettingsManager Class Reference
Comprehensive configuration persistence and management system with hardware integration.
#include <settings_manager.h>
Public Member Functions
SettingsManager ()
Constructor - initializes settings with default values.
bool begin ()
Initialize settings manager and load all configurations from storage.
void setDisplayManager (DisplayManager *dm)
Set DisplayManager reference for immediate brightness hardware application.
void setSecondDisplayEnabled (bool enabled)
Enable or disable the second display.
bool isSecondDisplayEnabled ()
Get current second display enable state.
void setDCCEnabled (bool enabled)
Enable or disable DCC interface functionality.
bool isDCCEnabled ()
Get current DCC interface enable state.
void setDCCAddress (int address)
Set DCC decoder address for command filtering.
int getDCCAddress ()
Get current DCC decoder address.
void setDCCPin (int pin)
Set GPIO pin for DCC signal input.
int getDCCPin ()
Get current DCC GPIO pin setting.
void setImageInterval (int seconds)
Set image slideshow interval.
int getImageInterval ()
Get current image slideshow interval.
void setImageEnabled (bool enabled)
Enable or disable image slideshow functionality.
bool isImageEnabled ()
Get current image slideshow enable state.
void setBrightness (int value)
Set display brightness level with immediate hardware application.
int getBrightness ()
Get current display brightness level.
void setClockEnabled (bool enabled)
Enable or disable clock display functionality.
bool isClockEnabled ()
Get current clock display enable state.
void setClockFace (ClockFaceType faceType)
Set clock face display type.
ClockFaceType getClockFace ()
Get current clock face type setting.
void printSettings ()
Print complete settings summary to logger.
void resetToDefaults ()
Reset all settings to factory default values.
String getSettingsJson ()
Get settings summary as JSON string for web interface.
int validateAndCorrectSettings ()
Validate and clamp setting values to acceptable ranges.
bool areAllSettingsFilesPersistent ()
Check if all settings files exist in persistent storage.
Private Member Functions
bool saveBoolean (const char *filename, bool value)
Save boolean value to LittleFS file.
bool loadBoolean (const char *filename, bool defaultValue)
Load boolean value from LittleFS file with fallback default.
bool saveInteger (const char *filename, int value)
Save integer value to LittleFS file.
int loadInteger (const char *filename, int defaultValue)
Load integer value from LittleFS file with fallback default.
Private Attributes
bool secondDisplayEnabled
Current second display enable state.
bool dccEnabled
Current DCC interface enable state.
int dccAddress
Current DCC address (1-10239)
int dccPin
Current DCC GPIO pin number.
int imageInterval
Current image interval in seconds.
bool imageEnabled
Current image slideshow enable state.
int brightness
Current display brightness (0-255)
bool clockEnabled
Current clock display enable state.
ClockFaceType clockFace
Current clock face type selection.
DisplayManager * displayManager
Optional DisplayManager reference for immediate hardware updates.
Static Private Attributes
static const char * SECOND_DISPLAY_FILE = "/second_display.txt"
Persistent storage file paths for individual settings.
static const char * DCC_ENABLED_FILE = "/dcc_enabled.txt"
DCC interface enable state file.
static const char * DCC_ADDRESS_FILE = "/dcc_address.txt"
DCC address configuration file.
static const char * DCC_PIN_FILE = "/dcc_pin.txt"
DCC GPIO pin configuration file.
static const char * IMAGE_INTERVAL_FILE = "/image_interval.txt"
Image slideshow interval file.
static const char * IMAGE_ENABLED_FILE = "/image_enabled.txt"
Image display enable state file.
static const char * BRIGHTNESS_FILE = "/brightness.txt"
Display brightness setting file.
static const char * CLOCK_ENABLED_FILE = "/clock_enabled.txt"
Clock display enable state file.
static const char * CLOCK_FACE_FILE = "/clock_face.txt"
Clock face type configuration file.
Detailed Description
Comprehensive configuration persistence and management system with hardware integration.
Manages all system configuration settings with persistent storage using LittleFS. Provides type-safe accessors, automatic validation, real-time persistence, and immediate hardware application for all configurable aspects of the dual display billboard system.
Enhanced Features:
Optional DisplayManager integration for immediate brightness hardware control
Automatic brightness application based on second display enable state
Clean separation of configuration storage and hardware control responsibilities
Definition at line 45 of file settings_manager.h.
Constructor & Destructor Documentation
SettingsManager()
SettingsManager::SettingsManager ()
Constructor - initializes settings with default values.
Initialize SettingsManager with safe default configuration values for all system settings.
Sets up default configuration values for all settings. Actual values will be loaded from persistent storage during begin() initialization.
Sets conservative defaults that ensure stable system operation before loading persistent configuration from LittleFS.
The constructor establishes a known-good baseline configuration with safety-first defaults. All settings will be overridden by persistent storage during the begin() initialization sequence, but these defaults provide fallback values and ensure the system has valid configuration even if persistent storage is corrupted.
Default Configuration:
Second display: disabled (single display mode)
DCC interface: disabled (safety-first approach)
DCC address: 101 (standard range default)
DCC GPIO pin: 4 (safe pin choice)
Image interval: 10 seconds (reasonable slideshow speed)
Image slideshow: enabled (primary functionality)
Brightness: 200/255 (78% for comfortable viewing)
Clock display: disabled (compatibility mode)
Clock face: modern square (clean aesthetic)
DisplayManager: null (optional hardware integration)
Note
All settings are validated and corrected during begin() initialization
DisplayManager integration is optional and set via setDisplayManager()
Persistent storage values override these defaults when available
See also
begin() for complete initialization with persistent storage loading
setDisplayManager() for hardware integration setup
resetToDefaults() for restoring factory configuration
Since
v0.9
Definition at line 75 of file settings_manager.cpp.
References brightness, CLOCK_MODERN_SQUARE, clockEnabled, clockFace, dccAddress, dccEnabled, dccPin, displayManager, imageEnabled, imageInterval, and secondDisplayEnabled.
Member Function Documentation
areAllSettingsFilesPersistent()
bool SettingsManager::areAllSettingsFilesPersistent ()
Check if all settings files exist in persistent storage.
Check persistence completeness by verifying existence of all settings files in LittleFS storage for configuration integrity assessment.
Returns
true if all setting files exist, false if any are missing
Diagnostic method to verify the integrity of persistent storage and identify missing configuration files.
This method performs a comprehensive audit of the LittleFS filesystem to verify that all expected settings files exist, providing insight into configuration persistence integrity and potential file system issues. The method is useful for diagnostics, system health checks, and troubleshooting persistence problems.
Persistence Audit Process:
Checks existence of all 9 core settings files in LittleFS
Counts existing vs. expected files for completeness assessment
Logs debug information for missing files (detailed diagnostics)
Provides summary statistics for persistence health monitoring
Returns boolean status for automated health checking
Audited Settings Files:
SECOND_DISPLAY_FILE: dual display configuration
DCC_ENABLED_FILE: DCC interface enable state
DCC_ADDRESS_FILE: DCC decoder address
DCC_PIN_FILE: DCC GPIO pin configuration
IMAGE_INTERVAL_FILE: slideshow timing
IMAGE_ENABLED_FILE: slideshow enable state
BRIGHTNESS_FILE: display brightness level
CLOCK_ENABLED_FILE: clock display state
CLOCK_FACE_FILE: clock visual style
Returns
true if all settings files exist in persistent storage, false if any files are missing from LittleFS
Note
Performs read-only filesystem operations (no modifications)
Logs informational summary of persistence status
Logs debug details for each missing file
Safe to call frequently for health monitoring
Missing files are normal on first boot before settings are saved
See also
begin() for settings loading and file creation
resetToDefaults() for complete settings file creation
LittleFS filesystem for underlying storage implementation
Since
v0.9
Definition at line 1466 of file settings_manager.cpp.
References BRIGHTNESS_FILE, CLOCK_ENABLED_FILE, CLOCK_FACE_FILE, DCC_ADDRESS_FILE, DCC_ENABLED_FILE, DCC_PIN_FILE, DISPLAY_SPLASH_DURATION_MS, IMAGE_ENABLED_FILE, IMAGE_INTERVAL_FILE, LOG_DEBUGF, LOG_INFOF, SECOND_DISPLAY_FILE, and TAG.
begin()
bool SettingsManager::begin ()
Initialize settings manager and load all configurations from storage.
Initialize the SettingsManager by loading all configuration values from LittleFS persistent storage with automatic validation and correction of out-of-range values.
Loads all settings from LittleFS persistent storage. If any setting file doesn't exist, uses the default value and creates the file for future use. Should be called once during system startup after LittleFS initialization.
Returns
true if initialization successful, false if critical error occurred
Establishes complete system configuration state.
This method performs comprehensive initialization including loading all settings from individual LittleFS files, validating loaded values against acceptable ranges, automatically correcting any invalid values, and logging the complete system configuration for diagnostic purposes. The initialization process ensures robust system configuration regardless of persistent storage state.
Initialization Process:
Load all settings from LittleFS with fallback defaults
Validate and automatically correct out-of-range values
Save corrected values back to persistent storage
Log complete configuration state for diagnostics
Report successful initialization
Settings Loaded:
Second display enable/disable state
DCC interface configuration (enable, address, GPIO pin)
Image slideshow settings (interval, enable state)
Display brightness level
Clock display settings (enable state, face type)
Returns
true on successful initialization (always succeeds with fallback defaults)
Note
Automatically corrects invalid settings and reports correction count
All corrected values are immediately saved to persistent storage
Logs complete configuration state for system diagnostics
Safe to call multiple times (reloads configuration)
DisplayManager integration requires separate setDisplayManager() call
See also
setDisplayManager() for hardware integration after initialization
validateAndCorrectSettings() for automatic value correction
resetToDefaults() for factory reset functionality
printSettings() for diagnostic configuration display
Since
v0.9
Definition at line 133 of file settings_manager.cpp.
References brightness, BRIGHTNESS_FILE, CLOCK_ENABLED_FILE, CLOCK_FACE_FILE, CLOCK_MODERN_SQUARE, clockEnabled, clockFace, DCC_ADDRESS_FILE, DCC_ENABLED_FILE, DCC_PIN_FILE, dccAddress, dccEnabled, dccPin, DISPLAY_SPLASH_DURATION_MS, IMAGE_ENABLED_FILE, IMAGE_INTERVAL_FILE, imageEnabled, imageInterval, loadBoolean(), loadInteger(), LOG_INFO, LOG_INFOF, saveBoolean(), saveInteger(), SECOND_DISPLAY_FILE, secondDisplayEnabled, TAG, and validateAndCorrectSettings().
Referenced by loop().
getBrightness()
int SettingsManager::getBrightness ()
Get current display brightness level.
Query the current display brightness level for hardware control and user interface feedback.
Returns
Current brightness setting (0-255)
This method provides access to the current display brightness configuration, which is used for hardware PWM control, user interface display, and system state reporting. The value represents the PWM duty cycle for backlight control.
Returns
Brightness level (0-255) where 0=off, 255=maximum brightness
Note
Returns the current in-memory brightness value (no file system access)
Value is loaded from persistent storage during begin() initialization
Used by DisplayManager for PWM hardware control
Thread-safe for read access
Value range is validated during configuration (setBrightness)
Can be converted to percentage: (value / 255.0f) * 100.0f
See also
setBrightness() for configuring brightness with validation and hardware application
begin() for initialization from persistent storage
setDisplayManager() for hardware integration setup
DisplayManager::setBrightness() for underlying PWM hardware control
Since
v0.9
Definition at line 819 of file settings_manager.cpp.
References brightness.
Referenced by WiFiManager::setupNormalModeRoutes().
getClockFace()
ClockFaceType SettingsManager::getClockFace ()
Get current clock face type setting.
Query the current clock face visual style for time display rendering and user interface configuration.
Returns
Current clock face type selection
This method provides access to the configured clock face type that determines the visual style for time display when clock functionality is enabled. The face type is used by the DisplayClockManager for selecting appropriate rendering methods and visual layouts.
Returns
ClockFaceType enumeration value representing current visual style
Note
Returns the current in-memory face type value (no file system access)
Face type is loaded from persistent storage during begin() initialization
Used by DisplayClockManager for time display style selection
Thread-safe for read access
Face type determines visual layout and rendering approach for time display
See also
setClockFace() for configuring clock face visual style
begin() for initialization from persistent storage
setClockEnabled() for enabling/disabling clock display
isClockEnabled() for querying clock display state
ClockFaceType enumeration for available visual styles
DisplayClockManager for time display rendering with face type
Since
v0.9
Definition at line 964 of file settings_manager.cpp.
References clockFace.
Referenced by WiFiManager::setupNormalModeRoutes(), and SlideshowManager::showClock().
getDCCAddress()
int SettingsManager::getDCCAddress ()
Get current DCC decoder address.
Query the current Digital Command Control (DCC) decoder address for model railroad command filtering and system configuration.
Returns
Current DCC address setting
This method provides access to the configured DCC decoder address that determines which DCC commands the billboard system will respond to from model railroad control systems. The address is used by the DCCManager for command filtering and processing.
Returns
DCC decoder address (1-10239) for command reception and filtering
Note
Returns the current in-memory address value (no file system access)
Address is loaded from persistent storage during begin() initialization
Used by DCCManager for command filtering and address matching
Thread-safe for read access
Address range is validated during configuration (setDCCAddress)
See also
setDCCAddress() for configuring DCC decoder address with validation
begin() for initialization from persistent storage
isDCCEnabled() for DCC interface enable state
getDCCPin() for DCC input GPIO pin configuration
DCCManager for DCC command processing and address filtering
Since
v0.9
Definition at line 490 of file settings_manager.cpp.
References dccAddress.
Referenced by DCCManager::begin(), and WiFiManager::setupNormalModeRoutes().
getDCCPin()
int SettingsManager::getDCCPin ()
Get current DCC GPIO pin setting.
Query the current Digital Command Control (DCC) input GPIO pin for hardware initialization and signal processing setup.
Returns
Current DCC GPIO pin number
This method provides access to the configured ESP32 GPIO pin that will be used for DCC signal reception from model railroad control systems. The pin is used by the DCCManager during initialization for interrupt setup and signal decoding configuration.
Returns
ESP32 GPIO pin number (0-39) configured for DCC signal input
Note
Returns the current in-memory pin value (no file system access)
Pin is loaded from persistent storage during begin() initialization
Used by DCCManager for interrupt setup and signal processing
Thread-safe for read access
Pin range is validated during configuration (setDCCPin)
Consider pin usage conflicts with other system peripherals
See also
setDCCPin() for configuring DCC input GPIO pin with validation
begin() for initialization from persistent storage
isDCCEnabled() for DCC interface enable state
getDCCAddress() for DCC decoder address configuration
DCCManager for DCC signal decoding and interrupt handling
Since
v0.9
Definition at line 566 of file settings_manager.cpp.
References dccPin.
Referenced by DCCManager::begin(), and WiFiManager::setupNormalModeRoutes().
getImageInterval()
int SettingsManager::getImageInterval ()
Get current image slideshow interval.
Query the current automatic image slideshow interval timing for display management and transition scheduling.
Returns
Current interval in seconds between image changes
This method provides access to the configured time interval between automatic image transitions in the billboard slideshow system. The interval is used by the SlideshowManager for scheduling image advancement and timing calculations.
Returns
Image display interval in seconds (1-3600) for slideshow timing
Note
Returns the current in-memory interval value (no file system access)
Interval is loaded from persistent storage during begin() initialization
Used by SlideshowManager for automatic image transition timing
Thread-safe for read access
Interval range is validated during configuration (setImageInterval)
Value is used in millisecond calculations for precise timing control
See also
setImageInterval() for configuring slideshow interval with validation
begin() for initialization from persistent storage
setImageEnabled() for enabling/disabling automatic slideshow
isImageEnabled() for querying slideshow enable state
SlideshowManager for automatic image transition management
Since
v0.9
Definition at line 644 of file settings_manager.cpp.
References imageInterval.
Referenced by WiFiManager::setupNormalModeRoutes(), SlideshowManager::shouldRetrySlideshow(), and SlideshowManager::updateSlideshow().
getSettingsJson()
String SettingsManager::getSettingsJson ()
Get settings summary as JSON string for web interface.
Export all current system settings as a JSON string for API responses, debugging, and configuration backup purposes.
Returns
JSON formatted string containing all current settings
Provides a structured JSON representation of all settings suitable for web interface display or API responses.
This method creates a comprehensive JSON representation of all current system settings, providing both machine-readable configuration data and human-friendly formatted values. The JSON output is suitable for web API responses, debugging output, configuration backup, and system integration.
JSON Structure and Content:
Complete settings coverage (all configurable parameters)
Boolean values as JSON boolean primitives (true/false)
Integer values as JSON number primitives
Additional computed fields (brightnessPercent for convenience)
Compact single-line format for efficient transmission
Standards-compliant JSON for broad compatibility
Included Settings:
secondDisplayEnabled: boolean display configuration
dccEnabled: boolean DCC interface state
dccAddress: integer DCC decoder address (1-10239)
dccPin: integer ESP32 GPIO pin (0-39)
imageInterval: integer slideshow timing in seconds
imageEnabled: boolean slideshow enable state
brightness: integer PWM value (0-255)
brightnessPercent: float percentage value for UI display
clockEnabled: boolean clock display state
clockFace: integer clock face type enumeration
Returns
String containing complete JSON representation of all settings
Note
Returns current in-memory values (no file system access)
JSON is compact single-line format (no pretty printing)
brightnessPercent is computed from brightness for convenience
Safe to call frequently for status reporting
Compatible with standard JSON parsers and web APIs
See also
printSettings() for human-readable diagnostic output
resetToDefaults() for factory configuration restoration
begin() for settings loading and initialization
Since
v0.9
Definition at line 1332 of file settings_manager.cpp.
References brightness, clockEnabled, clockFace, dccAddress, dccEnabled, dccPin, DISPLAY_SPLASH_DURATION_MS, imageEnabled, imageInterval, and secondDisplayEnabled.
isClockEnabled()
bool SettingsManager::isClockEnabled ()
Get current clock display enable state.
Query the current clock display enable/disable state for time display management and content rotation logic.
Returns
true if clock display is enabled, false if disabled
This method provides access to the current clock display configuration state, which determines whether the billboard system will include time display in its content rotation. The state is used by the DisplayClockManager for conditional time rendering and content scheduling.
Returns
true if clock/time display is enabled, false if time display is disabled (content-only mode)
Note
Returns the current in-memory state (no file system access)
Value is loaded from persistent storage during begin() initialization
Used by DisplayClockManager for conditional time display rendering
Thread-safe for read access
When false, time display is excluded from billboard content rotation
See also
setClockEnabled() for configuring clock display state
begin() for initialization from persistent storage
setClockFace() for configuring clock visual style
getClockFace() for querying current clock face type
DisplayClockManager for time display rendering
Since
v0.9
Definition at line 893 of file settings_manager.cpp.
References clockEnabled.
Referenced by WiFiManager::setupNormalModeRoutes(), and SlideshowManager::updateSlideshow().
isDCCEnabled()
bool SettingsManager::isDCCEnabled ()
Get current DCC interface enable state.
Query the current Digital Command Control (DCC) interface enable/disable state for model railroad integration and system initialization logic.
Returns
true if DCC interface is enabled, false if disabled
This method provides access to the current DCC interface configuration state, which determines whether the billboard system will initialize DCC decoder functionality for model railroad command reception. The state is used by the DCCManager during system startup to conditionally enable DCC features.
Returns
true if DCC interface is enabled for model railroad integration, false if DCC functionality is disabled
Note
Returns the current in-memory state (no file system access)
Value is loaded from persistent storage during begin() initialization
Used by DCCManager during system startup for conditional initialization
Thread-safe for read access
DCC functionality also requires valid address and pin configuration
See also
setDCCEnabled() for configuring DCC interface state
begin() for initialization from persistent storage
getDCCAddress() for DCC decoder address configuration
getDCCPin() for DCC input GPIO pin configuration
DCCManager for DCC command processing implementation
Since
v0.9
Definition at line 415 of file settings_manager.cpp.
References dccEnabled.
Referenced by DCCManager::begin(), and WiFiManager::setupNormalModeRoutes().
isImageEnabled()
bool SettingsManager::isImageEnabled ()
Get current image slideshow enable state.
Query the current automatic image slideshow enable/disable state for display management and transition control logic.
Returns
true if image slideshow is enabled, false if disabled
This method provides access to the current slideshow configuration state, which determines whether the billboard system will automatically cycle through images or require manual control. The state is used by the SlideshowManager for conditional automatic image advancement.
Returns
true if automatic image slideshow is enabled, false if slideshow is disabled (manual control only)
Note
Returns the current in-memory state (no file system access)
Value is loaded from persistent storage during begin() initialization
Used by SlideshowManager for conditional automatic image transitions
Thread-safe for read access
When false, images must be changed manually or through external control
See also
setImageEnabled() for configuring slideshow enable state
begin() for initialization from persistent storage
setImageInterval() for configuring automatic transition timing
getImageInterval() for querying current slideshow interval
SlideshowManager for automatic image transition management
Since
v0.9
Definition at line 714 of file settings_manager.cpp.
References imageEnabled.
Referenced by loop(), and WiFiManager::setupNormalModeRoutes().
isSecondDisplayEnabled()
bool SettingsManager::isSecondDisplayEnabled ()
Get current second display enable state.
Query the current second display enable/disable state for system configuration and display management logic.
Returns
true if second display is enabled, false if disabled
This method provides access to the current second display configuration state, which is used throughout the system for display-aware operations including brightness control, image rendering, and clock display management.
Returns
true if second display is enabled (dual display mode), false if disabled (single display mode)
Note
Returns the current in-memory state (no file system access)
Value is loaded from persistent storage during begin() initialization
Used by other system components for display-aware operations
Thread-safe for read access
See also
setSecondDisplayEnabled() for configuring second display state
begin() for initialization from persistent storage
DisplayManager integration for hardware-aware operations
Since
v0.9
Definition at line 341 of file settings_manager.cpp.
References secondDisplayEnabled.
Referenced by loop(), and WiFiManager::setupNormalModeRoutes().
loadBoolean()
bool SettingsManager::loadBoolean (const char * filename, bool defaultValue) private
Load boolean value from LittleFS file with fallback default.
Load boolean setting value from LittleFS persistent storage with default value fallback and comprehensive error handling.
Parameters
filename Source file path for loading
defaultValue Default value if file doesn't exist or read fails
Returns
Loaded boolean value or default if unavailable
This private helper method handles the low-level file I/O operations for loading boolean configuration values from the LittleFS filesystem. The method provides robust error handling, default value fallback, and standardized logging for all boolean settings throughout the SettingsManager system.
Loading Logic:
Returns default value if file does not exist (first boot scenario)
Returns default value if file cannot be opened (I/O error recovery)
Parses text content as "true" for boolean true, everything else false
Automatic string trimming for whitespace tolerance
Safe fallback behavior for corrupted or invalid files
Parameters
filename Constant string pointer to the source filename for loading
defaultValue Boolean default value to return on file error or absence
Returns
Boolean setting value from file, or defaultValue on any error condition
Note
Private method for internal SettingsManager use only
Logs debug messages for missing files and warnings for I/O errors
Uses LittleFS read mode "r" (read-only access)
File handle is properly closed after operation
Thread-safe through LittleFS filesystem operations
Only explicit "true" string evaluates to boolean true
See also
saveBoolean() for corresponding write operation
loadInteger() for integer value loading
LittleFS filesystem for underlying storage implementation
Since
v0.9
Definition at line 1157 of file settings_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, LOG_DEBUGF, LOG_WARNF, and TAG.
Referenced by begin().
loadInteger()
int SettingsManager::loadInteger (const char * filename, int defaultValue) private
Load integer value from LittleFS file with fallback default.
Load integer setting value from LittleFS persistent storage with default value fallback and robust parsing with error handling.
Parameters
filename Source file path for loading
defaultValue Default value if file doesn't exist or read fails
Returns
Loaded integer value or default if unavailable
This private helper method handles the low-level file I/O operations for loading integer configuration values from the LittleFS filesystem. The method provides comprehensive error handling, default value fallback, input validation, and standardized logging for all integer settings throughout the SettingsManager.
Loading and Parsing Logic:
Returns default value if file does not exist (first boot scenario)
Returns default value if file cannot be opened (I/O error recovery)
Parses text content as decimal integer with String.toInt()
Validates parsing success (toInt() returns 0 for invalid strings)
Handles edge case where "0" is valid but other invalid strings also return 0
Automatic string trimming for whitespace tolerance
Safe fallback behavior for corrupted or invalid files
Parameters
filename Constant string pointer to the source filename for loading
defaultValue Integer default value to return on file error, absence, or parsing failure
Returns
Integer setting value from file, or defaultValue on any error condition
Note
Private method for internal SettingsManager use only
Logs debug messages for missing files and warnings for I/O or parsing errors
Uses LittleFS read mode "r" (read-only access)
File handle is properly closed after operation
Thread-safe through LittleFS filesystem operations
Distinguishes between valid "0" and invalid string parsing
See also
saveInteger() for corresponding write operation
loadBoolean() for boolean value loading
LittleFS filesystem for underlying storage implementation
Since
v0.9
Definition at line 1259 of file settings_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, LOG_DEBUGF, LOG_WARNF, and TAG.
Referenced by begin().
printSettings()
void SettingsManager::printSettings ()
Print complete settings summary to logger.
Display comprehensive system settings summary for diagnostics and configuration verification purposes.
Outputs all current setting values to the logging system for diagnostic and debugging purposes. Useful for system status checks.
This method outputs a formatted summary of all current system settings to the logging system, providing a complete overview of the billboard's configuration state. The output includes all configurable parameters with their current values and states for debugging and verification.
Settings Summary Output:
Second display configuration (enabled/disabled)
DCC interface settings (enabled/disabled, address, GPIO pin)
Image slideshow configuration (interval, enabled/disabled)
Display brightness (absolute value and percentage)
Clock display settings (enabled/disabled, face type)
Formatted with emoji icons for easy visual identification
Note
Outputs to LOG_INFO level for standard diagnostic visibility
DCC details only shown when DCC interface is enabled
Clock face type only shown when clock display is enabled
Brightness displayed as both raw value (0-255) and percentage
Safe to call frequently for status monitoring
See also
begin() for initialization logging
getSettingsJson() for machine-readable settings export
resetToDefaults() for factory reset functionality
Since
v0.9
Definition at line 1001 of file settings_manager.cpp.
References brightness, clockEnabled, clockFace, dccAddress, dccEnabled, dccPin, imageEnabled, imageInterval, LOG_INFO, LOG_INFOF, secondDisplayEnabled, and TAG.
resetToDefaults()
void SettingsManager::resetToDefaults ()
Reset all settings to factory default values.
Reset all system settings to factory default values with immediate persistence and comprehensive validation.
Restores all configuration settings to their default values and saves them to persistent storage. Use with caution as this will overwrite all user customizations.
This method restores the entire billboard system configuration to factory default values, providing a complete reset functionality for troubleshooting, initial setup, or configuration recovery. All settings are immediately validated and saved to persistent storage with proper error handling.
Factory Default Values:
Second Display: enabled (dual display mode)
DCC Interface: disabled (standalone operation)
DCC Address: 101 (standard accessory decoder range)
DCC GPIO Pin: 4 (safe ESP32 input pin)
Image Interval: 10 seconds (balanced slideshow timing)
Image Slideshow: enabled (automatic image cycling)
Brightness: 200 (78% of maximum, good visibility)
Clock Display: disabled (image-focused content)
Clock Face: Modern Square (clean digital style)
Reset Process Features:
Immediate application of all default values
Complete persistence to LittleFS storage
Validation and error handling for each setting
Hardware integration when DisplayManager is available
Comprehensive logging for reset verification
Note
All settings are immediately saved to persistent storage
Hardware brightness is applied immediately when DisplayManager is integrated
Reset operation is atomic (all settings changed together)
Logs comprehensive reset confirmation for diagnostics
Safe to call multiple times (idempotent operation)
See also
printSettings() for verification of reset values
begin() for default value documentation
setDisplayManager() for hardware integration after reset
Since
v0.9
Definition at line 1058 of file settings_manager.cpp.
References CLOCK_MODERN_SQUARE, LOG_INFO, setBrightness(), setClockEnabled(), setClockFace(), setDCCAddress(), setDCCEnabled(), setDCCPin(), setImageEnabled(), setImageInterval(), setSecondDisplayEnabled(), and TAG.
saveBoolean()
bool SettingsManager::saveBoolean (const char * filename, bool value) private
Save boolean value to LittleFS file.
Save boolean setting value to LittleFS persistent storage with error handling and logging for configuration persistence.
Parameters
filename Target file path for storage
value Boolean value to save
Returns
true if save successful, false otherwise
This private helper method handles the low-level file I/O operations for saving boolean configuration values to the LittleFS filesystem. The method provides standardized error handling and logging for all boolean settings throughout the SettingsManager system.
Storage Format:
Boolean values stored as text strings ("true" or "false")
Simple text format for easy debugging and manual editing
Atomic write operation with proper file handle management
Automatic file creation if not exists
Parameters
filename Constant string pointer to the target filename for storage
value Boolean value to be saved (true or false)
Returns
true if save operation was successful, false if file I/O error occurred
Note
Private method for internal SettingsManager use only
Logs error messages for failed file operations
Uses LittleFS write mode "w" (create/overwrite)
File handle is properly closed after operation
Thread-safe through LittleFS filesystem operations
See also
loadBoolean() for corresponding read operation
saveInteger() for integer value storage
LittleFS filesystem for underlying storage implementation
Since
v0.9
Definition at line 1111 of file settings_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, LOG_ERRORF, and TAG.
Referenced by begin(), setClockEnabled(), setDCCEnabled(), setImageEnabled(), and setSecondDisplayEnabled().
saveInteger()
bool SettingsManager::saveInteger (const char * filename, int value) private
Save integer value to LittleFS file.
Save integer setting value to LittleFS persistent storage with error handling and logging for numerical configuration persistence.
Parameters
filename Target file path for storage
value Integer value to save
Returns
true if save successful, false otherwise
This private helper method handles the low-level file I/O operations for saving integer configuration values to the LittleFS filesystem. The method provides standardized error handling and logging for all integer settings throughout the SettingsManager system.
Storage Format:
Integer values stored as decimal text strings
Simple text format for easy debugging and manual editing
Atomic write operation with proper file handle management
Automatic file creation if not exists
No validation (validation performed at higher level)
Parameters
filename Constant string pointer to the target filename for storage
value Integer value to be saved (any valid int range)
Returns
true if save operation was successful, false if file I/O error occurred
Note
Private method for internal SettingsManager use only
Logs error messages for failed file operations
Uses LittleFS write mode "w" (create/overwrite)
File handle is properly closed after operation
Thread-safe through LittleFS filesystem operations
Value validation should be performed before calling this method
See also
loadInteger() for corresponding read operation
saveBoolean() for boolean value storage
LittleFS filesystem for underlying storage implementation
Since
v0.9
Definition at line 1211 of file settings_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, LOG_ERRORF, and TAG.
Referenced by begin(), setBrightness(), setClockFace(), setDCCAddress(), setDCCPin(), setImageInterval(), and validateAndCorrectSettings().
setBrightness()
void SettingsManager::setBrightness (int value)
Set display brightness level with immediate hardware application.
Configure display brightness with PWM validation, persistent storage, and immediate hardware application for billboard display control.
Parameters
value Brightness level (0-255, where 0=minimum, 255=maximum)
Controls the overall brightness of both displays. Values are automatically clamped to the valid range of 0-255. Setting is persisted immediately to storage and, if DisplayManager is available, applied immediately to hardware respecting the current second display enable setting.
This method sets the display brightness level for the billboard system with automatic hardware application when DisplayManager is integrated. The brightness value controls the PWM backlight intensity for both single and dual display configurations, providing immediate visual feedback and persistent storage.
Brightness Control Features:
Validates brightness against PWM hardware limits (0-255)
Automatically clamps out-of-range values to valid PWM limits
Immediate hardware application when DisplayManager is integrated
Display-aware application (single vs dual display configurations)
Persistent storage for brightness retention across system restarts
Hardware Integration Behavior:
When second display enabled: applies brightness to both displays
When second display disabled: applies to main display, turns off second
Immediate PWM adjustment provides real-time brightness feedback
Coordinates with display configuration for proper hardware state
Parameters
value Brightness level (0-255) where 0=off, 255=maximum brightness
Note
Brightness is immediately validated and saved to LittleFS persistent storage
Out-of-range values are automatically clamped to PWM limits (0-255)
Hardware brightness is applied immediately when DisplayManager is integrated
Logs save operation success/failure and validation warnings for diagnostics
Display configuration awareness ensures proper dual display management
See also
getBrightness() for querying current brightness level
setDisplayManager() for hardware integration setup
setSecondDisplayEnabled() for display configuration control
DisplayManager::setBrightness() for underlying PWM hardware control
Since
v0.9
Definition at line 759 of file settings_manager.cpp.
References brightness, BRIGHTNESS_FILE, DISPLAY_SPLASH_DURATION_MS, displayManager, DisplayManager::isSplashActive(), LOG_DEBUG, LOG_INFO, LOG_INFOF, LOG_WARN, LOG_WARNF, saveInteger(), secondDisplayEnabled, DisplayManager::setBrightness(), and TAG.
Referenced by resetToDefaults(), and WiFiManager::setupNormalModeRoutes().
setClockEnabled()
void SettingsManager::setClockEnabled (bool enabled)
Enable or disable clock display functionality.
Configure clock display enable/disable state with persistent storage for billboard time display functionality.
Parameters
enabled true to enable clock display, false to disable
When enabled, clock faces can be displayed instead of or alongside the image slideshow, depending on system configuration.
This method controls whether the billboard system will display clock/time information as part of its content rotation. When enabled, the system will show the current time using the configured clock face style, providing useful time information to viewers.
Clock Display Features:
Enables/disables time display functionality for billboard content
Automatically saves configuration to persistent storage for system restarts
Coordinates with clock face type configuration for complete time display
Used by DisplayClockManager for conditional time rendering
Parameters
enabled true to enable clock/time display functionality, false to disable time display (content-only mode)
Note
Setting is immediately saved to LittleFS persistent storage
Changes take effect immediately for clock display behavior
Logs save operation success/failure for diagnostics
Safe to call repeatedly with same value (no unnecessary file operations)
When disabled, time display is excluded from content rotation
See also
isClockEnabled() for querying current clock display state
setClockFace() for configuring clock visual style
getClockFace() for querying current clock face type
DisplayClockManager for time display rendering
Since
v0.9
Definition at line 858 of file settings_manager.cpp.
References CLOCK_ENABLED_FILE, clockEnabled, LOG_INFOF, LOG_WARN, saveBoolean(), and TAG.
Referenced by resetToDefaults(), and WiFiManager::setupNormalModeRoutes().
setClockFace()
void SettingsManager::setClockFace (ClockFaceType faceType)
Set clock face display type.
Configure clock face visual style with type validation and persistent storage for billboard time display customization.
Parameters
faceType Clock face type from ClockFaceType enumeration
Selects which style of clock face to display when clock mode is active. Available types defined in clock_types.h header file.
This method sets the visual style/type for clock display when time functionality is enabled. Different clock face types provide various visual presentations of time information, allowing customization of the billboard's time display to match different aesthetic preferences or visibility requirements.
Clock Face Type Features:
Supports multiple visual styles defined in ClockFaceType enumeration
Modern square, analog, digital, and other display formats
Automatically saves configuration to persistent storage for system restarts
Used by DisplayClockManager for time rendering style selection
Type safety through ClockFaceType enumeration
Parameters
faceType Clock face visual style from ClockFaceType enumeration
Note
Face type is immediately saved to LittleFS persistent storage
Changes take effect immediately for next clock display update
Logs save operation success/failure for diagnostics
Safe to call repeatedly with same value (no unnecessary file operations)
Face type determines visual layout and rendering style for time display
See also
getClockFace() for querying current clock face type
setClockEnabled() for enabling/disabling clock display
isClockEnabled() for querying clock display state
ClockFaceType enumeration for available visual styles
DisplayClockManager for time display rendering with face type
Since
v0.9
Definition at line 929 of file settings_manager.cpp.
References CLOCK_FACE_FILE, clockFace, DISPLAY_SPLASH_DURATION_MS, LOG_INFOF, LOG_WARN, saveInteger(), and TAG.
Referenced by resetToDefaults(), and WiFiManager::setupNormalModeRoutes().
setDCCAddress()
void SettingsManager::setDCCAddress (int address)
Set DCC decoder address for command filtering.
Configure Digital Command Control (DCC) decoder address for model railroad command reception with NMRA standards validation and persistence.
Parameters
address DCC address (typically 1-10239, standard range 1-127)
Sets the DCC address that this device will respond to. Only DCC commands sent to this address will be processed by the system.
This method sets the DCC decoder address that the billboard system will respond to when receiving commands from model railroad control systems. The address determines which DCC commands will be processed by the billboard, allowing multiple devices to coexist on the same DCC bus with unique addresses.
DCC Address Standards and Validation:
Validates against NMRA DCC standards (valid range: 1-10239)
Short addresses: 1-127 (most commonly used for accessories)
Long addresses: 128-10239 (extended addressing for complex layouts)
Automatically clamps out-of-range values to valid limits
Logs validation warnings when address correction is required
Parameters
address DCC decoder address (1-10239) for command reception
Note
Address is immediately validated and saved to LittleFS persistent storage
Out-of-range addresses are automatically clamped to valid limits (1-10239)
Changes take effect after system restart when DCC hardware is initialized
Logs save operation success/failure and validation warnings for diagnostics
Address 1 is used as default fallback for invalid values below range
See also
getDCCAddress() for querying current DCC decoder address
setDCCEnabled() for enabling/disabling DCC interface
setDCCPin() for configuring DCC input GPIO pin
DCCManager for DCC command processing and address filtering
Since
v0.9
Definition at line 450 of file settings_manager.cpp.
References DCC_ADDRESS_FILE, dccAddress, DISPLAY_SPLASH_DURATION_MS, LOG_INFOF, LOG_WARN, LOG_WARNF, saveInteger(), and TAG.
Referenced by resetToDefaults(), DCCManager::setAddress(), and WiFiManager::setupNormalModeRoutes().
setDCCEnabled()
void SettingsManager::setDCCEnabled (bool enabled)
Enable or disable DCC interface functionality.
Configure Digital Command Control (DCC) interface enable/disable state for model railroad integration with persistent storage and validation.
Parameters
enabled true to enable DCC interface, false to disable
Controls whether the system listens for DCC commands. When enabled, the system will monitor the configured GPIO pin for DCC signals.
This method controls the DCC interface functionality for model railroad integration, enabling the billboard system to respond to DCC commands from model railroad control systems. When enabled, the system will initialize the DCC decoder functionality using the configured address and GPIO pin.
DCC Integration Features:
Enables/disables DCC command reception from model railroad control systems
Automatically saves configuration to persistent storage for system restarts
Validates DCC interface state for proper model railroad integration
Coordinates with DCC address and pin configuration for complete setup
Parameters
enabled true to enable DCC interface for model railroad integration, false to disable DCC functionality
Note
Setting is immediately saved to LittleFS persistent storage
DCC functionality requires additional configuration of address and GPIO pin
Changes take effect after system restart when DCC hardware is initialized
Logs save operation success/failure for diagnostics
Safe to call repeatedly with same value (no unnecessary file operations)
See also
isDCCEnabled() for querying current DCC interface state
setDCCAddress() for configuring DCC decoder address
setDCCPin() for configuring DCC input GPIO pin
DCCManager for underlying DCC command processing
Since
v0.9
Definition at line 380 of file settings_manager.cpp.
References DCC_ENABLED_FILE, dccEnabled, LOG_INFOF, LOG_WARN, saveBoolean(), and TAG.
Referenced by resetToDefaults(), DCCManager::setEnabled(), and WiFiManager::setupNormalModeRoutes().
setDCCPin()
void SettingsManager::setDCCPin (int pin)
Set GPIO pin for DCC signal input.
Configure Digital Command Control (DCC) input GPIO pin for signal reception with ESP32 hardware validation and persistent storage.
Parameters
pin GPIO pin number for DCC signal reception
Configures which GPIO pin will be used to receive DCC signals. Should be a pin capable of interrupt-driven input detection.
This method sets the ESP32 GPIO pin that will be used to receive DCC signals from model railroad control systems. The pin must be capable of digital input and interrupt handling for proper DCC signal timing and decoding.
ESP32 GPIO Pin Validation and Constraints:
Validates pin range against ESP32 hardware capabilities (0-39)
Automatically clamps out-of-range values to valid GPIO limits
Default fallback to pin 4 for invalid low values (reliable input pin)
Logs validation warnings when pin correction is required
Some pins have hardware restrictions (input-only, boot-sensitive, etc.)
Parameters
pin ESP32 GPIO pin number (0-39) for DCC signal input
Note
Pin is immediately validated and saved to LittleFS persistent storage
Out-of-range pins are automatically clamped to valid ESP32 GPIO range
Changes take effect after system restart when DCC hardware is initialized
Pin 4 is used as default fallback for invalid values below range
Logs save operation success/failure and validation warnings for diagnostics
Consider pin usage conflicts with display SPI, I2C, or other peripherals
See also
getDCCPin() for querying current DCC input GPIO pin
setDCCEnabled() for enabling/disabling DCC interface
setDCCAddress() for configuring DCC decoder address
DCCManager for DCC signal decoding and interrupt handling
Since
v0.9
Definition at line 525 of file settings_manager.cpp.
References DCC_PIN_FILE, dccPin, DISPLAY_SPLASH_DURATION_MS, LOG_INFOF, LOG_WARN, LOG_WARNF, saveInteger(), and TAG.
Referenced by resetToDefaults(), DCCManager::setPin(), and WiFiManager::setupNormalModeRoutes().
setDisplayManager()
void SettingsManager::setDisplayManager (DisplayManager * dm)
Set DisplayManager reference for immediate brightness hardware application.
Integrate DisplayManager hardware interface for immediate brightness control and automatic hardware state management.
Parameters
dm Pointer to DisplayManager instance for hardware control integration
Optional integration allowing SettingsManager to immediately apply brightness changes to hardware when setBrightness() is called. This eliminates the need for separate configuration storage and hardware application calls.
Enables real-time application of brightness settings to display hardware.
This method establishes integration with the DisplayManager to provide immediate hardware control capabilities. When integrated, brightness changes are instantly applied to the appropriate displays based on the second display configuration. The method also immediately applies current brightness settings to hardware upon integration.
Integration Features:
Immediate brightness application on settings changes
Automatic dual/single display brightness management
Hardware state synchronization with configuration
Optional integration (can be disabled by passing nullptr)
Hardware Application Logic:
If second display enabled: applies brightness to both displays
If second display disabled: applies brightness to main display, turns off second
Immediate application of current brightness settings upon integration
Parameters
dm Pointer to DisplayManager instance for hardware integration, or nullptr to disable
Note
Integration is optional - SettingsManager functions without DisplayManager
Immediately applies current brightness settings to hardware when integrated
Brightness changes are applied in real-time when DisplayManager is integrated
Can be called multiple times to change or disable integration
Safe to pass nullptr to disable hardware integration
See also
setBrightness() for brightness control with immediate hardware application
setSecondDisplayEnabled() for display configuration with hardware control
DisplayManager::setBrightness() for underlying hardware control method
Since
v0.9
Definition at line 238 of file settings_manager.cpp.
References brightness, DISPLAY_SPLASH_DURATION_MS, displayManager, LOG_DEBUG, LOG_INFO, secondDisplayEnabled, and TAG.
Referenced by loop().
setImageEnabled()
void SettingsManager::setImageEnabled (bool enabled)
Enable or disable image slideshow functionality.
Configure automatic image slideshow enable/disable state with persistent storage for billboard display control.
Parameters
enabled true to enable image slideshow, false to disable
When disabled, the system will not display images and may show alternative content like clocks or static displays.
This method controls whether the billboard system will automatically cycle through images in the slideshow sequence. When enabled, the system will automatically transition between images using the configured interval timing. When disabled, images must be changed manually or through external control.
Slideshow Control Features:
Enables/disables automatic image cycling for billboard displays
Automatically saves configuration to persistent storage for system restarts
Coordinates with image interval timing for complete slideshow management
Used by SlideshowManager for conditional automatic advancement
Parameters
enabled true to enable automatic image slideshow cycling, false to disable automatic transitions (manual control only)
Note
Setting is immediately saved to LittleFS persistent storage
Changes take effect immediately for slideshow behavior
Logs save operation success/failure for diagnostics
Safe to call repeatedly with same value (no unnecessary file operations)
When disabled, current image remains displayed until manually changed
See also
isImageEnabled() for querying current slideshow enable state
setImageInterval() for configuring automatic transition timing
getImageInterval() for querying current slideshow interval
SlideshowManager for automatic image transition management
Since
v0.9
Definition at line 679 of file settings_manager.cpp.
References IMAGE_ENABLED_FILE, imageEnabled, LOG_INFOF, LOG_WARN, saveBoolean(), and TAG.
Referenced by resetToDefaults(), and WiFiManager::setupNormalModeRoutes().
setImageInterval()
void SettingsManager::setImageInterval (int seconds)
Set image slideshow interval.
Configure automatic image slideshow interval timing with validation and persistent storage for billboard display management.
Parameters
seconds Time in seconds between image transitions
Controls how long each image is displayed before transitioning to the next image in the slideshow sequence.
This method sets the time interval between automatic image transitions in the billboard slideshow system. The interval determines how long each image is displayed before automatically advancing to the next image in the sequence.
Interval Validation and Constraints:
Validates interval range for practical slideshow operation (1-3600 seconds)
Minimum 1 second prevents excessive CPU usage and display flicker
Maximum 1 hour (3600 seconds) prevents excessively long static displays
Automatically clamps out-of-range values to valid limits
Logs validation warnings when interval correction is required
Parameters
seconds Image display interval in seconds (1-3600)
Note
Interval is immediately validated and saved to LittleFS persistent storage
Out-of-range intervals are automatically clamped to valid limits (1-3600)
Changes take effect immediately for next image transition
Logs save operation success/failure and validation warnings for diagnostics
Used by SlideshowManager for automatic image advancement timing
See also
getImageInterval() for querying current slideshow interval
setImageEnabled() for enabling/disabling automatic slideshow
isImageEnabled() for querying slideshow enable state
SlideshowManager for automatic image transition management
Since
v0.9
Definition at line 604 of file settings_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, IMAGE_INTERVAL_FILE, imageInterval, LOG_INFOF, LOG_WARN, LOG_WARNF, saveInteger(), and TAG.
Referenced by resetToDefaults(), and WiFiManager::setupNormalModeRoutes().
setSecondDisplayEnabled()
void SettingsManager::setSecondDisplayEnabled (bool enabled)
Enable or disable the second display.
Configure second display enable/disable state with persistent storage and immediate hardware brightness application.
Parameters
enabled true to enable second display, false to disable
Immediately saves the setting to persistent storage. When disabled, the second display will not be initialized or updated.
Controls dual display functionality for the billboard system.
This method manages the second display configuration with complete persistence and immediate hardware integration. When the second display state changes, the method automatically adjusts brightness application to match the new configuration, ensuring proper hardware state synchronization.
Hardware Integration Behavior:
When enabled: applies current brightness to both displays
When disabled: applies brightness to main display only, turns off second display
Immediate hardware state synchronization when DisplayManager is integrated
Parameters
enabled true to enable second display functionality, false for single display mode
Note
Setting is immediately saved to LittleFS persistent storage
Hardware brightness is automatically adjusted when DisplayManager is integrated
Safe to call repeatedly with same value (no unnecessary operations)
Logs save operation success/failure for diagnostics
See also
isSecondDisplayEnabled() for querying current second display state
setDisplayManager() for hardware integration setup
setBrightness() for brightness control with display awareness
DisplayManager::setBrightness() for underlying hardware control
Since
v0.9
Definition at line 294 of file settings_manager.cpp.
References brightness, displayManager, DisplayManager::isSplashActive(), LOG_DEBUG, LOG_INFO, LOG_INFOF, LOG_WARN, saveBoolean(), SECOND_DISPLAY_FILE, secondDisplayEnabled, DisplayManager::setBrightness(), and TAG.
Referenced by resetToDefaults(), and WiFiManager::setupNormalModeRoutes().
validateAndCorrectSettings()
int SettingsManager::validateAndCorrectSettings ()
Validate and clamp setting values to acceptable ranges.
Validate and automatically correct all loaded settings values to ensure they fall within acceptable ranges with persistence and logging.
Performs validation on all current settings and corrects any values that are outside acceptable ranges. Useful for data integrity checks.
Returns
Number of settings that were corrected
This method performs comprehensive validation of all loaded configuration values against their respective valid ranges and hardware constraints. When out-of-range values are detected, they are automatically corrected to safe limits and immediately saved back to persistent storage to prevent repeated corrections on future boots.
Validation Rules and Corrections:
DCC Address: 1-10239 (NMRA standards), corrected to boundaries
DCC GPIO Pin: 0-39 (ESP32 hardware), corrected to safe values
Image Interval: 1-3600 seconds, corrected to practical limits
Brightness: 0-255 (PWM range), corrected to hardware limits
Boolean settings: inherently valid (no correction needed)
Clock face enumeration: no range validation (enum safety)
Correction Process:
Identifies each out-of-range value with logging
Applies appropriate boundary clamping logic
Immediately saves corrected value to persistent storage
Counts total corrections for diagnostic reporting
Provides detailed logging for each correction applied
Returns
Integer count of settings that required correction and were fixed
Note
Called automatically during begin() initialization
Corrections are immediately persisted to prevent repeat corrections
Logs warning messages for each correction applied
Returns 0 when all settings are within valid ranges
Uses conservative safe values for boundary corrections
See also
begin() for automatic validation during initialization
resetToDefaults() for complete configuration reset
printSettings() for verification of corrected values
Since
v0.9
Definition at line 1386 of file settings_manager.cpp.
References brightness, BRIGHTNESS_FILE, DCC_ADDRESS_FILE, DCC_PIN_FILE, dccAddress, dccPin, DISPLAY_SPLASH_DURATION_MS, IMAGE_INTERVAL_FILE, imageInterval, LOG_WARNF, saveInteger(), and TAG.
Referenced by begin().
Field Documentation
brightness
int SettingsManager::brightness private
Current display brightness (0-255)
Definition at line 72 of file settings_manager.h.
Referenced by begin(), getBrightness(), getSettingsJson(), printSettings(), setBrightness(), setDisplayManager(), setSecondDisplayEnabled(), SettingsManager(), and validateAndCorrectSettings().
BRIGHTNESS_FILE
const char * SettingsManager::BRIGHTNESS_FILE = "/brightness.txt" static private
Display brightness setting file.
Definition at line 58 of file settings_manager.h.
Referenced by areAllSettingsFilesPersistent(), begin(), setBrightness(), and validateAndCorrectSettings().
CLOCK_ENABLED_FILE
const char * SettingsManager::CLOCK_ENABLED_FILE = "/clock_enabled.txt" static private
Clock display enable state file.
Definition at line 59 of file settings_manager.h.
Referenced by areAllSettingsFilesPersistent(), begin(), and setClockEnabled().
CLOCK_FACE_FILE
const char * SettingsManager::CLOCK_FACE_FILE = "/clock_face.txt" static private
Clock face type configuration file.
Definition at line 60 of file settings_manager.h.
Referenced by areAllSettingsFilesPersistent(), begin(), and setClockFace().
clockEnabled
bool SettingsManager::clockEnabled private
Current clock display enable state.
Definition at line 73 of file settings_manager.h.
Referenced by begin(), getSettingsJson(), isClockEnabled(), printSettings(), setClockEnabled(), and SettingsManager().
clockFace
ClockFaceType SettingsManager::clockFace private
Current clock face type selection.
Definition at line 74 of file settings_manager.h.
Referenced by begin(), getClockFace(), getSettingsJson(), printSettings(), setClockFace(), and SettingsManager().
DCC_ADDRESS_FILE
const char * SettingsManager::DCC_ADDRESS_FILE = "/dcc_address.txt" static private
DCC address configuration file.
Definition at line 54 of file settings_manager.h.
Referenced by areAllSettingsFilesPersistent(), begin(), setDCCAddress(), and validateAndCorrectSettings().
DCC_ENABLED_FILE
const char * SettingsManager::DCC_ENABLED_FILE = "/dcc_enabled.txt" static private
DCC interface enable state file.
Definition at line 53 of file settings_manager.h.
Referenced by areAllSettingsFilesPersistent(), begin(), and setDCCEnabled().
DCC_PIN_FILE
const char * SettingsManager::DCC_PIN_FILE = "/dcc_pin.txt" static private
DCC GPIO pin configuration file.
Definition at line 55 of file settings_manager.h.
Referenced by areAllSettingsFilesPersistent(), begin(), setDCCPin(), and validateAndCorrectSettings().
dccAddress
int SettingsManager::dccAddress private
Current DCC address (1-10239)
Definition at line 68 of file settings_manager.h.
Referenced by begin(), getDCCAddress(), getSettingsJson(), printSettings(), setDCCAddress(), SettingsManager(), and validateAndCorrectSettings().
dccEnabled
bool SettingsManager::dccEnabled private
Current DCC interface enable state.
Definition at line 67 of file settings_manager.h.
Referenced by begin(), getSettingsJson(), isDCCEnabled(), printSettings(), setDCCEnabled(), and SettingsManager().
dccPin
int SettingsManager::dccPin private
Current DCC GPIO pin number.
Definition at line 69 of file settings_manager.h.
Referenced by begin(), getDCCPin(), getSettingsJson(), printSettings(), setDCCPin(), SettingsManager(), and validateAndCorrectSettings().
displayManager
DisplayManager* SettingsManager::displayManager private
Optional DisplayManager reference for immediate hardware updates.
Definition at line 77 of file settings_manager.h.
Referenced by setBrightness(), setDisplayManager(), setSecondDisplayEnabled(), and SettingsManager().
IMAGE_ENABLED_FILE
const char * SettingsManager::IMAGE_ENABLED_FILE = "/image_enabled.txt" static private
Image display enable state file.
Definition at line 57 of file settings_manager.h.
Referenced by areAllSettingsFilesPersistent(), begin(), and setImageEnabled().
IMAGE_INTERVAL_FILE
const char * SettingsManager::IMAGE_INTERVAL_FILE = "/image_interval.txt" static private
Image slideshow interval file.
Definition at line 56 of file settings_manager.h.
Referenced by areAllSettingsFilesPersistent(), begin(), setImageInterval(), and validateAndCorrectSettings().
imageEnabled
bool SettingsManager::imageEnabled private
Current image slideshow enable state.
Definition at line 71 of file settings_manager.h.
Referenced by begin(), getSettingsJson(), isImageEnabled(), printSettings(), setImageEnabled(), and SettingsManager().
imageInterval
int SettingsManager::imageInterval private
Current image interval in seconds.
Definition at line 70 of file settings_manager.h.
Referenced by begin(), getImageInterval(), getSettingsJson(), printSettings(), setImageInterval(), SettingsManager(), and validateAndCorrectSettings().
SECOND_DISPLAY_FILE
const char * SettingsManager::SECOND_DISPLAY_FILE = "/second_display.txt" static private
Persistent storage file paths for individual settings.
Second display enable state file
Definition at line 52 of file settings_manager.h.
Referenced by areAllSettingsFilesPersistent(), begin(), and setSecondDisplayEnabled().
secondDisplayEnabled
bool SettingsManager::secondDisplayEnabled private
Current second display enable state.
Definition at line 66 of file settings_manager.h.
Referenced by begin(), getSettingsJson(), isSecondDisplayEnabled(), printSettings(), setBrightness(), setDisplayManager(), setSecondDisplayEnabled(), and SettingsManager().
The documentation for this class was generated from the following files:
include/settings_manager.h
src/settings_manager.cpp