Dual Display Billboard: TextUtils Class Reference
TextUtils Class Reference
Unicode text rendering utilities.
#include <text_utils.h>
Static Public Member Functions
static int drawUnicodeText (TFT_eSPI &tft, const String &text, int x, int y, uint16_t color=TFT_WHITE)
Render Unicode text string at specified position.
static int getUnicodeTextWidth (TFT_eSPI &tft, const String &text)
Calculate pixel width of Unicode text string.
static String toDisplayText (const String &input)
Convert international characters to display-ready text.
static String transliterateText (const String &input)
Convert international characters to ASCII fallback text.
Static Private Member Functions
static const UnicodeGlyph * findGlyph (uint16_t codepoint)
Find glyph data for Unicode codepoint.
static uint16_t getNextUTF8Char (const String &text, int &index)
Get next UTF-8 character from string.
static void drawGlyph (TFT_eSPI &tft, const UnicodeGlyph *glyph, int x, int y, uint16_t color)
Draw individual Unicode glyph.
static String toASCIIFallback (const String &text)
Fallback to ASCII substitution if Unicode glyph not available.
Detailed Description
Unicode text rendering utilities.
Definition at line 36 of file text_utils.h.
Member Function Documentation
drawGlyph()
void TextUtils::drawGlyph (TFT_eSPI & tft, const UnicodeGlyph * glyph, int x, int y, uint16_t color) static private
Draw individual Unicode glyph.
Parameters
tft TFT display instance
glyph Glyph to draw
x X position
y Y position
color Color to use
Definition at line 341 of file text_utils.cpp.
References UnicodeGlyph::bitmap, and DISPLAY_SPLASH_DURATION_MS.
Referenced by drawUnicodeText().
drawUnicodeText()
int TextUtils::drawUnicodeText (TFT_eSPI & tft, const String & text, int x, int y, uint16_t color = TFT_WHITE) static
Render Unicode text string at specified position.
Parameters
tft TFT display instance
text UTF-8 encoded text string
x X position for text start
y Y position for text baseline
color Text color
Returns
Width of rendered text in pixels
Draw Unicode text string on TFT display with platform-specific adjustments
Definition at line 144 of file text_utils.cpp.
References DISPLAY_SPLASH_DURATION_MS, drawGlyph(), findGlyph(), FONT_WIDTH, and getNextUTF8Char().
Referenced by DisplayClockManager::displayClockOnDisplay().
findGlyph()
const UnicodeGlyph * TextUtils::findGlyph (uint16_t codepoint) static private
Find glyph data for Unicode codepoint.
Find glyph for Unicode codepoint.
Parameters
codepoint Unicode codepoint to find
Returns
Pointer to glyph data or nullptr if not found
Definition at line 279 of file text_utils.cpp.
References DISPLAY_SPLASH_DURATION_MS, GLYPH_COUNT, and unicode_glyphs.
Referenced by drawUnicodeText(), getUnicodeTextWidth(), and transliterateText().
getNextUTF8Char()
uint16_t TextUtils::getNextUTF8Char (const String & text, int & index) static private
Get next UTF-8 character from string.
Parameters
text Text string
index Current index (will be updated)
Returns
Unicode codepoint
Definition at line 291 of file text_utils.cpp.
References DISPLAY_SPLASH_DURATION_MS.
Referenced by drawUnicodeText(), getUnicodeTextWidth(), and transliterateText().
getUnicodeTextWidth()
int TextUtils::getUnicodeTextWidth (TFT_eSPI & tft, const String & text) static
Calculate pixel width of Unicode text string.
Parameters
tft TFT display instance for accurate font measurements
text UTF-8 encoded text string
Returns
Total width in pixels
Definition at line 197 of file text_utils.cpp.
References DISPLAY_SPLASH_DURATION_MS, findGlyph(), and getNextUTF8Char().
Referenced by DisplayClockManager::displayClockOnDisplay().
toASCIIFallback()
static String TextUtils::toASCIIFallback (const String & text) static private
Fallback to ASCII substitution if Unicode glyph not available.
Parameters
text Input text
Returns
ASCII equivalent text
toDisplayText()
String TextUtils::toDisplayText (const String & input) static
Convert international characters to display-ready text.
Alias for transliterateText - for compatibility.
Parameters
input Input string that may contain international characters
Returns
String ready for display (Unicode rendering or ASCII fallback)
Definition at line 272 of file text_utils.cpp.
References DISPLAY_SPLASH_DURATION_MS.
Referenced by DisplayClockManager::displayClockOnDisplay().
transliterateText()
String TextUtils::transliterateText (const String & input) static
Convert international characters to ASCII fallback text.
Convert international characters to display-ready text.
Parameters
input Input string that may contain international characters
Returns
String with ASCII substitutions
Definition at line 229 of file text_utils.cpp.
References DISPLAY_SPLASH_DURATION_MS, findGlyph(), and getNextUTF8Char().
The documentation for this class was generated from the following files:
include/text_utils.h
src/text_utils.cpp