Dual Display Billboard: DisplayManager Class Reference
DisplayManager Class Reference
Dual TFT display hardware controller.
#include <display_manager.h>
Public Member Functions
DisplayManager ()
Constructor initializes DisplayManager with uninitialized hardware state.
bool begin ()
🚀 Initializes complete dual display hardware system
void selectDisplay (int displayNum)
🖥️ Selects the active display for operations
void selectDisplayForText (int displayNum)
📝 Selects display with text-optimized rotation
void selectDisplayForImage (int displayNum)
Selects display with image-optimized rotation.
void deselectAll ()
Deactivates all displays by setting chip select lines HIGH.
void clearBothDisplaysToBlack ()
Clears both displays to black and turns off backlight.
void setBrightness (uint8_t brightness, int displayNum=0)
Sets backlight brightness for specified display(s)
void fillScreen (uint16_t color, int displayNum=0)
Fills entire screen(s) with specified color.
void drawText (const char *text, int x, int y, uint16_t color, int displayNum)
Draws text on specified display at given coordinates.
void drawColorBitmap (int16_t x, int16_t y, const uint16_t *bitmap, int16_t w, int16_t h, int displayNum=0)
Draws RGB565 color bitmap stored in PROGMEM.
void drawColorBitmapRotated (int16_t x, int16_t y, const uint16_t *bitmap, int16_t w, int16_t h, int displayNum=0)
Draws RGB565 color bitmap with 270-degree rotation.
void showSplashScreen (int displayNum=0, unsigned long timeoutMs=2000)
Displays splash screen on specified display(s) with timeout.
void updateSplashScreen ()
bool isSplashActive ()
Returns the current splash screen activation state.
void enableSecondDisplay (bool enable)
Enables or disables the second display.
void alternateDisplays ()
Alternates color display between two screens at timed intervals.
void showPortalInfo (const String &ssid, const String &ip, const String &status)
Displays comprehensive portal configuration information.
void showPortalSequence (const String &ssid, const String &ip, const String &status)
Initiates splash-to-portal sequence with automatic transition.
void showQuickStatus (const String &message, uint16_t color)
Displays quick status message on first display.
void showAPStarting ()
Displays AP starting notification on primary display.
void showAPReady ()
Displays AP ready notification on primary display.
void showConnecting ()
Displays WiFi connection attempt notification.
void showConnectionSuccess (const String &ip)
Displays WiFi connection success confirmation.
TFT_eSPI * getTFT (int displayNum=1)
Provides TFT library access for external components.
void setRotation (uint8_t rotation)
Sets rotation for all displays and TFT instance.
String getDisplayType () const
Returns the hardware display type string.
uint16_t getDisplayWidth () const
Returns the display width in pixels.
uint16_t getDisplayHeight () const
Returns the display height in pixels.
Private Member Functions
void initializeBacklight ()
Initializes PWM backlight control for both displays.
void initializeCS ()
Initializes chip select (CS) pins for dual display control.
void initializeTFT ()
Initializes TFT library with dual display configuration.
Private Attributes
TFT_eSPI tft
TFT_eSPI library instance.
bool initialized
Initialization status flag.
uint8_t brightness1
uint8_t brightness2
Brightness levels (0-255)
unsigned long splashStartTime
Splash screen start timestamp.
bool splashActive
Splash screen active status.
unsigned long splashTimeoutMs
Splash timeout duration.
bool portalSequenceActive
Portal connection sequence status.
String pendingSSID
String pendingIP
String pendingStatus
Connection details for display.
Static Private Attributes
static const int firstScreenCS = DISPLAY_CS1_PIN
Primary display CS pin.
static const int secondScreenCS = DISPLAY_CS2_PIN
Secondary display CS pin.
static const int TFT_DC_PIN = DISPLAY_DC_PIN
DC pin (shared)
static const int TFT_BACKLIGHT1_PIN = DISPLAY_BLK1_PIN
Backlight 1 pin.
static const int TFT_BACKLIGHT2_PIN = DISPLAY_BLK2_PIN
Backlight 2 pin.
Detailed Description
Dual TFT display hardware controller.
Manages hardware interfacing for dual ST7735 displays with:
Independent chip select (CS) pin control
PWM brightness control for each display
Content-specific rotation management
Synchronized display operations
Hardware abstraction for different ESP32 variants
Definition at line 52 of file display_manager.h.
Constructor & Destructor Documentation
DisplayManager()
DisplayManager::DisplayManager ()
Constructor initializes DisplayManager with uninitialized hardware state.
Sets default brightness values and initialization status flag. Hardware configuration and actual initialization must be performed by begin() execution.
See also
begin() for complete hardware initialization sequence
initializeBacklight() for PWM brightness configuration
Since
v0.9
Definition at line 18 of file display_manager.cpp.
Member Function Documentation
alternateDisplays()
void DisplayManager::alternateDisplays ()
Alternates color display between two screens at timed intervals.
Automatically switches between displays, filling the first with blue and the second with yellow at regular intervals. Uses static variables to maintain state between calls. Primarily used for testing or demo modes.
The alternation cycle:
Display 1: Blue background
Display 2: Yellow background
Repeat after DISPLAY_ALTERNATING_INTERVAL_MS milliseconds
Note
Uses static variables to track timing and current display
Logging is commented out to reduce log spam during continuous operation
Interval controlled by DISPLAY_ALTERNATING_INTERVAL_MS constant
See also
selectDisplay() for display activation
fillScreen() for color fill operations
deselectAll() for display deactivation
Since
v0.9
Definition at line 544 of file display_manager.cpp.
References deselectAll(), DISPLAY_ALTERNATING_INTERVAL_MS, DISPLAY_SPLASH_DURATION_MS, selectDisplay(), and tft.
Referenced by loop().
begin()
bool DisplayManager::begin ()
🚀 Initializes complete dual display hardware system
Performs comprehensive hardware initialization sequence for dual ST7735/ST7789 displays. Configures PWM backlight control, chip select pins, TFT interface, and immediately clears both displays to prevent visual artifacts during startup.
Initialization Sequence:
💡 Backlight PWM configuration (5kHz, 8-bit resolution)
📌 Chip select pin setup with safe deselect state
🖥️ TFT library initialization with dual CS method
⚫ Immediate display clearing to prevent startup flash
Hardware Requirements: • ESP32/ESP32-S3 with sufficient GPIO pins • Dual ST7735 or ST7789 TFT displays • Independent backlight control circuits • Proper SPI wiring with shared MOSI/MISO/SCK
Returns
true Always returns true for compatibility
Note
Sets initialized flag to true upon successful completion
Both displays set to maximum brightness (255) by default
Warning
Requires proper hardware connections as defined in display_hardware_config.h
See also
initializeBacklight() for PWM backlight setup details
initializeCS() for chip select pin configuration
initializeTFT() for TFT library setup process
Definition at line 52 of file display_manager.cpp.
References clearBothDisplaysToBlack(), initializeBacklight(), initializeCS(), initialized, initializeTFT(), and LOG_INFO.
Referenced by loop().
clearBothDisplaysToBlack()
void DisplayManager::clearBothDisplaysToBlack ()
Clears both displays to black and turns off backlight.
Initializes both displays to a completely dark state by filling the screen with black pixels and setting brightness to zero. This method is typically called during system startup or reset to ensure displays start from a known clean state.
The operation sequence:
Activates display 1, fills with black, sets brightness to 0
Activates display 2, fills with black, sets brightness to 0
Deactivates all displays
Note
Both screen content and backlight are cleared
Uses setBrightness(0) to turn off backlight completely
Ensures consistent startup state across both displays
See also
selectDisplay() for individual display activation
setBrightness() for backlight control
deselectAll() for display deactivation
Since
v0.9
Definition at line 340 of file display_manager.cpp.
References deselectAll(), DISPLAY_SPLASH_DURATION_MS, LOG_INFO, selectDisplay(), setBrightness(), and tft.
Referenced by begin().
deselectAll()
void DisplayManager::deselectAll ()
Deactivates all displays by setting chip select lines HIGH.
Sets both display chip select pins to HIGH state, effectively deselecting all displays. This ensures no display is active before selecting a new one and prevents potential conflicts between multiple displays.
Note
Called automatically by selectDisplay methods before activation
Both firstScreenCS and secondScreenCS pins set to HIGH
See also
selectDisplay() for display selection with automatic deselection
selectDisplayForText() for text-optimized display selection
selectDisplayForImage() for image-optimized display selection
Since
v0.9
Definition at line 312 of file display_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, firstScreenCS, and secondScreenCS.
Referenced by alternateDisplays(), clearBothDisplaysToBlack(), ImageManager::displayImage(), drawColorBitmap(), drawColorBitmapRotated(), drawText(), enableSecondDisplay(), fillScreen(), initializeTFT(), selectDisplayForImage(), selectDisplayForText(), setRotation(), WiFiManager::setupNormalModeRoutes(), WiFiManager::setupRoutes(), showConnectionSuccess(), showPortalInfo(), and showQuickStatus().
drawColorBitmap()
void DisplayManager::drawColorBitmap (int16_t x, int16_t y, const uint16_t * bitmap, int16_t w, int16_t h, int displayNum = 0)
Draws RGB565 color bitmap stored in PROGMEM.
Renders a color bitmap stored in program memory (PROGMEM) pixel by pixel. Each pixel is read using pgm_read_word() and drawn individually to support bitmaps that exceed available RAM capacity.
Parameters
x Top-left X coordinate for bitmap placement
y Top-left Y coordinate for bitmap placement
bitmap Pointer to RGB565 bitmap data in PROGMEM
w Bitmap width in pixels
h Bitmap height in pixels
displayNum Target display number (1 or 2)
Note
Uses pgm_read_word() for PROGMEM access
Pixel-by-pixel drawing may be slow for large bitmaps
Display is automatically selected and deselected
Bitmap must be in RGB565 format
See also
drawColorBitmapRotated() for rotated bitmap rendering
selectDisplay() for display activation
deselectAll() for display deactivation
Since
v0.9
Definition at line 839 of file display_manager.cpp.
References deselectAll(), DISPLAY_SPLASH_DURATION_MS, selectDisplay(), and tft.
drawColorBitmapRotated()
void DisplayManager::drawColorBitmapRotated (int16_t x, int16_t y, const uint16_t * bitmap, int16_t w, int16_t h, int displayNum = 0)
Draws RGB565 color bitmap with 270-degree rotation.
Renders a color bitmap with automatic 270-degree clockwise rotation to correct orientation issues. Each pixel is transformed during rendering to achieve the rotation effect without requiring pre-rotated bitmap data.
Rotation transformation:
Original pixel at (i,j) becomes pixel at (h-1-j, i)
Effectively rotates 270 degrees clockwise
Corrects upside-down bitmap display issues
Parameters
x Top-left X coordinate for rotated bitmap placement
y Top-left Y coordinate for rotated bitmap placement
bitmap Pointer to RGB565 bitmap data in PROGMEM
w Original bitmap width in pixels (before rotation)
h Original bitmap height in pixels (before rotation)
displayNum Target display number (1 or 2)
Note
Final bitmap dimensions will be h×w after rotation
Uses pgm_read_word() for PROGMEM access
Display is automatically selected and deselected
Slower than non-rotated version due to coordinate transformation
See also
drawColorBitmap() for non-rotated bitmap rendering
selectDisplay() for display activation
deselectAll() for display deactivation
Since
v0.9
Definition at line 885 of file display_manager.cpp.
References deselectAll(), DISPLAY_SPLASH_DURATION_MS, selectDisplay(), and tft.
Referenced by showSplashScreen().
drawText()
void DisplayManager::drawText (const char * text, int x, int y, uint16_t color, int displayNum)
Draws text on specified display at given coordinates.
Renders text string at specified pixel coordinates using the TFT library. Automatically handles display selection and deselection for safe operation. Uses basic text rendering with standard size and specified color.
Parameters
text Null-terminated string to display
x Horizontal pixel coordinate (0 = left edge)
y Vertical pixel coordinate (0 = top edge)
color 16-bit RGB565 text color
displayNum Target display number (1 or 2)
Note
Uses fixed text size of 1 for consistent rendering
Text may wrap or clip if coordinates exceed display bounds
Display is automatically selected and deselected
See also
selectDisplay() for display activation
deselectAll() for display deactivation
fillScreen() for clearing display before text
Since
v0.9
Definition at line 483 of file display_manager.cpp.
References deselectAll(), DISPLAY_SPLASH_DURATION_MS, selectDisplay(), and tft.
enableSecondDisplay()
void DisplayManager::enableSecondDisplay (bool enable)
Enables or disables the second display.
Controls the operational state of the second display. When disabled, the display is cleared to black to provide visual feedback. When enabled, the display becomes available for normal operations.
Parameters
enable True to enable second display, false to disable
Note
When disabled, second display is filled with black
Logging indicates current state change
Does not affect display hardware initialization
See also
selectDisplay() for display activation
fillScreen() for display clearing
deselectAll() for display deactivation
Since
v0.9
Definition at line 511 of file display_manager.cpp.
References deselectAll(), DISPLAY_SPLASH_DURATION_MS, LOG_INFO, selectDisplay(), and tft.
Referenced by loop().
fillScreen()
void DisplayManager::fillScreen (uint16_t color, int displayNum = 0)
Fills entire screen(s) with specified color.
Clears the display buffer and fills it with a solid color. Can target individual displays or both simultaneously. Automatically handles display selection and deselection for safe multi-display operation.
Parameters
color 16-bit RGB565 color value Common values: TFT_BLACK, TFT_WHITE, TFT_RED, TFT_GREEN, TFT_BLUE
displayNum Target display selection 0 = both displays (sequential operation) 1 = first display only 2 = second display only
Note
For displayNum=0, displays are filled sequentially, not simultaneously
Uses selectDisplay() for safe chip select management
Automatically calls deselectAll() after operation
See also
selectDisplay() for individual display activation
deselectAll() for display deactivation
clearBothDisplaysToBlack() for black fill with brightness control
Since
v0.9
Definition at line 445 of file display_manager.cpp.
References deselectAll(), DISPLAY_SPLASH_DURATION_MS, selectDisplay(), and tft.
Referenced by showSplashScreen(), and updateSplashScreen().
getDisplayHeight()
uint16_t DisplayManager::getDisplayHeight () const
Returns the display height in pixels.
Provides compile-time detection of display height based on hardware type. Different display types have different resolutions and this method returns the appropriate height for the configured hardware.
Returns
240 pixels for ST7789, 80 pixels for ST7735
Note
Determined at compile time via preprocessor definitions
Used for image scaling and layout calculations
See also
getDisplayWidth() for display width detection
getDisplayType() for hardware type identification
Since
v0.9
Definition at line 1124 of file display_manager.cpp.
getDisplayType()
String DisplayManager::getDisplayType () const
Returns the hardware display type string.
Provides compile-time detection of the display hardware type based on preprocessor definitions. Used for hardware-specific configuration and debugging information.
Returns
"ST7789" if DISPLAY_TYPE_ST7789 defined, "ST7735" otherwise
Note
Determined at compile time via preprocessor definitions
Used for hardware-specific optimizations and logging
See also
getDisplayWidth() for display width detection
getDisplayHeight() for display height detection
Since
v0.9
Definition at line 1074 of file display_manager.cpp.
getDisplayWidth()
uint16_t DisplayManager::getDisplayWidth () const
Returns the display width in pixels.
Provides compile-time detection of display width based on hardware type. Different display types have different resolutions and this method returns the appropriate width for the configured hardware.
Returns
240 pixels for ST7789, 160 pixels for ST7735
Note
Determined at compile time via preprocessor definitions
Used for image scaling and layout calculations
See also
getDisplayHeight() for display height detection
getDisplayType() for hardware type identification
Since
v0.9
Definition at line 1099 of file display_manager.cpp.
getTFT()
TFT_eSPI * DisplayManager::getTFT (int displayNum = 1)
Provides TFT library access for external components.
Returns a pointer to the internal TFT_eSPI instance for use by other components like ImageManager. The returned instance is shared between displays and requires proper display selection before use.
Parameters
displayNum Display number for validation (1 or 2)
Returns
Pointer to TFT_eSPI instance if displayNum valid, nullptr otherwise
Note
Caller must use selectDisplay() before TFT operations
Same TFT instance is shared between both displays
Display selection controls which screen receives commands
See also
selectDisplay() for proper display activation
selectDisplayForImage() for image-specific operations
Since
v0.9
Definition at line 1048 of file display_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, and tft.
Referenced by DisplayClockManager::displayClockOnBothDisplays(), ImageManager::displayImage(), WiFiManager::setupNormalModeRoutes(), WiFiManager::setupRoutes(), ImageManager::showNoImagesMessage(), and ImageManager::tft_output().
initializeBacklight()
void DisplayManager::initializeBacklight () private
Initializes PWM backlight control for both displays.
Configures hardware PWM channels for independent backlight brightness control. Each display has its own PWM channel with 5kHz frequency and 8-bit resolution providing smooth brightness control from 0 to 255.
Hardware Configuration:
Display 1: GPIO 22 on PWM Channel 1 (5kHz, 8-bit, full brightness)
Display 2: GPIO 27 on PWM Channel 2 (5kHz, 8-bit, full brightness)
Note
Both displays initialized to maximum brightness (255)
Uses ESP32 LEDC peripheral for PWM generation
Called automatically during begin() initialization
See also
setBrightness() for runtime brightness control
begin() for complete initialization sequence
Since
v0.9
Definition at line 87 of file display_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, LOG_INFO, TFT_BACKLIGHT1_PIN, and TFT_BACKLIGHT2_PIN.
Referenced by begin().
initializeCS()
void DisplayManager::initializeCS () private
Initializes chip select (CS) pins for dual display control.
Configures GPIO pins for individual display selection in dual display setup. Both pins are set to OUTPUT mode and initialized to HIGH (deselected state) to ensure safe starting condition before any display operations.
Hardware Pin Mapping:
First Display CS: GPIO 5 (firstScreenCS)
Second Display CS: GPIO 15 (secondScreenCS)
Note
Both CS pins start in deselected state (HIGH)
Called automatically during begin() initialization
Essential for preventing display conflicts in dual setup
See also
selectDisplay() for runtime display activation
deselectAll() for deactivating all displays
begin() for complete initialization sequence
Since
v0.9
Definition at line 136 of file display_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, firstScreenCS, LOG_INFO, and secondScreenCS.
Referenced by begin().
initializeTFT()
void DisplayManager::initializeTFT () private
Initializes TFT library with dual display configuration.
Performs TFT_eSPI library initialization using dual CS selection method. Both displays are temporarily selected during initialization to ensure proper hardware recognition, then immediately cleared and configured with correct rotation settings.
Initialization Sequence:
Select both displays (CS pins LOW)
Initialize TFT library
Clear initialization flash artifacts
Configure individual display rotations
Clear both displays to black
Deselect all displays
Note
Uses dual CS method for reliable initialization
Immediately clears displays to prevent visual artifacts
Sets rotation 0 for both displays as default
Called automatically during begin() initialization
See also
selectDisplay() for runtime display selection
begin() for complete initialization sequence
Since
v0.9
Definition at line 174 of file display_manager.cpp.
References deselectAll(), DISPLAY_SPLASH_DURATION_MS, firstScreenCS, LOG_INFO, secondScreenCS, selectDisplay(), and tft.
Referenced by begin().
isSplashActive()
bool DisplayManager::isSplashActive ()
Returns the current splash screen activation state.
Provides access to the internal splash screen state without modification. Used by other components to determine if splash screen is currently active and adjust behavior accordingly.
Returns
True if splash screen is currently active, false otherwise
Note
This is a read-only state query method
Splash state is managed by other display methods
See also
showSplashScreen() for splash activation
hideSplashScreen() for splash deactivation
Since
v0.9
Definition at line 623 of file display_manager.cpp.
References splashActive.
Referenced by loop(), SettingsManager::setBrightness(), and SettingsManager::setSecondDisplayEnabled().
selectDisplay()
void DisplayManager::selectDisplay (int displayNum)
🖥️ Selects the active display for operations
This method activates the specified display by controlling chip select (CS) lines and setting the appropriate rotation for text display. Acts as a convenience wrapper for backward compatibility, defaulting to text rotation.
Parameters
displayNum The display number to select (1 or 2)
Warning
⚠️ Deselects all displays first, then selects the target display
Note
📝 Uses text rotation (DISPLAY_TEXT_ROTATION) as default
See also
selectDisplayForText() for explicit text rotation
selectDisplayForImage() for image-specific rotation
deselectAll() for deactivating all displays
Since
v0.9
Definition at line 227 of file display_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, and selectDisplayForText().
Referenced by alternateDisplays(), clearBothDisplaysToBlack(), drawColorBitmap(), drawColorBitmapRotated(), drawText(), enableSecondDisplay(), fillScreen(), initializeTFT(), setRotation(), WiFiManager::setupNormalModeRoutes(), WiFiManager::setupRoutes(), showConnectionSuccess(), ImageManager::showNoImagesMessage(), showPortalInfo(), and showQuickStatus().
selectDisplayForImage()
void DisplayManager::selectDisplayForImage (int displayNum)
Selects display with image-optimized rotation.
Activates the specified display and configures it for optimal image rendering by setting the image rotation (DISPLAY_IMAGE_ROTATION). This method ensures images are displayed in their correct orientation for viewing.
Parameters
displayNum The display number to activate (1 or 2)
1: First display (firstScreenCS)
2: Second display (secondScreenCS)
Warning
Always deselects all displays before selecting target
Note
Image rotation is configured via DISPLAY_IMAGE_ROTATION constant
Invalid display numbers are silently ignored
See also
selectDisplayForText() for text-specific rotation
deselectAll() for deactivating all displays
Since
v0.9
Definition at line 284 of file display_manager.cpp.
References deselectAll(), DISPLAY_IMAGE_ROTATION, DISPLAY_SPLASH_DURATION_MS, firstScreenCS, secondScreenCS, and tft.
Referenced by DisplayClockManager::displayClockOnBothDisplays(), ImageManager::displayImage(), and showSplashScreen().
selectDisplayForText()
void DisplayManager::selectDisplayForText (int displayNum)
📝 Selects display with text-optimized rotation
Activates the specified display and configures it for optimal text rendering by setting the text rotation (DISPLAY_TEXT_ROTATION). This method ensures text appears properly oriented for reading.
Parameters
displayNum The display number to activate (1 or 2)
1: First display (firstScreenCS)
2: Second display (secondScreenCS)
Warning
⚠️ Always deselects all displays before selecting target
Note
📌 Text rotation is configured via DISPLAY_TEXT_ROTATION constant
🔄 Invalid display numbers are silently ignored
See also
selectDisplayForImage() for image-specific rotation
deselectAll() for deactivating all displays
Since
v0.9
Definition at line 252 of file display_manager.cpp.
References deselectAll(), DISPLAY_SPLASH_DURATION_MS, DISPLAY_TEXT_ROTATION, firstScreenCS, secondScreenCS, and tft.
Referenced by selectDisplay().
setBrightness()
void DisplayManager::setBrightness (uint8_t brightness, int displayNum = 0)
Sets backlight brightness for specified display(s)
Controls the PWM-driven backlight brightness for one or both displays. Uses hardware PWM channels to provide smooth brightness control from 0 (completely off) to 255 (maximum brightness).
Channel mapping (hardware-specific):
Display 1: GPIO 27 on PWM Channel 2 (Blue display)
Display 2: GPIO 22 on PWM Channel 1 (Yellow display)
Parameters
brightness PWM duty cycle value (0-255) 0 = backlight off, 255 = maximum brightness
displayNum Target display number 1 = first display only 2 = second display only
0 = both displays
Note
Channel assignment is swapped due to hardware wiring
Brightness values are stored in brightness1/brightness2 variables
Uses ledcWrite() for hardware PWM control
See also
clearBothDisplaysToBlack() for setting brightness to 0
begin() for PWM channel initialization
Since
v0.9
Definition at line 393 of file display_manager.cpp.
References brightness1, brightness2, DISPLAY_SPLASH_DURATION_MS, and LOG_INFOF.
Referenced by clearBothDisplaysToBlack(), loop(), SettingsManager::setBrightness(), SettingsManager::setSecondDisplayEnabled(), WiFiManager::setupNormalModeRoutes(), and showSplashScreen().
setRotation()
void DisplayManager::setRotation (uint8_t rotation)
Sets rotation for all displays and TFT instance.
Configures the display rotation for both displays and the main TFT instance. This method ensures consistent rotation across all display operations and is particularly important for image operations that bypass display selection.
Rotation values:
0: No rotation (default)
1: 90 degrees clockwise
2: 180 degrees
3: 270 degrees clockwise
Parameters
rotation Rotation value (0-3)
Note
Returns immediately if DisplayManager not initialized
Sets rotation on main TFT instance first
Applies rotation to both individual displays
Automatically deselects displays after rotation setting
See also
selectDisplay() for display activation
deselectAll() for display deactivation
Since
v0.9
Definition at line 1157 of file display_manager.cpp.
References deselectAll(), DISPLAY_SPLASH_DURATION_MS, initialized, selectDisplay(), and tft.
Referenced by ImageManager::displayImage().
showAPReady()
void DisplayManager::showAPReady ()
Displays AP ready notification on primary display.
Shows a quick status message confirming that Access Point mode is ready and accepting connections. Uses blue background to indicate ready state. Provides clear visual confirmation of successful AP initialization.
Note
Uses showQuickStatus() with predefined message and color
Display 1 shows blue "AP Ready!" message
Display 2 remains dark during this status
See also
showQuickStatus() for underlying display mechanism
showAPStarting() for AP starting notification
Since
v0.9
Definition at line 665 of file display_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, and showQuickStatus().
showAPStarting()
void DisplayManager::showAPStarting ()
Displays AP starting notification on primary display.
Shows a quick status message indicating that Access Point mode is starting. Uses orange background color to indicate transition state. Provides immediate visual feedback during AP initialization process.
Note
Uses showQuickStatus() with predefined message and color
Display 1 shows orange "Starting AP..." message
Display 2 remains dark during this status
See also
showQuickStatus() for underlying display mechanism
showAPReady() for AP ready notification
Since
v0.9
Definition at line 644 of file display_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, and showQuickStatus().
Referenced by WiFiManager::initializeAP().
showConnecting()
void DisplayManager::showConnecting ()
Displays WiFi connection attempt notification.
Shows a quick status message indicating active WiFi connection attempt. Uses yellow background to indicate pending/in-progress state. Provides visual feedback during network connection process.
Note
Uses showQuickStatus() with predefined message and color
Display 1 shows yellow "Connecting..." message
Display 2 remains dark during this status
See also
showQuickStatus() for underlying display mechanism
showConnectionSuccess() for successful connection notification
Since
v0.9
Definition at line 686 of file display_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, and showQuickStatus().
Referenced by WiFiManager::connectToSavedNetwork(), and WiFiManager::handleConnect().
showConnectionSuccess()
void DisplayManager::showConnectionSuccess (const String & ip)
Displays WiFi connection success confirmation.
Shows confirmation message for successful WiFi connection including the assigned IP address. Uses blue background to indicate successful connection state and provides essential network information.
Display layout for 80x160 pixel screen (rotated):
Line 1: "Connected to Wi-Fi" confirmation
Line 2: "IP: XXX.XXX.XXX.XXX" address display
Parameters
ip The assigned IP address to display
Note
Display 1 shows blue background with white text
Display 2 remains dark with brightness set to 0
Uses left-aligned text positioning for readability
Returns immediately if DisplayManager not initialized
See also
showQuickStatus() for simple status messages
showPortalInfo() for portal configuration display
showConnecting() for connection attempt notification
Since
v0.9
Definition at line 780 of file display_manager.cpp.
References deselectAll(), DISPLAY_SPLASH_DURATION_MS, initialized, LOG_INFO, LOG_INFOF, LOG_WARN, selectDisplay(), and tft.
Referenced by WiFiManager::connectToSavedNetwork(), and WiFiManager::handleConnect().
showPortalInfo()
void DisplayManager::showPortalInfo (const String & ssid, const String & ip, const String & status)
Displays comprehensive portal configuration information.
Shows detailed portal information including SSID, IP address, and status on the primary display with green background. Designed for configuration portal mode when device acts as access point for initial setup.
Display layout uses optimized spacing for 160x80 pixel screen:
Line 1: SSID (typically "Billboard-Portal")
Line 2: IP address for portal access
Line 3: Current status message
Parameters
ssid Access point SSID name
ip IP address for portal access
status Current portal status message
Note
Display 1 shows green background with black text
Display 2 remains dark with brightness set to 0
Uses left-aligned text positioning to prevent clipping
Returns immediately if DisplayManager not initialized
See also
showQuickStatus() for simple status messages
showConnectionSuccess() for WiFi connection confirmation
showPortalSequence() for splash-to-portal transition
Since
v0.9
Definition at line 718 of file display_manager.cpp.
References deselectAll(), DISPLAY_SPLASH_DURATION_MS, initialized, LOG_INFO, LOG_WARN, selectDisplay(), and tft.
Referenced by updateSplashScreen().
showPortalSequence()
void DisplayManager::showPortalSequence (const String & ssid, const String & ip, const String & status)
Initiates splash-to-portal sequence with automatic transition.
Starts a timed sequence showing splash screen followed by portal configuration information. Stores portal data for delayed display after splash timeout completes.
Sequence timeline:
Immediate: Shows splash screen on both displays
After DISPLAY_SPLASH_DURATION_MS: Automatically shows portal info
Parameters
ssid Access point SSID for portal display
ip IP address for portal access
status Current portal status message
Note
Portal data is stored in pending variables for delayed display
Sets portalSequenceActive flag for updateSplashScreen()
Uses DISPLAY_SPLASH_DURATION_MS constant for timing
Splash displays on both screens (displayNum = 0)
See also
showSplashScreen() for splash display
updateSplashScreen() for automatic transition handling
showPortalInfo() for portal information display
Since
v0.9
Definition at line 1015 of file display_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, LOG_INFO, pendingIP, pendingSSID, pendingStatus, portalSequenceActive, and showSplashScreen().
Referenced by WiFiManager::initializeAP().
showQuickStatus()
void DisplayManager::showQuickStatus (const String & message, uint16_t color)
Displays quick status message on first display.
Shows a status message on display 1 with colored background while keeping display 2 dark. Designed for system notifications, errors, or status updates. Message is centered on screen with automatic text color selection for contrast.
Display behavior:
Display 1: Shows message with background color
Display 2: Always kept black with brightness 0
Parameters
message Text string to display on screen
color Background color (RGB565), also affects text color selection
Note
Text color automatically chosen: white on red background, black otherwise
Display 2 is always cleared and dimmed during status display
Returns immediately if DisplayManager not initialized
Uses centered text positioning at coordinates (80, 40)
See also
selectDisplay() for display activation
setBrightness() for backlight control
deselectAll() for display deactivation
Since
v0.9
Definition at line 592 of file display_manager.cpp.
References deselectAll(), DISPLAY_SPLASH_DURATION_MS, initialized, selectDisplay(), and tft.
Referenced by WiFiManager::connectToWiFi(), WiFiManager::handleConnect(), WiFiManager::initializeAP(), showAPReady(), showAPStarting(), and showConnecting().
showSplashScreen()
void DisplayManager::showSplashScreen (int displayNum = 0, unsigned long timeoutMs = 2000)
Displays splash screen on specified display(s) with timeout.
Shows a rotated color bitmap splash screen with automatic brightness control and timeout management. Can display on individual displays or both simultaneously. Uses image rotation for optimal presentation.
Features:
Automatic brightness boost to maximum (255) for visibility
Black background clearing before splash display
270-degree rotation for correct orientation
Configurable timeout with automatic state management
Parameters
displayNum Target display selection 0 = both displays (recursive call) 1 = first display only 2 = second display only
timeoutMs Splash screen timeout in milliseconds
Note
Sets splashActive flag and manages timing automatically
Uses selectDisplayForImage() for optimal image rotation
Splash bitmap must be defined as epd_bitmap_ constant
Portal sequence may follow after splash completion
See also
drawColorBitmapRotated() for bitmap rendering
updateSplashScreen() for timeout management
showPortalSequence() for splash-to-portal transition
Since
v0.9
Definition at line 937 of file display_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, drawColorBitmapRotated(), fillScreen(), LOG_INFOF, selectDisplayForImage(), setBrightness(), showSplashScreen(), SPLASH_HEIGHT, SPLASH_WIDTH, splashActive, splashStartTime, and splashTimeoutMs.
Referenced by showPortalSequence(), and showSplashScreen().
updateSplashScreen()
void DisplayManager::updateSplashScreen ()
Definition at line 969 of file display_manager.cpp.
References DISPLAY_SPLASH_DURATION_MS, fillScreen(), LOG_INFO, pendingIP, pendingSSID, pendingStatus, portalSequenceActive, showPortalInfo(), splashActive, splashStartTime, and splashTimeoutMs.
Referenced by loop().
Field Documentation
brightness1
uint8_t DisplayManager::brightness1 private
Definition at line 56 of file display_manager.h.
Referenced by setBrightness().
brightness2
uint8_t DisplayManager::brightness2 private
Brightness levels (0-255)
Definition at line 56 of file display_manager.h.
Referenced by setBrightness().
firstScreenCS
const int DisplayManager::firstScreenCS = DISPLAY_CS1_PIN static private
Primary display CS pin.
Definition at line 68 of file display_manager.h.
Referenced by deselectAll(), initializeCS(), initializeTFT(), selectDisplayForImage(), and selectDisplayForText().
initialized
bool DisplayManager::initialized private
Initialization status flag.
Definition at line 55 of file display_manager.h.
Referenced by begin(), setRotation(), showConnectionSuccess(), showPortalInfo(), and showQuickStatus().
pendingIP
String DisplayManager::pendingIP private
Definition at line 65 of file display_manager.h.
Referenced by showPortalSequence(), and updateSplashScreen().
pendingSSID
String DisplayManager::pendingSSID private
Definition at line 65 of file display_manager.h.
Referenced by showPortalSequence(), and updateSplashScreen().
pendingStatus
String DisplayManager::pendingStatus private
Connection details for display.
Definition at line 65 of file display_manager.h.
Referenced by showPortalSequence(), and updateSplashScreen().
portalSequenceActive
bool DisplayManager::portalSequenceActive private
Portal connection sequence status.
Definition at line 64 of file display_manager.h.
Referenced by showPortalSequence(), and updateSplashScreen().
secondScreenCS
const int DisplayManager::secondScreenCS = DISPLAY_CS2_PIN static private
Secondary display CS pin.
Definition at line 69 of file display_manager.h.
Referenced by deselectAll(), initializeCS(), initializeTFT(), selectDisplayForImage(), and selectDisplayForText().
splashActive
bool DisplayManager::splashActive private
Splash screen active status.
Definition at line 60 of file display_manager.h.
Referenced by isSplashActive(), showSplashScreen(), and updateSplashScreen().
splashStartTime
unsigned long DisplayManager::splashStartTime private
Splash screen start timestamp.
Definition at line 59 of file display_manager.h.
Referenced by showSplashScreen(), and updateSplashScreen().
splashTimeoutMs
unsigned long DisplayManager::splashTimeoutMs private
Splash timeout duration.
Definition at line 61 of file display_manager.h.
Referenced by showSplashScreen(), and updateSplashScreen().
tft
TFT_eSPI DisplayManager::tft private
TFT_eSPI library instance.
Definition at line 54 of file display_manager.h.
Referenced by alternateDisplays(), clearBothDisplaysToBlack(), drawColorBitmap(), drawColorBitmapRotated(), drawText(), enableSecondDisplay(), fillScreen(), getTFT(), initializeTFT(), selectDisplayForImage(), selectDisplayForText(), setRotation(), showConnectionSuccess(), showPortalInfo(), and showQuickStatus().
TFT_BACKLIGHT1_PIN
const int DisplayManager::TFT_BACKLIGHT1_PIN = DISPLAY_BLK1_PIN static private
Backlight 1 pin.
Definition at line 71 of file display_manager.h.
Referenced by initializeBacklight().
TFT_BACKLIGHT2_PIN
const int DisplayManager::TFT_BACKLIGHT2_PIN = DISPLAY_BLK2_PIN static private
Backlight 2 pin.
Definition at line 72 of file display_manager.h.
Referenced by initializeBacklight().
TFT_DC_PIN
const int DisplayManager::TFT_DC_PIN = DISPLAY_DC_PIN static private
DC pin (shared)
Definition at line 70 of file display_manager.h.
The documentation for this class was generated from the following files:
include/display_manager.h
src/display_manager.cpp