Dual Display Billboard: src/main.cpp File Reference
main.cpp File Reference
Dual Display Billboard System - Multi-Mode Application Entry Point.
#include <Arduino.h>
#include <LittleFS.h>
#include "logger.h"
#include "display_manager.h"
#include "wifi_manager.h"
#include "credential_manager.h"
#include "time_manager.h"
#include "settings_manager.h"
#include "image_manager.h"
#include "slideshow_manager.h"
#include "display_clock_manager.h"
#include "dcc_manager.h"
#include "memory_manager.h"
#include "platform_detector.h"
#include "config.h"
Functions
AsyncWebServer server (80)
void configureTCPSettings ()
void setup ()
void loop ()
Variables
DisplayManager displayManager
TimeManager timeManager
SettingsManager settingsManager
SlideshowManager slideshowManager & imageManager
WiFiManager wifiManager & server
CredentialManager credentialManager
unsigned long lastHeartbeat = 0
unsigned long startupTime = 0
bool systemInitialized = false
bool wifiInitialized = false
bool displayInitialized = false
bool timeInitialized = false
Detailed Description
Dual Display Billboard System - Multi-Mode Application Entry Point.
Advanced ESP32/ESP32-S3 based digital billboard system with dual ST7735 displays.
SYSTEM MODES:
TFT_TEST_ONLY: Hardware validation and basic display testing
SAFE_MODE_ONLY: Minimal functionality for troubleshooting
Production Mode: Full billboard system with WiFi, image management, and clock display
Initialize time system once WiFi is connected and in normal mode if (!timeInitialized && wifiInitialized && wifiManager.getCurrentMode() == WiFiManager::MODE_NORMAL) { LOG_INFO("MAIN", "Initializing time subsystem...");
if (timeManager.begin()) { LOG_INFO("MAIN", "Time manager initialized"); timeInitialized = true; } else { LOG_WARN("MAIN", "Time manager initialization failed - will retry later"); Don't set timeInitialized = true so it will retry later } }* - Dual 160x80 ST7735 TFT displays with independent control
WiFi management with captive portal setup
JPEG image upload and slideshow functionality
Multiple clock face styles with time synchronization
Professional logging system with configurable levels
Memory management and storage optimization
DCC (Digital Command Control) integration support
HARDWARE SUPPORT:
ESP32 DevKit (original)
ESP32-S3 DevKitC-1 (with 2MB PSRAM)
ST7735 TFT displays (160x80)
ST7789 TFT displays (240x240)
Author
Dual Display Billboard Project
Version
0.9
Date
2025
Definition in file main.cpp.
Function Documentation
configureTCPSettings()
void configureTCPSettings ()
Definition at line 218 of file main.cpp.
References DISPLAY_SPLASH_DURATION_MS.
Referenced by loop().
loop()
void loop ()
Definition at line 284 of file main.cpp.
References DisplayManager::alternateDisplays(), CredentialManager::begin(), DisplayManager::begin(), SettingsManager::begin(), SlideshowManager::begin(), TimeManager::begin(), configureTCPSettings(), credentialManager, DISPLAY_SPLASH_DURATION_MS, displayInitialized, displayManager, HEARTBEAT_INTERVAL, imageManager, SettingsManager::isImageEnabled(), lastHeartbeat, LOG_ERROR, LOG_INFO, LOG_INFOF, LOG_MEMORY_INFO, LOG_WARN, LOG_WARNF, MEMORY_CLEANUP, MEMORY_IS_CRITICAL, MEMORY_IS_LOW, MEMORY_STATUS, MEMORY_UPDATE, WiFiManager::MODE_NORMAL, SettingsManager::setDisplayManager(), settingsManager, STARTUP_DELAY, startupTime, systemInitialized, timeInitialized, timeManager, DisplayManager::updateSplashScreen(), and wifiInitialized.
server()
AsyncWebServer server (80)
setup()
void setup ()
Definition at line 246 of file main.cpp.
References PlatformDetector::detectPlatform(), DISPLAY_SPLASH_DURATION_MS, Logger::init(), MemoryManager::initialize(), LOG_ERROR, LOG_INFO, LOG_SYSTEM_INFO, LOG_WARN, MEMORY_STATUS, PlatformDetector::printPlatformInfo(), startupTime, and PlatformDetector::testPSRAMAllocation().
Variable Documentation
credentialManager
CredentialManager credentialManager
Definition at line 234 of file main.cpp.
Referenced by loop().
displayInitialized
bool displayInitialized = false
Definition at line 243 of file main.cpp.
Referenced by loop().
displayManager
DisplayClockManager clockManager & displayManager
Definition at line 214 of file main.cpp.
Referenced by loop().
imageManager
SlideshowManager slideshowManager& imageManager
Definition at line 231 of file main.cpp.
Referenced by loop().
lastHeartbeat
unsigned long lastHeartbeat = 0
Definition at line 237 of file main.cpp.
Referenced by loop().
server
WiFiManager wifiManager& server
Definition at line 233 of file main.cpp.
Referenced by TimeManager::loadNTPServer(), and TimeManager::saveNTPServer().
settingsManager
DCCManager dccManager & settingsManager
Definition at line 228 of file main.cpp.
Referenced by loop().
startupTime
unsigned long startupTime = 0
Definition at line 238 of file main.cpp.
Referenced by loop(), and setup().
systemInitialized
bool systemInitialized = false
Definition at line 241 of file main.cpp.
Referenced by loop().
timeInitialized
bool timeInitialized = false
Definition at line 244 of file main.cpp.
Referenced by loop().
timeManager
TimeManager timeManager
Definition at line 227 of file main.cpp.
Referenced by loop().
wifiInitialized
bool wifiInitialized = false
Definition at line 242 of file main.cpp.
Referenced by loop().