Dual Display Billboard: Version Namespace Reference
Version Namespace Reference
Version Information Namespace.
Functions
const String getFirmwareVersion ()
Get firmware version string.
const String getFirmwareVersionFull ()
Get full firmware version with build number.
const String getBuildNumber ()
Get build number in YYMMDDx format.
const String getBuildDate ()
Get build date in YYMMDD format.
const String getBuildTimestamp ()
Get build timestamp.
const String getBuildEnvironment ()
Get build environment name.
int getDailyBuildCount ()
Get daily build count.
const String getVersionInfoJson ()
Get comprehensive version information as JSON string.
void printVersionInfo (bool detailed=false)
Print version information to Serial.
Detailed Description
Version Information Namespace.
Provides centralized access to all firmware version and build information. All version data is automatically generated during build time.
Function Documentation
getBuildDate()
const String Version::getBuildDate () inline
Get build date in YYMMDD format.
Returns
Build date string (e.g., "250816")
Definition at line 80 of file version.h.
References BUILD_DATE, and DISPLAY_SPLASH_DURATION_MS.
Referenced by getVersionInfoJson(), and printVersionInfo().
getBuildEnvironment()
const String Version::getBuildEnvironment () inline
Get build environment name.
Returns
Environment string (e.g., "esp32dev-st7735-debug")
Definition at line 104 of file version.h.
References DISPLAY_SPLASH_DURATION_MS.
Referenced by getVersionInfoJson(), and printVersionInfo().
getBuildNumber()
const String Version::getBuildNumber () inline
Get build number in YYMMDDx format.
Returns
Build number string (e.g., "2508160")
Note
x = daily build counter (0-9)
Definition at line 68 of file version.h.
References DISPLAY_SPLASH_DURATION_MS.
Referenced by getVersionInfoJson(), and printVersionInfo().
getBuildTimestamp()
const String Version::getBuildTimestamp () inline
Get build timestamp.
Returns
Build timestamp string (e.g., "2025-08-16 14:30:25")
Definition at line 92 of file version.h.
References DISPLAY_SPLASH_DURATION_MS.
Referenced by getVersionInfoJson(), and printVersionInfo().
getDailyBuildCount()
int Version::getDailyBuildCount () inline
Get daily build count.
Returns
Daily build counter (0-9)
Definition at line 116 of file version.h.
References DISPLAY_SPLASH_DURATION_MS.
Referenced by getVersionInfoJson(), and printVersionInfo().
getFirmwareVersion()
const String Version::getFirmwareVersion () inline
Get firmware version string.
Returns
Base version string (e.g., "v0.9")
Note
Generated from current_version in platformio.ini
Definition at line 42 of file version.h.
References DISPLAY_SPLASH_DURATION_MS, and FIRMWARE_VERSION.
Referenced by getFirmwareVersionFull(), getVersionInfoJson(), and printVersionInfo().
getFirmwareVersionFull()
const String Version::getFirmwareVersionFull () inline
Get full firmware version with build number.
Returns
Full version string (e.g., "v0.9-build.2508160")
Note
Includes base version + build number
Definition at line 55 of file version.h.
References DISPLAY_SPLASH_DURATION_MS, and getFirmwareVersion().
Referenced by getVersionInfoJson(), and printVersionInfo().
getVersionInfoJson()
const String Version::getVersionInfoJson () inline
Get comprehensive version information as JSON string.
Returns
JSON formatted version information
Example output:
{
  "version": "v0.9",
  "fullVersion": "v0.9-build.2508160",
  "buildNumber": "2508160",
  "buildDate": "250816",
  "buildTimestamp": "2025-08-16 14:30:25",
  "environment": "esp32dev-st7735-debug",
  "dailyBuild": 0
}
Definition at line 141 of file version.h.
References DISPLAY_SPLASH_DURATION_MS, getBuildDate(), getBuildEnvironment(), getBuildNumber(), getBuildTimestamp(), getDailyBuildCount(), getFirmwareVersion(), and getFirmwareVersionFull().
printVersionInfo()
void Version::printVersionInfo (bool detailed = false) inline
Print version information to Serial.
Parameters
detailed Include detailed build information
Definition at line 158 of file version.h.
References DISPLAY_SPLASH_DURATION_MS, getBuildDate(), getBuildEnvironment(), getBuildNumber(), getBuildTimestamp(), getDailyBuildCount(), getFirmwareVersion(), and getFirmwareVersionFull().