name: Generate Documentation

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz
        
    - name: Generate documentation
      run: |
        doxygen Doxyfile
        
    - name: Create redirect page
      run: |
        mkdir -p gh-pages-deploy
        # Copy documentation to api-docs subdirectory
        cp -r docs/generated/html gh-pages-deploy/api-docs
        # Create root index.html that redirects to api-docs
        cat > gh-pages-deploy/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
          <meta http-equiv="refresh" content="0; url=api-docs/">
          <title>ESP32 Dual Display Billboard - Documentation</title>
        </head>
        <body>
          <h1>ESP32 Dual Display Billboard Documentation</h1>
          <p>Redirecting to <a href="api-docs/">API Documentation</a>...</p>
        </body>
        </html>
        EOF
        
    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/generated/html/
        retention-days: 30
        
    - name: Deploy to GitHub Pages (main branch only)
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages-deploy
